ALTER TABLE tasks DROP COLUMN IF EXISTS priority;
ALTER TABLE tasks DROP COLUMN IF EXISTS estimation;
DROP TABLE IF EXISTS task_watchers;
ALTER TABLE project_params ADD COLUMN IF NOT EXISTS description TEXT NOT NULL DEFAULT '';
ALTER TABLE board_fields ADD COLUMN IF NOT EXISTS description TEXT NOT NULL DEFAULT '';
