// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: admin_users.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const adminCreateUser = `-- name: AdminCreateUser :one
INSERT INTO users (username, email, password_hash, full_name, avatar_url, position, is_active, on_vacation, is_sick, alt_contact_channel, alt_contact_info)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, username, email, password_hash, full_name, avatar_url, position,
          is_active, on_vacation, is_sick, alt_contact_channel, alt_contact_info, deleted_at
`

type AdminCreateUserParams struct {
	Username          string         `json:"username"`
	Email             string         `json:"email"`
	PasswordHash      string         `json:"password_hash"`
	FullName          string         `json:"full_name"`
	AvatarUrl         sql.NullString `json:"avatar_url"`
	Position          sql.NullString `json:"position"`
	IsActive          bool           `json:"is_active"`
	OnVacation        bool           `json:"on_vacation"`
	IsSick            bool           `json:"is_sick"`
	AltContactChannel sql.NullString `json:"alt_contact_channel"`
	AltContactInfo    sql.NullString `json:"alt_contact_info"`
}

// Admin: create user with position and status fields
func (q *Queries) AdminCreateUser(ctx context.Context, arg AdminCreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, adminCreateUser,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
		arg.FullName,
		arg.AvatarUrl,
		arg.Position,
		arg.IsActive,
		arg.OnVacation,
		arg.IsSick,
		arg.AltContactChannel,
		arg.AltContactInfo,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.AvatarUrl,
		&i.Position,
		&i.IsActive,
		&i.OnVacation,
		&i.IsSick,
		&i.AltContactChannel,
		&i.AltContactInfo,
		&i.DeletedAt,
	)
	return i, err
}

const adminGetUserByID = `-- name: AdminGetUserByID :one
SELECT id, username, email, password_hash, full_name, avatar_url, position,
       is_active, on_vacation, is_sick, alt_contact_channel, alt_contact_info, deleted_at
FROM users
WHERE id = $1
`

// Admin: get user by ID (including deleted)
func (q *Queries) AdminGetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, adminGetUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.AvatarUrl,
		&i.Position,
		&i.IsActive,
		&i.OnVacation,
		&i.IsSick,
		&i.AltContactChannel,
		&i.AltContactInfo,
		&i.DeletedAt,
	)
	return i, err
}

const adminUpdateUser = `-- name: AdminUpdateUser :one
UPDATE users
SET username   = COALESCE(NULLIF($1::text, ''), username),
    email      = COALESCE(NULLIF($2::text, ''), email),
    full_name  = COALESCE(NULLIF($3::text, ''), full_name),
    position   = CASE WHEN $4::boolean THEN $5 ELSE position END,
    is_active  = CASE WHEN $6::boolean THEN $7::boolean ELSE is_active END,
    on_vacation = CASE WHEN $8::boolean THEN $9::boolean ELSE on_vacation END,
    is_sick     = CASE WHEN $10::boolean THEN $11::boolean ELSE is_sick END,
    alt_contact_channel = CASE WHEN $12::boolean THEN $13 ELSE alt_contact_channel END,
    alt_contact_info    = CASE WHEN $14::boolean THEN $15 ELSE alt_contact_info END
WHERE id = $16
RETURNING id, username, email, password_hash, full_name, avatar_url, position,
          is_active, on_vacation, is_sick, alt_contact_channel, alt_contact_info, deleted_at
`

type AdminUpdateUserParams struct {
	Username             string         `json:"username"`
	Email                string         `json:"email"`
	FullName             string         `json:"full_name"`
	SetPosition          bool           `json:"set_position"`
	Position             sql.NullString `json:"position"`
	SetIsActive          bool           `json:"set_is_active"`
	IsActive             bool           `json:"is_active"`
	SetOnVacation        bool           `json:"set_on_vacation"`
	OnVacation           bool           `json:"on_vacation"`
	SetIsSick            bool           `json:"set_is_sick"`
	IsSick               bool           `json:"is_sick"`
	SetAltContactChannel bool           `json:"set_alt_contact_channel"`
	AltContactChannel    sql.NullString `json:"alt_contact_channel"`
	SetAltContactInfo    bool           `json:"set_alt_contact_info"`
	AltContactInfo       sql.NullString `json:"alt_contact_info"`
	ID                   uuid.UUID      `json:"id"`
}

// Admin: update user fields
func (q *Queries) AdminUpdateUser(ctx context.Context, arg AdminUpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, adminUpdateUser,
		arg.Username,
		arg.Email,
		arg.FullName,
		arg.SetPosition,
		arg.Position,
		arg.SetIsActive,
		arg.IsActive,
		arg.SetOnVacation,
		arg.OnVacation,
		arg.SetIsSick,
		arg.IsSick,
		arg.SetAltContactChannel,
		arg.AltContactChannel,
		arg.SetAltContactInfo,
		arg.AltContactInfo,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.AvatarUrl,
		&i.Position,
		&i.IsActive,
		&i.OnVacation,
		&i.IsSick,
		&i.AltContactChannel,
		&i.AltContactInfo,
		&i.DeletedAt,
	)
	return i, err
}

const listAllUsers = `-- name: ListAllUsers :many
SELECT id, username, email, password_hash, full_name, avatar_url, position,
       is_active, on_vacation, is_sick, alt_contact_channel, alt_contact_info, deleted_at
FROM users
WHERE ($3::boolean IS TRUE OR deleted_at IS NULL)
ORDER BY username ASC
LIMIT $1 OFFSET $2
`

type ListAllUsersParams struct {
	Limit   int32 `json:"limit"`
	Offset  int32 `json:"offset"`
	Column3 bool  `json:"column_3"`
}

// Admin: list all users (with pagination, optional include deleted)
func (q *Queries) ListAllUsers(ctx context.Context, arg ListAllUsersParams) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listAllUsers, arg.Limit, arg.Offset, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.PasswordHash,
			&i.FullName,
			&i.AvatarUrl,
			&i.Position,
			&i.IsActive,
			&i.OnVacation,
			&i.IsSick,
			&i.AltContactChannel,
			&i.AltContactInfo,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllUsersCount = `-- name: ListAllUsersCount :one
SELECT COUNT(*) FROM users
WHERE ($1::boolean IS TRUE OR deleted_at IS NULL)
`

func (q *Queries) ListAllUsersCount(ctx context.Context, dollar_1 bool) (int64, error) {
	row := q.db.QueryRowContext(ctx, listAllUsersCount, dollar_1)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const softDeleteUser = `-- name: SoftDeleteUser :exec
UPDATE users
SET is_active = false,
    deleted_at = NOW()
WHERE id = $1
`

// Admin: soft delete user (deactivate and set deleted_at)
func (q *Queries) SoftDeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, softDeleteUser, id)
	return err
}
