// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: admin_users.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const adminCreateUser = `-- name: AdminCreateUser :one
INSERT INTO users (username, email, password_hash, full_name, avatar_url, position, is_active, on_vacation, is_sick, alt_contact_channel, alt_contact_info)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, username, email, password_hash, full_name, avatar_url, position,
          is_active, on_vacation, is_sick, alt_contact_channel, alt_contact_info, deleted_at, blocked_until
`

type AdminCreateUserParams struct {
	Username          string         `json:"username"`
	Email             string         `json:"email"`
	PasswordHash      string         `json:"password_hash"`
	FullName          string         `json:"full_name"`
	AvatarUrl         sql.NullString `json:"avatar_url"`
	Position          sql.NullString `json:"position"`
	IsActive          bool           `json:"is_active"`
	OnVacation        bool           `json:"on_vacation"`
	IsSick            bool           `json:"is_sick"`
	AltContactChannel sql.NullString `json:"alt_contact_channel"`
	AltContactInfo    sql.NullString `json:"alt_contact_info"`
}

// Admin: create user with position and status fields
func (q *Queries) AdminCreateUser(ctx context.Context, arg AdminCreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, adminCreateUser,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
		arg.FullName,
		arg.AvatarUrl,
		arg.Position,
		arg.IsActive,
		arg.OnVacation,
		arg.IsSick,
		arg.AltContactChannel,
		arg.AltContactInfo,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.AvatarUrl,
		&i.Position,
		&i.IsActive,
		&i.OnVacation,
		&i.IsSick,
		&i.AltContactChannel,
		&i.AltContactInfo,
		&i.DeletedAt,
		&i.BlockedUntil,
	)
	return i, err
}

const adminGetUserByID = `-- name: AdminGetUserByID :one
SELECT id, username, email, password_hash, full_name, avatar_url, position,
       is_active, on_vacation, is_sick, alt_contact_channel, alt_contact_info, deleted_at, blocked_until
FROM users
WHERE id = $1
`

// Admin: get user by ID (including deleted)
func (q *Queries) AdminGetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, adminGetUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.AvatarUrl,
		&i.Position,
		&i.IsActive,
		&i.OnVacation,
		&i.IsSick,
		&i.AltContactChannel,
		&i.AltContactInfo,
		&i.DeletedAt,
		&i.BlockedUntil,
	)
	return i, err
}

const adminUpdateUser = `-- name: AdminUpdateUser :one
UPDATE users
SET username   = COALESCE(NULLIF($1::text, ''), username),
    email      = COALESCE(NULLIF($2::text, ''), email),
    full_name  = COALESCE(NULLIF($3::text, ''), full_name),
    position   = CASE WHEN $4::boolean THEN $5 ELSE position END,
    is_active  = CASE WHEN $6::boolean THEN $7::boolean ELSE is_active END,
    on_vacation = CASE WHEN $8::boolean THEN $9::boolean ELSE on_vacation END,
    is_sick     = CASE WHEN $10::boolean THEN $11::boolean ELSE is_sick END,
    alt_contact_channel = CASE WHEN $12::boolean THEN $13 ELSE alt_contact_channel END,
    alt_contact_info    = CASE WHEN $14::boolean THEN $15 ELSE alt_contact_info END
WHERE id = $16
RETURNING id, username, email, password_hash, full_name, avatar_url, position,
          is_active, on_vacation, is_sick, alt_contact_channel, alt_contact_info, deleted_at, blocked_until
`

type AdminUpdateUserParams struct {
	Username             string         `json:"username"`
	Email                string         `json:"email"`
	FullName             string         `json:"full_name"`
	SetPosition          bool           `json:"set_position"`
	Position             sql.NullString `json:"position"`
	SetIsActive          bool           `json:"set_is_active"`
	IsActive             bool           `json:"is_active"`
	SetOnVacation        bool           `json:"set_on_vacation"`
	OnVacation           bool           `json:"on_vacation"`
	SetIsSick            bool           `json:"set_is_sick"`
	IsSick               bool           `json:"is_sick"`
	SetAltContactChannel bool           `json:"set_alt_contact_channel"`
	AltContactChannel    sql.NullString `json:"alt_contact_channel"`
	SetAltContactInfo    bool           `json:"set_alt_contact_info"`
	AltContactInfo       sql.NullString `json:"alt_contact_info"`
	ID                   uuid.UUID      `json:"id"`
}

// Admin: update user fields
func (q *Queries) AdminUpdateUser(ctx context.Context, arg AdminUpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, adminUpdateUser,
		arg.Username,
		arg.Email,
		arg.FullName,
		arg.SetPosition,
		arg.Position,
		arg.SetIsActive,
		arg.IsActive,
		arg.SetOnVacation,
		arg.OnVacation,
		arg.SetIsSick,
		arg.IsSick,
		arg.SetAltContactChannel,
		arg.AltContactChannel,
		arg.SetAltContactInfo,
		arg.AltContactInfo,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.AvatarUrl,
		&i.Position,
		&i.IsActive,
		&i.OnVacation,
		&i.IsSick,
		&i.AltContactChannel,
		&i.AltContactInfo,
		&i.DeletedAt,
		&i.BlockedUntil,
	)
	return i, err
}

const countActiveUsers = `-- name: CountActiveUsers :one
SELECT COUNT(*)::bigint FROM users
WHERE is_active = true
  AND ($1::boolean IS TRUE OR deleted_at IS NULL)
`

// Число активных пользователей по всему множеству (is_active=true).
// include_deleted управляет учётом soft-deleted. Независимо от q/is_active_filter/role_id —
// чтобы карточка «Активные» не менялась при фильтрации в таблице.
func (q *Queries) CountActiveUsers(ctx context.Context, dollar_1 bool) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveUsers, dollar_1)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countInactiveUsers = `-- name: CountInactiveUsers :one
SELECT COUNT(*)::bigint FROM users
WHERE is_active = false
  AND ($1::boolean IS TRUE OR deleted_at IS NULL)
`

// Число заблокированных/деактивированных пользователей по всему множеству (is_active=false).
func (q *Queries) CountInactiveUsers(ctx context.Context, dollar_1 bool) (int64, error) {
	row := q.db.QueryRowContext(ctx, countInactiveUsers, dollar_1)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const listAllUsers = `-- name: ListAllUsers :many
SELECT id, username, email, password_hash, full_name, avatar_url, position,
       is_active, on_vacation, is_sick, alt_contact_channel, alt_contact_info, deleted_at, blocked_until
FROM users u
WHERE ($1::boolean IS TRUE OR u.deleted_at IS NULL)
  AND ($2::text IS NULL OR $2::text = '' OR (
       u.username ILIKE '%' || $2 || '%'
    OR u.email    ILIKE '%' || $2 || '%'
    OR u.full_name ILIKE '%' || $2 || '%'
    OR COALESCE(u.position, '') ILIKE '%' || $2 || '%'))
  AND ($3::boolean IS NULL OR u.is_active = $3::boolean)
  AND ($4::uuid IS NULL OR EXISTS (
       SELECT 1 FROM user_roles ur WHERE ur.user_id = u.id AND ur.role_id = $4::uuid))
ORDER BY LOWER(u.full_name) ASC, u.id ASC
LIMIT $6 OFFSET $5
`

type ListAllUsersParams struct {
	IncludeDeleted bool           `json:"include_deleted"`
	Q              sql.NullString `json:"q"`
	IsActiveFilter sql.NullBool   `json:"is_active_filter"`
	RoleIDFilter   uuid.NullUUID  `json:"role_id_filter"`
	PageOffset     int32          `json:"page_offset"`
	PageLimit      int32          `json:"page_limit"`
}

// Admin: list all users с пагинацией и серверными фильтрами.
// include_deleted=true подключает soft-deleted; q (ILIKE по username/email/full_name/position),
// is_active_filter (true/false) и role_id_filter — опциональны, пропуск фильтра = nil.
func (q *Queries) ListAllUsers(ctx context.Context, arg ListAllUsersParams) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listAllUsers,
		arg.IncludeDeleted,
		arg.Q,
		arg.IsActiveFilter,
		arg.RoleIDFilter,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.PasswordHash,
			&i.FullName,
			&i.AvatarUrl,
			&i.Position,
			&i.IsActive,
			&i.OnVacation,
			&i.IsSick,
			&i.AltContactChannel,
			&i.AltContactInfo,
			&i.DeletedAt,
			&i.BlockedUntil,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllUsersCount = `-- name: ListAllUsersCount :one
SELECT COUNT(*)::bigint FROM users u
WHERE ($1::boolean IS TRUE OR u.deleted_at IS NULL)
  AND ($2::text IS NULL OR $2::text = '' OR (
       u.username ILIKE '%' || $2 || '%'
    OR u.email    ILIKE '%' || $2 || '%'
    OR u.full_name ILIKE '%' || $2 || '%'
    OR COALESCE(u.position, '') ILIKE '%' || $2 || '%'))
  AND ($3::boolean IS NULL OR u.is_active = $3::boolean)
  AND ($4::uuid IS NULL OR EXISTS (
       SELECT 1 FROM user_roles ur WHERE ur.user_id = u.id AND ur.role_id = $4::uuid))
`

type ListAllUsersCountParams struct {
	IncludeDeleted bool           `json:"include_deleted"`
	Q              sql.NullString `json:"q"`
	IsActiveFilter sql.NullBool   `json:"is_active_filter"`
	RoleIDFilter   uuid.NullUUID  `json:"role_id_filter"`
}

// Полное число записей под применённые фильтры (без учёта limit/offset).
func (q *Queries) ListAllUsersCount(ctx context.Context, arg ListAllUsersCountParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, listAllUsersCount,
		arg.IncludeDeleted,
		arg.Q,
		arg.IsActiveFilter,
		arg.RoleIDFilter,
	)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const softDeleteUser = `-- name: SoftDeleteUser :exec
UPDATE users
SET is_active = false,
    deleted_at = NOW()
WHERE id = $1
`

// Admin: soft delete user (deactivate and set deleted_at)
func (q *Queries) SoftDeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, softDeleteUser, id)
	return err
}
