// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: admin_users.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const adminCreateUser = `-- name: AdminCreateUser :one
INSERT INTO users (username, email, password_hash, full_name, avatar_url, position, is_active)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, username, email, password_hash, full_name, avatar_url, is_active, created_at, updated_at, deleted_at, position
`

type AdminCreateUserParams struct {
	Username     string         `json:"username"`
	Email        string         `json:"email"`
	PasswordHash string         `json:"password_hash"`
	FullName     string         `json:"full_name"`
	AvatarUrl    sql.NullString `json:"avatar_url"`
	Position     sql.NullString `json:"position"`
	IsActive     bool           `json:"is_active"`
}

// Admin: create user with position
func (q *Queries) AdminCreateUser(ctx context.Context, arg AdminCreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, adminCreateUser,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
		arg.FullName,
		arg.AvatarUrl,
		arg.Position,
		arg.IsActive,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.AvatarUrl,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Position,
	)
	return i, err
}

const adminGetUserByID = `-- name: AdminGetUserByID :one
SELECT id, username, email, password_hash, full_name, avatar_url, is_active, created_at, updated_at, deleted_at, position FROM users
WHERE id = $1
`

// Admin: get user by ID (including deleted)
func (q *Queries) AdminGetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, adminGetUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.AvatarUrl,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Position,
	)
	return i, err
}

const adminUpdateUser = `-- name: AdminUpdateUser :one
UPDATE users
SET username   = COALESCE(NULLIF($1::text, ''), username),
    email      = COALESCE(NULLIF($2::text, ''), email),
    full_name  = COALESCE(NULLIF($3::text, ''), full_name),
    position   = CASE WHEN $4::boolean THEN $5 ELSE position END,
    is_active  = CASE WHEN $6::boolean THEN $7::boolean ELSE is_active END,
    updated_at = NOW()
WHERE id = $8
RETURNING id, username, email, password_hash, full_name, avatar_url, is_active, created_at, updated_at, deleted_at, position
`

type AdminUpdateUserParams struct {
	Username    string         `json:"username"`
	Email       string         `json:"email"`
	FullName    string         `json:"full_name"`
	SetPosition bool           `json:"set_position"`
	Position    sql.NullString `json:"position"`
	SetIsActive bool           `json:"set_is_active"`
	IsActive    bool           `json:"is_active"`
	ID          uuid.UUID      `json:"id"`
}

// Admin: update user fields
func (q *Queries) AdminUpdateUser(ctx context.Context, arg AdminUpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, adminUpdateUser,
		arg.Username,
		arg.Email,
		arg.FullName,
		arg.SetPosition,
		arg.Position,
		arg.SetIsActive,
		arg.IsActive,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.AvatarUrl,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Position,
	)
	return i, err
}

const listAllUsers = `-- name: ListAllUsers :many
SELECT id, username, email, password_hash, full_name, avatar_url, is_active, created_at, updated_at, deleted_at, position
FROM users
WHERE ($3::boolean IS TRUE OR deleted_at IS NULL)
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListAllUsersParams struct {
	Limit   int32 `json:"limit"`
	Offset  int32 `json:"offset"`
	Column3 bool  `json:"column_3"`
}

// Admin: list all users (with pagination, optional include deleted)
func (q *Queries) ListAllUsers(ctx context.Context, arg ListAllUsersParams) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listAllUsers, arg.Limit, arg.Offset, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.PasswordHash,
			&i.FullName,
			&i.AvatarUrl,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllUsersCount = `-- name: ListAllUsersCount :one
SELECT COUNT(*) FROM users
WHERE ($1::boolean IS TRUE OR deleted_at IS NULL)
`

func (q *Queries) ListAllUsersCount(ctx context.Context, dollar_1 bool) (int64, error) {
	row := q.db.QueryRowContext(ctx, listAllUsersCount, dollar_1)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const softDeleteUser = `-- name: SoftDeleteUser :exec
UPDATE users
SET is_active = false,
    deleted_at = NOW(),
    updated_at = NOW()
WHERE id = $1
`

// Admin: soft delete user (deactivate and set deleted_at)
func (q *Queries) SoftDeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, softDeleteUser, id)
	return err
}
