// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: analytics_cache.sql

package db

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const cleanExpiredAnalyticsCache = `-- name: CleanExpiredAnalyticsCache :exec
DELETE FROM analytics_cache
WHERE expires_at <= NOW()
`

func (q *Queries) CleanExpiredAnalyticsCache(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, cleanExpiredAnalyticsCache)
	return err
}

const getAnalyticsCache = `-- name: GetAnalyticsCache :one
SELECT id, project_id, report_type, parameters, result_data, generated_at, expires_at
FROM analytics_cache
WHERE project_id = $1
  AND report_type = $2
  AND parameters = $3
  AND expires_at > NOW()
ORDER BY generated_at DESC
LIMIT 1
`

type GetAnalyticsCacheParams struct {
	ProjectID  uuid.UUID       `json:"project_id"`
	ReportType string          `json:"report_type"`
	Parameters json.RawMessage `json:"parameters"`
}

func (q *Queries) GetAnalyticsCache(ctx context.Context, arg GetAnalyticsCacheParams) (AnalyticsCache, error) {
	row := q.db.QueryRowContext(ctx, getAnalyticsCache, arg.ProjectID, arg.ReportType, arg.Parameters)
	var i AnalyticsCache
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ReportType,
		&i.Parameters,
		&i.ResultData,
		&i.GeneratedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const saveAnalyticsCache = `-- name: SaveAnalyticsCache :one

INSERT INTO analytics_cache (project_id, report_type, parameters, result_data, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, project_id, report_type, parameters, result_data, generated_at, expires_at
`

type SaveAnalyticsCacheParams struct {
	ProjectID  uuid.UUID       `json:"project_id"`
	ReportType string          `json:"report_type"`
	Parameters json.RawMessage `json:"parameters"`
	ResultData json.RawMessage `json:"result_data"`
	ExpiresAt  time.Time       `json:"expires_at"`
}

// Analytics cache storage
func (q *Queries) SaveAnalyticsCache(ctx context.Context, arg SaveAnalyticsCacheParams) (AnalyticsCache, error) {
	row := q.db.QueryRowContext(ctx, saveAnalyticsCache,
		arg.ProjectID,
		arg.ReportType,
		arg.Parameters,
		arg.ResultData,
		arg.ExpiresAt,
	)
	var i AnalyticsCache
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ReportType,
		&i.Parameters,
		&i.ResultData,
		&i.GeneratedAt,
		&i.ExpiresAt,
	)
	return i, err
}
