// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: analytics_kanban.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const getAverageCycleTimeByPeriod = `-- name: GetAverageCycleTimeByPeriod :many
WITH task_started AS (
    SELECT tsh.task_id, MIN(tsh.entered_at) AS started_at
    FROM task_status_history tsh
    JOIN columns c ON c.id = tsh.column_id
    WHERE c.system_type IN ('in_progress', 'paused')
    GROUP BY tsh.task_id
),
task_completed_at AS (
    SELECT tsh.task_id, MIN(tsh.entered_at) AS completed_at
    FROM task_status_history tsh
    JOIN columns c ON c.id = tsh.column_id
    WHERE c.system_type IN ('completed', 'cancelled')
    GROUP BY tsh.task_id
),
cycle_times AS (
    SELECT
        t.id AS task_id,
        t.class_of_service,
        tc.completed_at,
        (EXTRACT(EPOCH FROM (tc.completed_at - ts.started_at)) / 86400.0)::double precision AS cycle_time_days
    FROM tasks t
    JOIN task_started ts ON ts.task_id = t.id
    JOIN task_completed_at tc ON tc.task_id = t.id
    WHERE t.project_id = $1
      AND t.deleted_at IS NULL
      AND tc.completed_at >= ts.started_at
      AND tc.completed_at BETWEEN $2::timestamptz AND $3::timestamptz
      AND ($4::text IS NULL OR $4 = '' OR t.class_of_service = $4)
)
SELECT
    date_trunc($5::text, completed_at)::timestamp AS period_start,
    class_of_service,
    AVG(cycle_time_days)::float AS avg_cycle_time_days,
    COUNT(*)::int AS task_count
FROM cycle_times
GROUP BY date_trunc($5::text, completed_at), class_of_service
ORDER BY period_start, class_of_service
`

type GetAverageCycleTimeByPeriodParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	Column2   time.Time `json:"column_2"`
	Column3   time.Time `json:"column_3"`
	Column4   string    `json:"column_4"`
	Column5   string    `json:"column_5"`
}

type GetAverageCycleTimeByPeriodRow struct {
	PeriodStart      time.Time      `json:"period_start"`
	ClassOfService   sql.NullString `json:"class_of_service"`
	AvgCycleTimeDays float64        `json:"avg_cycle_time_days"`
	TaskCount        int32          `json:"task_count"`
}

// Average Cycle Time по периодам (day/week/month)
func (q *Queries) GetAverageCycleTimeByPeriod(ctx context.Context, arg GetAverageCycleTimeByPeriodParams) ([]GetAverageCycleTimeByPeriodRow, error) {
	rows, err := q.db.QueryContext(ctx, getAverageCycleTimeByPeriod,
		arg.ProjectID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAverageCycleTimeByPeriodRow{}
	for rows.Next() {
		var i GetAverageCycleTimeByPeriodRow
		if err := rows.Scan(
			&i.PeriodStart,
			&i.ClassOfService,
			&i.AvgCycleTimeDays,
			&i.TaskCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCfdColumnCountsByDate = `-- name: GetCfdColumnCountsByDate :many
WITH dates AS (
    SELECT generate_series($2::date, $3::date, '1 day'::interval)::date AS date
),
board_columns AS (
    SELECT id, name, "order"
    FROM columns
    WHERE columns.board_id = $4
),
task_completed AS (
    SELECT tsh.task_id, MIN(tsh.entered_at) AS completed_at
    FROM task_status_history tsh
    JOIN columns c ON c.id = tsh.column_id
    WHERE c.system_type IN ('completed', 'cancelled')
    GROUP BY tsh.task_id
),
task_column_on_date AS (
    SELECT DISTINCT ON (tsh.task_id, d.date)
        d.date,
        tsh.task_id,
        tsh.column_id
    FROM dates d
    CROSS JOIN task_status_history tsh
    JOIN columns c ON c.id = tsh.column_id
    AND c.board_id = $4
    JOIN tasks t ON t.id = tsh.task_id AND t.project_id = $1
    WHERE t.deleted_at IS NULL
      AND tsh.entered_at <= d.date + interval '1 day'
      AND (tsh.left_at IS NULL OR tsh.left_at::date > d.date)
      AND t.created_at <= d.date + interval '1 day'
      AND NOT EXISTS (
          SELECT 1 FROM task_completed tc
          WHERE tc.task_id = tsh.task_id AND tc.completed_at::date <= d.date
      )
    ORDER BY tsh.task_id, d.date, tsh.entered_at DESC
)
SELECT
    tcd.date,
    bc.id AS column_id,
    bc.name AS column_name,
    bc."order" AS column_order,
    COUNT(tcd.task_id)::int AS task_count
FROM dates d
CROSS JOIN board_columns bc
LEFT JOIN task_column_on_date tcd ON tcd.date = d.date AND tcd.column_id = bc.id
GROUP BY d.date, bc.id, bc.name, bc."order"
ORDER BY d.date, bc."order"
`

type GetCfdColumnCountsByDateParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	Column2   time.Time `json:"column_2"`
	Column3   time.Time `json:"column_3"`
	BoardID   uuid.UUID `json:"board_id"`
}

type GetCfdColumnCountsByDateRow struct {
	Date        sql.NullTime `json:"date"`
	ColumnID    uuid.UUID    `json:"column_id"`
	ColumnName  string       `json:"column_name"`
	ColumnOrder int16        `json:"column_order"`
	TaskCount   int32        `json:"task_count"`
}

// CFD: per-date, per-column count of tasks in that column (for a board)
func (q *Queries) GetCfdColumnCountsByDate(ctx context.Context, arg GetCfdColumnCountsByDateParams) ([]GetCfdColumnCountsByDateRow, error) {
	rows, err := q.db.QueryContext(ctx, getCfdColumnCountsByDate,
		arg.ProjectID,
		arg.Column2,
		arg.Column3,
		arg.BoardID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCfdColumnCountsByDateRow{}
	for rows.Next() {
		var i GetCfdColumnCountsByDateRow
		if err := rows.Scan(
			&i.Date,
			&i.ColumnID,
			&i.ColumnName,
			&i.ColumnOrder,
			&i.TaskCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCycleTimeScatterplot = `-- name: GetCycleTimeScatterplot :many
WITH task_started AS (
    SELECT
        tsh.task_id,
        MIN(tsh.entered_at) AS started_at
    FROM task_status_history tsh
    JOIN columns c ON c.id = tsh.column_id
    WHERE c.system_type IN ('in_progress', 'paused')
    GROUP BY tsh.task_id
),
task_completed_at AS (
    SELECT
        tsh.task_id,
        MIN(tsh.entered_at) AS completed_at
    FROM task_status_history tsh
    JOIN columns c ON c.id = tsh.column_id
    WHERE c.system_type IN ('completed', 'cancelled')
    GROUP BY tsh.task_id
)
SELECT
    t.id AS task_id,
    t.key AS task_key,
    t.class_of_service,
    tc.completed_at,
    (EXTRACT(EPOCH FROM (tc.completed_at - ts.started_at)) / 86400.0)::double precision AS cycle_time_days
FROM tasks t
JOIN task_started ts ON ts.task_id = t.id
JOIN task_completed_at tc ON tc.task_id = t.id
WHERE t.project_id = $1
  AND t.deleted_at IS NULL
  AND tc.completed_at >= ts.started_at
  AND tc.completed_at BETWEEN $2::timestamptz AND $3::timestamptz
  AND ($4::text IS NULL OR $4 = '' OR t.class_of_service = $4)
ORDER BY tc.completed_at
`

type GetCycleTimeScatterplotParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	Column2   time.Time `json:"column_2"`
	Column3   time.Time `json:"column_3"`
	Column4   string    `json:"column_4"`
}

type GetCycleTimeScatterplotRow struct {
	TaskID         uuid.UUID      `json:"task_id"`
	TaskKey        string         `json:"task_key"`
	ClassOfService sql.NullString `json:"class_of_service"`
	CompletedAt    interface{}    `json:"completed_at"`
	CycleTimeDays  float64        `json:"cycle_time_days"`
}

// Cycle Time: от первого входа в in_progress/paused до входа в completed/cancelled
func (q *Queries) GetCycleTimeScatterplot(ctx context.Context, arg GetCycleTimeScatterplotParams) ([]GetCycleTimeScatterplotRow, error) {
	rows, err := q.db.QueryContext(ctx, getCycleTimeScatterplot,
		arg.ProjectID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCycleTimeScatterplotRow{}
	for rows.Next() {
		var i GetCycleTimeScatterplotRow
		if err := rows.Scan(
			&i.TaskID,
			&i.TaskKey,
			&i.ClassOfService,
			&i.CompletedAt,
			&i.CycleTimeDays,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTaskCompletedAt = `-- name: GetTaskCompletedAt :many

SELECT
    tsh.task_id,
    MIN(tsh.entered_at) AS completed_at
FROM task_status_history tsh
JOIN columns c ON c.id = tsh.column_id
JOIN tasks t ON t.id = tsh.task_id
WHERE t.project_id = $1
  AND c.system_type IN ('completed', 'cancelled')
GROUP BY tsh.task_id
`

type GetTaskCompletedAtRow struct {
	TaskID      uuid.UUID   `json:"task_id"`
	CompletedAt interface{} `json:"completed_at"`
}

// Kanban analytics: CFD, Throughput, WIP
// Task completion: when task first entered completed/cancelled column
func (q *Queries) GetTaskCompletedAt(ctx context.Context, projectID uuid.UUID) ([]GetTaskCompletedAtRow, error) {
	rows, err := q.db.QueryContext(ctx, getTaskCompletedAt, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTaskCompletedAtRow{}
	for rows.Next() {
		var i GetTaskCompletedAtRow
		if err := rows.Scan(&i.TaskID, &i.CompletedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getThroughputByPeriod = `-- name: GetThroughputByPeriod :many
WITH task_completed AS (
    SELECT
        t.id AS task_id,
        t.class_of_service,
        MIN(tsh.entered_at) AS completed_at
    FROM tasks t
    JOIN task_status_history tsh ON tsh.task_id = t.id
    JOIN columns c ON c.id = tsh.column_id AND c.system_type IN ('completed', 'cancelled')
    WHERE t.project_id = $1
      AND t.deleted_at IS NULL
    GROUP BY t.id, t.class_of_service
)
SELECT
    date_trunc($4::text, tc.completed_at)::timestamp AS period_start,
    tc.class_of_service,
    COUNT(*)::int AS task_count
FROM task_completed tc
WHERE tc.completed_at BETWEEN $2::timestamptz AND $3::timestamptz
GROUP BY date_trunc($4::text, tc.completed_at), tc.class_of_service
ORDER BY period_start, tc.class_of_service
`

type GetThroughputByPeriodParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	Column2   time.Time `json:"column_2"`
	Column3   time.Time `json:"column_3"`
	Column4   string    `json:"column_4"`
}

type GetThroughputByPeriodRow struct {
	PeriodStart    time.Time      `json:"period_start"`
	ClassOfService sql.NullString `json:"class_of_service"`
	TaskCount      int32          `json:"task_count"`
}

// Throughput: count of tasks completed per period (week or day), optional class_of_service
func (q *Queries) GetThroughputByPeriod(ctx context.Context, arg GetThroughputByPeriodParams) ([]GetThroughputByPeriodRow, error) {
	rows, err := q.db.QueryContext(ctx, getThroughputByPeriod,
		arg.ProjectID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetThroughputByPeriodRow{}
	for rows.Next() {
		var i GetThroughputByPeriodRow
		if err := rows.Scan(&i.PeriodStart, &i.ClassOfService, &i.TaskCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getThroughputSimple = `-- name: GetThroughputSimple :many
WITH task_completed AS (
    SELECT
        t.id AS task_id,
        MIN(tsh.entered_at) AS completed_at
    FROM tasks t
    JOIN task_status_history tsh ON tsh.task_id = t.id
    JOIN columns c ON c.id = tsh.column_id AND c.system_type IN ('completed', 'cancelled')
    WHERE t.project_id = $1
      AND t.deleted_at IS NULL
    GROUP BY t.id
)
SELECT
    (date_trunc('day', tc.completed_at)::date)::timestamp AS day_start,
    COUNT(*)::int AS task_count
FROM task_completed tc
WHERE tc.completed_at BETWEEN $2::timestamptz AND $3::timestamptz
GROUP BY date_trunc('day', tc.completed_at)
ORDER BY day_start
`

type GetThroughputSimpleParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	Column2   time.Time `json:"column_2"`
	Column3   time.Time `json:"column_3"`
}

type GetThroughputSimpleRow struct {
	DayStart  time.Time `json:"day_start"`
	TaskCount int32     `json:"task_count"`
}

// Throughput simple (no group by class): for backward compatibility and simple charts
func (q *Queries) GetThroughputSimple(ctx context.Context, arg GetThroughputSimpleParams) ([]GetThroughputSimpleRow, error) {
	rows, err := q.db.QueryContext(ctx, getThroughputSimple, arg.ProjectID, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetThroughputSimpleRow{}
	for rows.Next() {
		var i GetThroughputSimpleRow
		if err := rows.Scan(&i.DayStart, &i.TaskCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWipOverTime = `-- name: GetWipOverTime :many
WITH dates AS (
    SELECT generate_series($2::date, $3::date, '1 day'::interval)::date AS date
),
task_completed AS (
    SELECT tsh.task_id, MIN(tsh.entered_at) AS completed_at
    FROM task_status_history tsh
    JOIN columns c ON c.id = tsh.column_id
    WHERE c.system_type IN ('completed', 'cancelled')
    GROUP BY tsh.task_id
),
wip_per_day AS (
    SELECT
        d.date,
        COUNT(t.id)::int AS wip_count
    FROM dates d
    CROSS JOIN tasks t
    LEFT JOIN task_completed tc ON tc.task_id = t.id
    JOIN columns col ON col.id = t.column_id
    WHERE t.project_id = $1
      AND t.deleted_at IS NULL
      AND t.created_at <= d.date + interval '1 day'
      AND (tc.completed_at IS NULL OR tc.completed_at::date > d.date)
      AND col.system_type NOT IN ('initial', 'completed', 'cancelled')
    GROUP BY d.date
)
SELECT date, wip_count
FROM wip_per_day
ORDER BY date
`

type GetWipOverTimeParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	Column2   time.Time `json:"column_2"`
	Column3   time.Time `json:"column_3"`
}

type GetWipOverTimeRow struct {
	Date     time.Time `json:"date"`
	WipCount int32     `json:"wip_count"`
}

// WIP over time: for each date, count of tasks in progress (not in initial, not completed)
func (q *Queries) GetWipOverTime(ctx context.Context, arg GetWipOverTimeParams) ([]GetWipOverTimeRow, error) {
	rows, err := q.db.QueryContext(ctx, getWipOverTime, arg.ProjectID, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetWipOverTimeRow{}
	for rows.Next() {
		var i GetWipOverTimeRow
		if err := rows.Scan(&i.Date, &i.WipCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWipWithAge = `-- name: GetWipWithAge :many
WITH dates AS (
    SELECT generate_series($2::date, $3::date, '1 day'::interval)::date AS date
),
task_completed AS (
    SELECT tsh.task_id, MIN(tsh.entered_at) AS completed_at
    FROM task_status_history tsh
    JOIN columns c ON c.id = tsh.column_id
    WHERE c.system_type IN ('completed', 'cancelled')
    GROUP BY tsh.task_id
),
task_in_progress_start AS (
    SELECT
        tsh.task_id,
        MIN(tsh.entered_at) AS started_at
    FROM task_status_history tsh
    JOIN columns c ON c.id = tsh.column_id
    WHERE c.system_type IN ('in_progress', 'paused')
    GROUP BY tsh.task_id
),
daily_wip AS (
    SELECT
        d.date,
        t.id AS task_id,
        COALESCE(tips.started_at, t.created_at) AS work_started_at
    FROM dates d
    JOIN tasks t ON t.project_id = $1 AND t.deleted_at IS NULL
    LEFT JOIN task_completed tc ON tc.task_id = t.id
    JOIN columns col ON col.id = t.column_id
    LEFT JOIN task_in_progress_start tips ON tips.task_id = t.id
    WHERE t.created_at <= d.date + interval '1 day'
      AND (tc.completed_at IS NULL OR tc.completed_at::date > d.date)
      AND col.system_type NOT IN ('initial', 'completed', 'cancelled')
)
SELECT
    date,
    COUNT(*)::int AS wip_count,
    COALESCE(AVG(EXTRACT(EPOCH FROM (date::timestamp + interval '1 day' - work_started_at)) / 86400.0), 0)::float AS avg_wip_age_days,
    COALESCE(MAX(EXTRACT(EPOCH FROM (date::timestamp + interval '1 day' - work_started_at)) / 86400.0), 0)::float AS max_wip_age_days
FROM daily_wip
GROUP BY date
ORDER BY date
`

type GetWipWithAgeParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	Column2   time.Time `json:"column_2"`
	Column3   time.Time `json:"column_3"`
}

type GetWipWithAgeRow struct {
	Date          time.Time `json:"date"`
	WipCount      int32     `json:"wip_count"`
	AvgWipAgeDays float64   `json:"avg_wip_age_days"`
	MaxWipAgeDays float64   `json:"max_wip_age_days"`
}

// WIP over time with age (avg/max age in days)
func (q *Queries) GetWipWithAge(ctx context.Context, arg GetWipWithAgeParams) ([]GetWipWithAgeRow, error) {
	rows, err := q.db.QueryContext(ctx, getWipWithAge, arg.ProjectID, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetWipWithAgeRow{}
	for rows.Next() {
		var i GetWipWithAgeRow
		if err := rows.Scan(
			&i.Date,
			&i.WipCount,
			&i.AvgWipAgeDays,
			&i.MaxWipAgeDays,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
