// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: attachments.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createAttachment = `-- name: CreateAttachment :one
INSERT INTO attachments (task_id, comment_id, file_name, file_path, file_size, content_type, uploaded_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, task_id, comment_id, file_name, file_path, file_size, content_type, uploaded_by, uploaded_at
`

type CreateAttachmentParams struct {
	TaskID      uuid.NullUUID `json:"task_id"`
	CommentID   uuid.NullUUID `json:"comment_id"`
	FileName    string        `json:"file_name"`
	FilePath    string        `json:"file_path"`
	FileSize    int64         `json:"file_size"`
	ContentType string        `json:"content_type"`
	UploadedBy  uuid.UUID     `json:"uploaded_by"`
}

func (q *Queries) CreateAttachment(ctx context.Context, arg CreateAttachmentParams) (Attachment, error) {
	row := q.db.QueryRowContext(ctx, createAttachment,
		arg.TaskID,
		arg.CommentID,
		arg.FileName,
		arg.FilePath,
		arg.FileSize,
		arg.ContentType,
		arg.UploadedBy,
	)
	var i Attachment
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.CommentID,
		&i.FileName,
		&i.FilePath,
		&i.FileSize,
		&i.ContentType,
		&i.UploadedBy,
		&i.UploadedAt,
	)
	return i, err
}

const deleteAttachment = `-- name: DeleteAttachment :exec
DELETE FROM attachments WHERE id = $1
`

func (q *Queries) DeleteAttachment(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteAttachment, id)
	return err
}

const getAttachmentByID = `-- name: GetAttachmentByID :one
SELECT id, task_id, comment_id, file_name, file_path, file_size, content_type, uploaded_by, uploaded_at
FROM attachments
WHERE id = $1
`

func (q *Queries) GetAttachmentByID(ctx context.Context, id uuid.UUID) (Attachment, error) {
	row := q.db.QueryRowContext(ctx, getAttachmentByID, id)
	var i Attachment
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.CommentID,
		&i.FileName,
		&i.FilePath,
		&i.FileSize,
		&i.ContentType,
		&i.UploadedBy,
		&i.UploadedAt,
	)
	return i, err
}

const listTaskAttachments = `-- name: ListTaskAttachments :many
SELECT id, task_id, comment_id, file_name, file_path, file_size, content_type, uploaded_by, uploaded_at
FROM attachments
WHERE task_id = $1
ORDER BY uploaded_at ASC
`

func (q *Queries) ListTaskAttachments(ctx context.Context, taskID uuid.NullUUID) ([]Attachment, error) {
	rows, err := q.db.QueryContext(ctx, listTaskAttachments, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Attachment{}
	for rows.Next() {
		var i Attachment
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.CommentID,
			&i.FileName,
			&i.FilePath,
			&i.FileSize,
			&i.ContentType,
			&i.UploadedBy,
			&i.UploadedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
