// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: attachments.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createCommentAttachment = `-- name: CreateCommentAttachment :one
INSERT INTO attachments (comment_id, file_name, file_path, uploaded_by)
VALUES ($1, $2, $3, $4)
RETURNING id, task_id, comment_id, file_name, file_path, uploaded_by, uploaded_at
`

type CreateCommentAttachmentParams struct {
	CommentID  uuid.NullUUID `json:"comment_id"`
	FileName   string        `json:"file_name"`
	FilePath   string        `json:"file_path"`
	UploadedBy uuid.UUID     `json:"uploaded_by"`
}

func (q *Queries) CreateCommentAttachment(ctx context.Context, arg CreateCommentAttachmentParams) (Attachment, error) {
	row := q.db.QueryRowContext(ctx, createCommentAttachment,
		arg.CommentID,
		arg.FileName,
		arg.FilePath,
		arg.UploadedBy,
	)
	var i Attachment
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.CommentID,
		&i.FileName,
		&i.FilePath,
		&i.UploadedBy,
		&i.UploadedAt,
	)
	return i, err
}

const createTaskAttachment = `-- name: CreateTaskAttachment :one

INSERT INTO attachments (task_id, file_name, file_path, uploaded_by)
VALUES ($1, $2, $3, $4)
RETURNING id, task_id, comment_id, file_name, file_path, uploaded_by, uploaded_at
`

type CreateTaskAttachmentParams struct {
	TaskID     uuid.NullUUID `json:"task_id"`
	FileName   string        `json:"file_name"`
	FilePath   string        `json:"file_path"`
	UploadedBy uuid.UUID     `json:"uploaded_by"`
}

// Attachments for tasks and comments
func (q *Queries) CreateTaskAttachment(ctx context.Context, arg CreateTaskAttachmentParams) (Attachment, error) {
	row := q.db.QueryRowContext(ctx, createTaskAttachment,
		arg.TaskID,
		arg.FileName,
		arg.FilePath,
		arg.UploadedBy,
	)
	var i Attachment
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.CommentID,
		&i.FileName,
		&i.FilePath,
		&i.UploadedBy,
		&i.UploadedAt,
	)
	return i, err
}

const listCommentAttachments = `-- name: ListCommentAttachments :many
SELECT id, task_id, comment_id, file_name, file_path, uploaded_by, uploaded_at
FROM attachments
WHERE comment_id = $1
ORDER BY uploaded_at DESC
`

func (q *Queries) ListCommentAttachments(ctx context.Context, commentID uuid.NullUUID) ([]Attachment, error) {
	rows, err := q.db.QueryContext(ctx, listCommentAttachments, commentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Attachment{}
	for rows.Next() {
		var i Attachment
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.CommentID,
			&i.FileName,
			&i.FilePath,
			&i.UploadedBy,
			&i.UploadedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskAttachments = `-- name: ListTaskAttachments :many
SELECT id, task_id, comment_id, file_name, file_path, uploaded_by, uploaded_at
FROM attachments
WHERE task_id = $1
ORDER BY uploaded_at DESC
`

func (q *Queries) ListTaskAttachments(ctx context.Context, taskID uuid.NullUUID) ([]Attachment, error) {
	rows, err := q.db.QueryContext(ctx, listTaskAttachments, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Attachment{}
	for rows.Next() {
		var i Attachment
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.CommentID,
			&i.FileName,
			&i.FilePath,
			&i.UploadedBy,
			&i.UploadedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
