// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit_log.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const countAuditLogs = `-- name: CountAuditLogs :one
SELECT COUNT(*)
FROM audit_log
WHERE ($1 IS NULL OR user_id = $1)
  AND ($2 IS NULL OR $2 = '' OR action_type = $2)
  AND ($3 IS NULL OR created_at >= $3)
  AND ($4 IS NULL OR created_at <= $4)
`

type CountAuditLogsParams struct {
	UserID     interface{} `json:"user_id"`
	ActionType interface{} `json:"action_type"`
	FromAt     interface{} `json:"from_at"`
	ToAt       interface{} `json:"to_at"`
}

// Количество записей по тем же фильтрам (для пагинации)
func (q *Queries) CountAuditLogs(ctx context.Context, arg CountAuditLogsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAuditLogs,
		arg.UserID,
		arg.ActionType,
		arg.FromAt,
		arg.ToAt,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertAuditLog = `-- name: InsertAuditLog :one
INSERT INTO audit_log (user_id, action_type, entity_type, entity_id, metadata)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, action_type, entity_type, entity_id, created_at, metadata
`

type InsertAuditLogParams struct {
	UserID     uuid.UUID             `json:"user_id"`
	ActionType string                `json:"action_type"`
	EntityType sql.NullString        `json:"entity_type"`
	EntityID   uuid.NullUUID         `json:"entity_id"`
	Metadata   pqtype.NullRawMessage `json:"metadata"`
}

// Добавить запись в журнал
func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRowContext(ctx, insertAuditLog,
		arg.UserID,
		arg.ActionType,
		arg.EntityType,
		arg.EntityID,
		arg.Metadata,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ActionType,
		&i.EntityType,
		&i.EntityID,
		&i.CreatedAt,
		&i.Metadata,
	)
	return i, err
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT id, user_id, action_type, entity_type, entity_id, created_at, metadata
FROM audit_log
WHERE ($1 IS NULL OR user_id = $1)
  AND ($2 IS NULL OR $2 = '' OR action_type = $2)
  AND ($3 IS NULL OR created_at >= $3)
  AND ($4 IS NULL OR created_at <= $4)
ORDER BY created_at DESC
LIMIT $6 OFFSET $5
`

type ListAuditLogsParams struct {
	UserID     interface{} `json:"user_id"`
	ActionType interface{} `json:"action_type"`
	FromAt     interface{} `json:"from_at"`
	ToAt       interface{} `json:"to_at"`
	Offset     int32       `json:"offset"`
	Limit      int32       `json:"limit"`
}

// Список записей журнала с фильтрами (user_id, action_type, from, to опциональны)
func (q *Queries) ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error) {
	rows, err := q.db.QueryContext(ctx, listAuditLogs,
		arg.UserID,
		arg.ActionType,
		arg.FromAt,
		arg.ToAt,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ActionType,
			&i.EntityType,
			&i.EntityID,
			&i.CreatedAt,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
