// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const countFailedAttemptsByIPSince = `-- name: CountFailedAttemptsByIPSince :one
SELECT COUNT(*)::INT
FROM login_attempts
WHERE ip_address = $1
  AND success = FALSE
  AND attempted_at >= $2
`

type CountFailedAttemptsByIPSinceParams struct {
	IpAddress   pqtype.Inet `json:"ip_address"`
	AttemptedAt time.Time   `json:"attempted_at"`
}

func (q *Queries) CountFailedAttemptsByIPSince(ctx context.Context, arg CountFailedAttemptsByIPSinceParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, countFailedAttemptsByIPSince, arg.IpAddress, arg.AttemptedAt)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countFailedAttemptsByUsernameSince = `-- name: CountFailedAttemptsByUsernameSince :one
SELECT COUNT(*)::INT
FROM login_attempts
WHERE username = $1
  AND success = FALSE
  AND attempted_at >= $2
`

type CountFailedAttemptsByUsernameSinceParams struct {
	Username    sql.NullString `json:"username"`
	AttemptedAt time.Time      `json:"attempted_at"`
}

func (q *Queries) CountFailedAttemptsByUsernameSince(ctx context.Context, arg CountFailedAttemptsByUsernameSinceParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, countFailedAttemptsByUsernameSince, arg.Username, arg.AttemptedAt)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createRefreshToken = `-- name: CreateRefreshToken :one

INSERT INTO refresh_tokens (user_id, token_hash, expires_at)
VALUES ($1, $2, $3)
RETURNING id, user_id, token_hash, expires_at, revoked_at, created_at
`

type CreateRefreshTokenParams struct {
	UserID    uuid.UUID `json:"user_id"`
	TokenHash string    `json:"token_hash"`
	ExpiresAt time.Time `json:"expires_at"`
}

// Refresh tokens
func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, createRefreshToken, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredBlockedIPs = `-- name: DeleteExpiredBlockedIPs :exec
DELETE FROM blocked_ips
WHERE blocked_until <= NOW()
`

func (q *Queries) DeleteExpiredBlockedIPs(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredBlockedIPs)
	return err
}

const deleteExpiredBlockedUsers = `-- name: DeleteExpiredBlockedUsers :exec
DELETE FROM blocked_users
WHERE blocked_until <= NOW()
`

func (q *Queries) DeleteExpiredBlockedUsers(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredBlockedUsers)
	return err
}

const getBlockedIP = `-- name: GetBlockedIP :one

SELECT ip_address, blocked_until
FROM blocked_ips
WHERE ip_address = $1
`

// Blocked IPs
func (q *Queries) GetBlockedIP(ctx context.Context, ipAddress pqtype.Inet) (BlockedIp, error) {
	row := q.db.QueryRowContext(ctx, getBlockedIP, ipAddress)
	var i BlockedIp
	err := row.Scan(&i.IpAddress, &i.BlockedUntil)
	return i, err
}

const getBlockedUser = `-- name: GetBlockedUser :one

SELECT user_id, blocked_until
FROM blocked_users
WHERE user_id = $1
`

// Blocked users
func (q *Queries) GetBlockedUser(ctx context.Context, userID uuid.UUID) (BlockedUser, error) {
	row := q.db.QueryRowContext(ctx, getBlockedUser, userID)
	var i BlockedUser
	err := row.Scan(&i.UserID, &i.BlockedUntil)
	return i, err
}

const getRefreshTokenByHash = `-- name: GetRefreshTokenByHash :one
SELECT id, user_id, token_hash, expires_at, revoked_at, created_at FROM refresh_tokens
WHERE token_hash = $1
`

func (q *Queries) GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, getRefreshTokenByHash, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertLoginAttempt = `-- name: InsertLoginAttempt :exec

INSERT INTO login_attempts (username, ip_address, success)
VALUES ($1, $2, $3)
`

type InsertLoginAttemptParams struct {
	Username  sql.NullString `json:"username"`
	IpAddress pqtype.Inet    `json:"ip_address"`
	Success   bool           `json:"success"`
}

// Login attempts
func (q *Queries) InsertLoginAttempt(ctx context.Context, arg InsertLoginAttemptParams) error {
	_, err := q.db.ExecContext(ctx, insertLoginAttempt, arg.Username, arg.IpAddress, arg.Success)
	return err
}

const revokeAllUserRefreshTokens = `-- name: RevokeAllUserRefreshTokens :exec
UPDATE refresh_tokens
SET revoked_at = NOW()
WHERE user_id = $1
  AND revoked_at IS NULL
`

func (q *Queries) RevokeAllUserRefreshTokens(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, revokeAllUserRefreshTokens, userID)
	return err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE refresh_tokens
SET revoked_at = NOW()
WHERE id = $1
`

func (q *Queries) RevokeRefreshToken(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, revokeRefreshToken, id)
	return err
}

const upsertBlockedIP = `-- name: UpsertBlockedIP :exec
INSERT INTO blocked_ips (ip_address, blocked_until)
VALUES ($1, $2)
ON CONFLICT (ip_address) DO UPDATE
SET blocked_until = EXCLUDED.blocked_until
`

type UpsertBlockedIPParams struct {
	IpAddress    pqtype.Inet `json:"ip_address"`
	BlockedUntil time.Time   `json:"blocked_until"`
}

func (q *Queries) UpsertBlockedIP(ctx context.Context, arg UpsertBlockedIPParams) error {
	_, err := q.db.ExecContext(ctx, upsertBlockedIP, arg.IpAddress, arg.BlockedUntil)
	return err
}

const upsertBlockedUser = `-- name: UpsertBlockedUser :exec
INSERT INTO blocked_users (user_id, blocked_until)
VALUES ($1, $2)
ON CONFLICT (user_id) DO UPDATE
SET blocked_until = EXCLUDED.blocked_until
`

type UpsertBlockedUserParams struct {
	UserID       uuid.UUID `json:"user_id"`
	BlockedUntil time.Time `json:"blocked_until"`
}

func (q *Queries) UpsertBlockedUser(ctx context.Context, arg UpsertBlockedUserParams) error {
	_, err := q.db.ExecContext(ctx, upsertBlockedUser, arg.UserID, arg.BlockedUntil)
	return err
}
