// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const clearExpiredUserBlocks = `-- name: ClearExpiredUserBlocks :exec
UPDATE users
SET blocked_until = NULL, is_active = true
WHERE blocked_until IS NOT NULL AND blocked_until <= NOW()
`

func (q *Queries) ClearExpiredUserBlocks(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearExpiredUserBlocks)
	return err
}

const countFailedAttemptsByIPSince = `-- name: CountFailedAttemptsByIPSince :one
SELECT COUNT(*)::INT
FROM login_attempts
WHERE ip_address = $1
  AND success = FALSE
  AND attempted_at >= $2
`

type CountFailedAttemptsByIPSinceParams struct {
	IpAddress   pqtype.Inet `json:"ip_address"`
	AttemptedAt time.Time   `json:"attempted_at"`
}

func (q *Queries) CountFailedAttemptsByIPSince(ctx context.Context, arg CountFailedAttemptsByIPSinceParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, countFailedAttemptsByIPSince, arg.IpAddress, arg.AttemptedAt)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countFailedAttemptsByUsernameSince = `-- name: CountFailedAttemptsByUsernameSince :one
SELECT COUNT(*)::INT
FROM login_attempts
WHERE username = $1
  AND success = FALSE
  AND attempted_at >= $2
`

type CountFailedAttemptsByUsernameSinceParams struct {
	Username    sql.NullString `json:"username"`
	AttemptedAt time.Time      `json:"attempted_at"`
}

func (q *Queries) CountFailedAttemptsByUsernameSince(ctx context.Context, arg CountFailedAttemptsByUsernameSinceParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, countFailedAttemptsByUsernameSince, arg.Username, arg.AttemptedAt)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createRefreshToken = `-- name: CreateRefreshToken :one

INSERT INTO tokens (user_id, token_hash, expires_at)
VALUES ($1, $2, $3)
RETURNING id, user_id, token_hash, expires_at, revoked_at
`

type CreateRefreshTokenParams struct {
	UserID    uuid.UUID `json:"user_id"`
	TokenHash string    `json:"token_hash"`
	ExpiresAt time.Time `json:"expires_at"`
}

// Refresh tokens
func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (Token, error) {
	row := q.db.QueryRowContext(ctx, createRefreshToken, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	var i Token
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const deleteExpiredBlockedIPs = `-- name: DeleteExpiredBlockedIPs :exec
DELETE FROM blocked_ips
WHERE blocked_until <= NOW()
`

func (q *Queries) DeleteExpiredBlockedIPs(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredBlockedIPs)
	return err
}

const getBlockedIP = `-- name: GetBlockedIP :one

SELECT ip_address, blocked_until
FROM blocked_ips
WHERE ip_address = $1
`

// Blocked IPs
func (q *Queries) GetBlockedIP(ctx context.Context, ipAddress pqtype.Inet) (BlockedIp, error) {
	row := q.db.QueryRowContext(ctx, getBlockedIP, ipAddress)
	var i BlockedIp
	err := row.Scan(&i.IpAddress, &i.BlockedUntil)
	return i, err
}

const getRefreshTokenByHash = `-- name: GetRefreshTokenByHash :one
SELECT id, user_id, token_hash, expires_at, revoked_at
FROM tokens
WHERE token_hash = $1
`

func (q *Queries) GetRefreshTokenByHash(ctx context.Context, tokenHash string) (Token, error) {
	row := q.db.QueryRowContext(ctx, getRefreshTokenByHash, tokenHash)
	var i Token
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const getUserBlockedUntil = `-- name: GetUserBlockedUntil :one

SELECT blocked_until
FROM users
WHERE id = $1
`

// Blocked users (temporary block via users.blocked_until)
func (q *Queries) GetUserBlockedUntil(ctx context.Context, id uuid.UUID) (sql.NullTime, error) {
	row := q.db.QueryRowContext(ctx, getUserBlockedUntil, id)
	var blocked_until sql.NullTime
	err := row.Scan(&blocked_until)
	return blocked_until, err
}

const insertLoginAttempt = `-- name: InsertLoginAttempt :exec

INSERT INTO login_attempts (username, ip_address, success)
VALUES ($1, $2, $3)
`

type InsertLoginAttemptParams struct {
	Username  sql.NullString `json:"username"`
	IpAddress pqtype.Inet    `json:"ip_address"`
	Success   bool           `json:"success"`
}

// Login attempts
func (q *Queries) InsertLoginAttempt(ctx context.Context, arg InsertLoginAttemptParams) error {
	_, err := q.db.ExecContext(ctx, insertLoginAttempt, arg.Username, arg.IpAddress, arg.Success)
	return err
}

const revokeAllUserRefreshTokens = `-- name: RevokeAllUserRefreshTokens :exec
UPDATE tokens
SET revoked_at = NOW()
WHERE user_id = $1
  AND revoked_at IS NULL
`

func (q *Queries) RevokeAllUserRefreshTokens(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, revokeAllUserRefreshTokens, userID)
	return err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE tokens
SET revoked_at = NOW()
WHERE id = $1
`

func (q *Queries) RevokeRefreshToken(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, revokeRefreshToken, id)
	return err
}

const setUserBlockedUntil = `-- name: SetUserBlockedUntil :exec
UPDATE users
SET blocked_until = $2, is_active = false
WHERE id = $1
`

type SetUserBlockedUntilParams struct {
	ID           uuid.UUID    `json:"id"`
	BlockedUntil sql.NullTime `json:"blocked_until"`
}

func (q *Queries) SetUserBlockedUntil(ctx context.Context, arg SetUserBlockedUntilParams) error {
	_, err := q.db.ExecContext(ctx, setUserBlockedUntil, arg.ID, arg.BlockedUntil)
	return err
}

const upsertBlockedIP = `-- name: UpsertBlockedIP :exec
INSERT INTO blocked_ips (ip_address, blocked_until)
VALUES ($1, $2)
ON CONFLICT (ip_address) DO UPDATE
SET blocked_until = EXCLUDED.blocked_until
`

type UpsertBlockedIPParams struct {
	IpAddress    pqtype.Inet `json:"ip_address"`
	BlockedUntil time.Time   `json:"blocked_until"`
}

func (q *Queries) UpsertBlockedIP(ctx context.Context, arg UpsertBlockedIPParams) error {
	_, err := q.db.ExecContext(ctx, upsertBlockedIP, arg.IpAddress, arg.BlockedUntil)
	return err
}
