// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: boards.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const countTasksInColumn = `-- name: CountTasksInColumn :one
SELECT COUNT(*)::int AS count FROM tasks WHERE column_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountTasksInColumn(ctx context.Context, columnID uuid.NullUUID) (int32, error) {
	row := q.db.QueryRowContext(ctx, countTasksInColumn, columnID)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const countTasksInSwimlane = `-- name: CountTasksInSwimlane :one
SELECT COUNT(*)::int AS count FROM tasks WHERE swimlane_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountTasksInSwimlane(ctx context.Context, swimlaneID uuid.NullUUID) (int32, error) {
	row := q.db.QueryRowContext(ctx, countTasksInSwimlane, swimlaneID)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const createBoard = `-- name: CreateBoard :one

INSERT INTO boards (project_id, template_id, name, description, sort_order, is_default, priority_type, estimation_unit, swimlane_group_by, priority_options)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, project_id, template_id, name, description, sort_order, priority_type, estimation_unit, swimlane_group_by, is_default, priority_options
`

type CreateBoardParams struct {
	ProjectID       uuid.NullUUID         `json:"project_id"`
	TemplateID      uuid.NullUUID         `json:"template_id"`
	Name            string                `json:"name"`
	Description     sql.NullString        `json:"description"`
	SortOrder       int16                 `json:"sort_order"`
	IsDefault       bool                  `json:"is_default"`
	PriorityType    string                `json:"priority_type"`
	EstimationUnit  string                `json:"estimation_unit"`
	SwimlaneGroupBy string                `json:"swimlane_group_by"`
	PriorityOptions pqtype.NullRawMessage `json:"priority_options"`
}

type CreateBoardRow struct {
	ID              uuid.UUID             `json:"id"`
	ProjectID       uuid.NullUUID         `json:"project_id"`
	TemplateID      uuid.NullUUID         `json:"template_id"`
	Name            string                `json:"name"`
	Description     sql.NullString        `json:"description"`
	SortOrder       int16                 `json:"sort_order"`
	PriorityType    string                `json:"priority_type"`
	EstimationUnit  string                `json:"estimation_unit"`
	SwimlaneGroupBy string                `json:"swimlane_group_by"`
	IsDefault       bool                  `json:"is_default"`
	PriorityOptions pqtype.NullRawMessage `json:"priority_options"`
}

// Boards
func (q *Queries) CreateBoard(ctx context.Context, arg CreateBoardParams) (CreateBoardRow, error) {
	row := q.db.QueryRowContext(ctx, createBoard,
		arg.ProjectID,
		arg.TemplateID,
		arg.Name,
		arg.Description,
		arg.SortOrder,
		arg.IsDefault,
		arg.PriorityType,
		arg.EstimationUnit,
		arg.SwimlaneGroupBy,
		arg.PriorityOptions,
	)
	var i CreateBoardRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.TemplateID,
		&i.Name,
		&i.Description,
		&i.SortOrder,
		&i.PriorityType,
		&i.EstimationUnit,
		&i.SwimlaneGroupBy,
		&i.IsDefault,
		&i.PriorityOptions,
	)
	return i, err
}

const createColumn = `-- name: CreateColumn :one
INSERT INTO columns (board_id, name, system_type, wip_limit, sort_order, is_locked)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, board_id, name, system_type, wip_limit, sort_order, is_locked, note
`

type CreateColumnParams struct {
	BoardID    uuid.UUID      `json:"board_id"`
	Name       string         `json:"name"`
	SystemType sql.NullString `json:"system_type"`
	WipLimit   sql.NullInt16  `json:"wip_limit"`
	SortOrder  int16          `json:"sort_order"`
	IsLocked   bool           `json:"is_locked"`
}

func (q *Queries) CreateColumn(ctx context.Context, arg CreateColumnParams) (Column, error) {
	row := q.db.QueryRowContext(ctx, createColumn,
		arg.BoardID,
		arg.Name,
		arg.SystemType,
		arg.WipLimit,
		arg.SortOrder,
		arg.IsLocked,
	)
	var i Column
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.Name,
		&i.SystemType,
		&i.WipLimit,
		&i.SortOrder,
		&i.IsLocked,
		&i.Note,
	)
	return i, err
}

const createNoteForColumn = `-- name: CreateNoteForColumn :one
INSERT INTO notes (column_id, content)
VALUES ($1, $2)
RETURNING id, column_id, swimlane_id, content
`

type CreateNoteForColumnParams struct {
	ColumnID uuid.NullUUID `json:"column_id"`
	Content  string        `json:"content"`
}

func (q *Queries) CreateNoteForColumn(ctx context.Context, arg CreateNoteForColumnParams) (Note, error) {
	row := q.db.QueryRowContext(ctx, createNoteForColumn, arg.ColumnID, arg.Content)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.ColumnID,
		&i.SwimlaneID,
		&i.Content,
	)
	return i, err
}

const createNoteForSwimlane = `-- name: CreateNoteForSwimlane :one
INSERT INTO notes (swimlane_id, content)
VALUES ($1, $2)
RETURNING id, column_id, swimlane_id, content
`

type CreateNoteForSwimlaneParams struct {
	SwimlaneID uuid.NullUUID `json:"swimlane_id"`
	Content    string        `json:"content"`
}

func (q *Queries) CreateNoteForSwimlane(ctx context.Context, arg CreateNoteForSwimlaneParams) (Note, error) {
	row := q.db.QueryRowContext(ctx, createNoteForSwimlane, arg.SwimlaneID, arg.Content)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.ColumnID,
		&i.SwimlaneID,
		&i.Content,
	)
	return i, err
}

const createSwimlane = `-- name: CreateSwimlane :one
INSERT INTO swimlanes (board_id, name, wip_limit, sort_order)
VALUES ($1, $2, $3, $4)
RETURNING id, board_id, name, wip_limit, sort_order, note
`

type CreateSwimlaneParams struct {
	BoardID   uuid.UUID     `json:"board_id"`
	Name      string        `json:"name"`
	WipLimit  sql.NullInt16 `json:"wip_limit"`
	SortOrder int16         `json:"sort_order"`
}

func (q *Queries) CreateSwimlane(ctx context.Context, arg CreateSwimlaneParams) (Swimlane, error) {
	row := q.db.QueryRowContext(ctx, createSwimlane,
		arg.BoardID,
		arg.Name,
		arg.WipLimit,
		arg.SortOrder,
	)
	var i Swimlane
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.Name,
		&i.WipLimit,
		&i.SortOrder,
		&i.Note,
	)
	return i, err
}

const deleteBoard = `-- name: DeleteBoard :exec
DELETE FROM boards
WHERE id = $1
`

func (q *Queries) DeleteBoard(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteBoard, id)
	return err
}

const deleteColumn = `-- name: DeleteColumn :exec
DELETE FROM columns
WHERE id = $1
`

func (q *Queries) DeleteColumn(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteColumn, id)
	return err
}

const deleteNote = `-- name: DeleteNote :exec
DELETE FROM notes
WHERE id = $1
`

func (q *Queries) DeleteNote(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteNote, id)
	return err
}

const deleteSwimlane = `-- name: DeleteSwimlane :exec
DELETE FROM swimlanes
WHERE id = $1
`

func (q *Queries) DeleteSwimlane(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteSwimlane, id)
	return err
}

const getBoardByID = `-- name: GetBoardByID :one
SELECT id, project_id, template_id, name, description, sort_order, priority_type, estimation_unit, swimlane_group_by, is_default, priority_options
FROM boards
WHERE id = $1
`

type GetBoardByIDRow struct {
	ID              uuid.UUID             `json:"id"`
	ProjectID       uuid.NullUUID         `json:"project_id"`
	TemplateID      uuid.NullUUID         `json:"template_id"`
	Name            string                `json:"name"`
	Description     sql.NullString        `json:"description"`
	SortOrder       int16                 `json:"sort_order"`
	PriorityType    string                `json:"priority_type"`
	EstimationUnit  string                `json:"estimation_unit"`
	SwimlaneGroupBy string                `json:"swimlane_group_by"`
	IsDefault       bool                  `json:"is_default"`
	PriorityOptions pqtype.NullRawMessage `json:"priority_options"`
}

func (q *Queries) GetBoardByID(ctx context.Context, id uuid.UUID) (GetBoardByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getBoardByID, id)
	var i GetBoardByIDRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.TemplateID,
		&i.Name,
		&i.Description,
		&i.SortOrder,
		&i.PriorityType,
		&i.EstimationUnit,
		&i.SwimlaneGroupBy,
		&i.IsDefault,
		&i.PriorityOptions,
	)
	return i, err
}

const getColumnByID = `-- name: GetColumnByID :one
SELECT id, board_id, name, system_type, wip_limit, sort_order, is_locked, note
FROM columns
WHERE id = $1
`

func (q *Queries) GetColumnByID(ctx context.Context, id uuid.UUID) (Column, error) {
	row := q.db.QueryRowContext(ctx, getColumnByID, id)
	var i Column
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.Name,
		&i.SystemType,
		&i.WipLimit,
		&i.SortOrder,
		&i.IsLocked,
		&i.Note,
	)
	return i, err
}

const getNoteByID = `-- name: GetNoteByID :one
SELECT id, column_id, swimlane_id, content
FROM notes
WHERE id = $1
`

func (q *Queries) GetNoteByID(ctx context.Context, id uuid.UUID) (Note, error) {
	row := q.db.QueryRowContext(ctx, getNoteByID, id)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.ColumnID,
		&i.SwimlaneID,
		&i.Content,
	)
	return i, err
}

const getSwimlaneByID = `-- name: GetSwimlaneByID :one
SELECT id, board_id, name, wip_limit, sort_order, note
FROM swimlanes
WHERE id = $1
`

func (q *Queries) GetSwimlaneByID(ctx context.Context, id uuid.UUID) (Swimlane, error) {
	row := q.db.QueryRowContext(ctx, getSwimlaneByID, id)
	var i Swimlane
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.Name,
		&i.WipLimit,
		&i.SortOrder,
		&i.Note,
	)
	return i, err
}

const listBoardColumns = `-- name: ListBoardColumns :many

SELECT id, board_id, name, system_type, wip_limit, sort_order, is_locked, note
FROM columns
WHERE board_id = $1
ORDER BY sort_order
`

// Columns
func (q *Queries) ListBoardColumns(ctx context.Context, boardID uuid.UUID) ([]Column, error) {
	rows, err := q.db.QueryContext(ctx, listBoardColumns, boardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Column{}
	for rows.Next() {
		var i Column
		if err := rows.Scan(
			&i.ID,
			&i.BoardID,
			&i.Name,
			&i.SystemType,
			&i.WipLimit,
			&i.SortOrder,
			&i.IsLocked,
			&i.Note,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBoardNotes = `-- name: ListBoardNotes :many

SELECT n.id, n.column_id, n.swimlane_id, n.content
FROM notes n
JOIN columns c ON n.column_id = c.id
WHERE c.board_id = $1
UNION ALL
SELECT n.id, n.column_id, n.swimlane_id, n.content
FROM notes n
JOIN swimlanes s ON n.swimlane_id = s.id
WHERE s.board_id = $1
`

// Notes
func (q *Queries) ListBoardNotes(ctx context.Context, boardID uuid.UUID) ([]Note, error) {
	rows, err := q.db.QueryContext(ctx, listBoardNotes, boardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Note{}
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.ColumnID,
			&i.SwimlaneID,
			&i.Content,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBoardSwimlanes = `-- name: ListBoardSwimlanes :many

SELECT id, board_id, name, wip_limit, sort_order, note
FROM swimlanes
WHERE board_id = $1
ORDER BY sort_order
`

// Swimlanes
func (q *Queries) ListBoardSwimlanes(ctx context.Context, boardID uuid.UUID) ([]Swimlane, error) {
	rows, err := q.db.QueryContext(ctx, listBoardSwimlanes, boardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Swimlane{}
	for rows.Next() {
		var i Swimlane
		if err := rows.Scan(
			&i.ID,
			&i.BoardID,
			&i.Name,
			&i.WipLimit,
			&i.SortOrder,
			&i.Note,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectBoards = `-- name: ListProjectBoards :many
SELECT id, project_id, template_id, name, description, sort_order, priority_type, estimation_unit, swimlane_group_by, is_default, priority_options
FROM boards
WHERE project_id = $1
ORDER BY sort_order
`

type ListProjectBoardsRow struct {
	ID              uuid.UUID             `json:"id"`
	ProjectID       uuid.NullUUID         `json:"project_id"`
	TemplateID      uuid.NullUUID         `json:"template_id"`
	Name            string                `json:"name"`
	Description     sql.NullString        `json:"description"`
	SortOrder       int16                 `json:"sort_order"`
	PriorityType    string                `json:"priority_type"`
	EstimationUnit  string                `json:"estimation_unit"`
	SwimlaneGroupBy string                `json:"swimlane_group_by"`
	IsDefault       bool                  `json:"is_default"`
	PriorityOptions pqtype.NullRawMessage `json:"priority_options"`
}

func (q *Queries) ListProjectBoards(ctx context.Context, projectID uuid.NullUUID) ([]ListProjectBoardsRow, error) {
	rows, err := q.db.QueryContext(ctx, listProjectBoards, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectBoardsRow{}
	for rows.Next() {
		var i ListProjectBoardsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.TemplateID,
			&i.Name,
			&i.Description,
			&i.SortOrder,
			&i.PriorityType,
			&i.EstimationUnit,
			&i.SwimlaneGroupBy,
			&i.IsDefault,
			&i.PriorityOptions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unsetDefaultBoardByProjectID = `-- name: UnsetDefaultBoardByProjectID :exec
UPDATE boards SET is_default = false WHERE project_id = $1 AND is_default = true
`

func (q *Queries) UnsetDefaultBoardByProjectID(ctx context.Context, projectID uuid.NullUUID) error {
	_, err := q.db.ExecContext(ctx, unsetDefaultBoardByProjectID, projectID)
	return err
}

const updateBoard = `-- name: UpdateBoard :one
UPDATE boards
SET name        = COALESCE($1, name),
    description = $2,
    sort_order  = COALESCE($3, sort_order),
    priority_type    = COALESCE($4, priority_type),
    estimation_unit  = COALESCE($5, estimation_unit),
    swimlane_group_by = COALESCE($6, swimlane_group_by),
    is_default = COALESCE($7, is_default),
    priority_options = COALESCE($8, priority_options)
WHERE id = $9
RETURNING id, project_id, template_id, name, description, sort_order, priority_type, estimation_unit, swimlane_group_by, is_default, priority_options
`

type UpdateBoardParams struct {
	Name            sql.NullString        `json:"name"`
	Description     sql.NullString        `json:"description"`
	SortOrder       sql.NullInt16         `json:"sort_order"`
	PriorityType    sql.NullString        `json:"priority_type"`
	EstimationUnit  sql.NullString        `json:"estimation_unit"`
	SwimlaneGroupBy sql.NullString        `json:"swimlane_group_by"`
	IsDefault       sql.NullBool          `json:"is_default"`
	PriorityOptions pqtype.NullRawMessage `json:"priority_options"`
	ID              uuid.UUID             `json:"id"`
}

type UpdateBoardRow struct {
	ID              uuid.UUID             `json:"id"`
	ProjectID       uuid.NullUUID         `json:"project_id"`
	TemplateID      uuid.NullUUID         `json:"template_id"`
	Name            string                `json:"name"`
	Description     sql.NullString        `json:"description"`
	SortOrder       int16                 `json:"sort_order"`
	PriorityType    string                `json:"priority_type"`
	EstimationUnit  string                `json:"estimation_unit"`
	SwimlaneGroupBy string                `json:"swimlane_group_by"`
	IsDefault       bool                  `json:"is_default"`
	PriorityOptions pqtype.NullRawMessage `json:"priority_options"`
}

func (q *Queries) UpdateBoard(ctx context.Context, arg UpdateBoardParams) (UpdateBoardRow, error) {
	row := q.db.QueryRowContext(ctx, updateBoard,
		arg.Name,
		arg.Description,
		arg.SortOrder,
		arg.PriorityType,
		arg.EstimationUnit,
		arg.SwimlaneGroupBy,
		arg.IsDefault,
		arg.PriorityOptions,
		arg.ID,
	)
	var i UpdateBoardRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.TemplateID,
		&i.Name,
		&i.Description,
		&i.SortOrder,
		&i.PriorityType,
		&i.EstimationUnit,
		&i.SwimlaneGroupBy,
		&i.IsDefault,
		&i.PriorityOptions,
	)
	return i, err
}

const updateBoardOrder = `-- name: UpdateBoardOrder :exec
UPDATE boards SET sort_order = $2 WHERE id = $1
`

type UpdateBoardOrderParams struct {
	ID        uuid.UUID `json:"id"`
	SortOrder int16     `json:"sort_order"`
}

func (q *Queries) UpdateBoardOrder(ctx context.Context, arg UpdateBoardOrderParams) error {
	_, err := q.db.ExecContext(ctx, updateBoardOrder, arg.ID, arg.SortOrder)
	return err
}

const updateColumn = `-- name: UpdateColumn :one
UPDATE columns
SET name        = COALESCE($1, name),
    system_type = $2,
    wip_limit   = $3,
    sort_order  = COALESCE($4, sort_order)
WHERE id = $5
RETURNING id, board_id, name, system_type, wip_limit, sort_order, is_locked, note
`

type UpdateColumnParams struct {
	Name       sql.NullString `json:"name"`
	SystemType sql.NullString `json:"system_type"`
	WipLimit   sql.NullInt16  `json:"wip_limit"`
	SortOrder  sql.NullInt16  `json:"sort_order"`
	ID         uuid.UUID      `json:"id"`
}

func (q *Queries) UpdateColumn(ctx context.Context, arg UpdateColumnParams) (Column, error) {
	row := q.db.QueryRowContext(ctx, updateColumn,
		arg.Name,
		arg.SystemType,
		arg.WipLimit,
		arg.SortOrder,
		arg.ID,
	)
	var i Column
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.Name,
		&i.SystemType,
		&i.WipLimit,
		&i.SortOrder,
		&i.IsLocked,
		&i.Note,
	)
	return i, err
}

const updateColumnOrder = `-- name: UpdateColumnOrder :exec
UPDATE columns SET sort_order = $2 WHERE id = $1
`

type UpdateColumnOrderParams struct {
	ID        uuid.UUID `json:"id"`
	SortOrder int16     `json:"sort_order"`
}

func (q *Queries) UpdateColumnOrder(ctx context.Context, arg UpdateColumnOrderParams) error {
	_, err := q.db.ExecContext(ctx, updateColumnOrder, arg.ID, arg.SortOrder)
	return err
}

const updateNote = `-- name: UpdateNote :one
UPDATE notes
SET content = COALESCE($1, content)
WHERE id = $2
RETURNING id, column_id, swimlane_id, content
`

type UpdateNoteParams struct {
	Content sql.NullString `json:"content"`
	ID      uuid.UUID      `json:"id"`
}

func (q *Queries) UpdateNote(ctx context.Context, arg UpdateNoteParams) (Note, error) {
	row := q.db.QueryRowContext(ctx, updateNote, arg.Content, arg.ID)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.ColumnID,
		&i.SwimlaneID,
		&i.Content,
	)
	return i, err
}

const updateSwimlane = `-- name: UpdateSwimlane :one
UPDATE swimlanes
SET name       = COALESCE($1, name),
    wip_limit  = $2,
    sort_order = COALESCE($3, sort_order)
WHERE id = $4
RETURNING id, board_id, name, wip_limit, sort_order, note
`

type UpdateSwimlaneParams struct {
	Name      sql.NullString `json:"name"`
	WipLimit  sql.NullInt16  `json:"wip_limit"`
	SortOrder sql.NullInt16  `json:"sort_order"`
	ID        uuid.UUID      `json:"id"`
}

func (q *Queries) UpdateSwimlane(ctx context.Context, arg UpdateSwimlaneParams) (Swimlane, error) {
	row := q.db.QueryRowContext(ctx, updateSwimlane,
		arg.Name,
		arg.WipLimit,
		arg.SortOrder,
		arg.ID,
	)
	var i Swimlane
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.Name,
		&i.WipLimit,
		&i.SortOrder,
		&i.Note,
	)
	return i, err
}

const updateSwimlaneOrder = `-- name: UpdateSwimlaneOrder :exec
UPDATE swimlanes SET sort_order = $2 WHERE id = $1
`

type UpdateSwimlaneOrderParams struct {
	ID        uuid.UUID `json:"id"`
	SortOrder int16     `json:"sort_order"`
}

func (q *Queries) UpdateSwimlaneOrder(ctx context.Context, arg UpdateSwimlaneOrderParams) error {
	_, err := q.db.ExecContext(ctx, updateSwimlaneOrder, arg.ID, arg.SortOrder)
	return err
}
