// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: boards.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createBoard = `-- name: CreateBoard :one

INSERT INTO boards (project_id, template_id, name, description, "order")
VALUES ($1, $2, $3, $4, $5)
RETURNING id, project_id, template_id, name, description, "order", created_at, updated_at
`

type CreateBoardParams struct {
	ProjectID   uuid.NullUUID  `json:"project_id"`
	TemplateID  uuid.NullUUID  `json:"template_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Order       int16          `json:"order"`
}

// Boards
func (q *Queries) CreateBoard(ctx context.Context, arg CreateBoardParams) (Board, error) {
	row := q.db.QueryRowContext(ctx, createBoard,
		arg.ProjectID,
		arg.TemplateID,
		arg.Name,
		arg.Description,
		arg.Order,
	)
	var i Board
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.TemplateID,
		&i.Name,
		&i.Description,
		&i.Order,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createColumn = `-- name: CreateColumn :one
INSERT INTO columns (board_id, name, system_type, wip_limit, "order")
VALUES ($1, $2, $3, $4, $5)
RETURNING id, board_id, name, system_type, wip_limit, "order", created_at, updated_at, is_sprint_backlog
`

type CreateColumnParams struct {
	BoardID    uuid.UUID      `json:"board_id"`
	Name       string         `json:"name"`
	SystemType sql.NullString `json:"system_type"`
	WipLimit   sql.NullInt16  `json:"wip_limit"`
	Order      int16          `json:"order"`
}

func (q *Queries) CreateColumn(ctx context.Context, arg CreateColumnParams) (Column, error) {
	row := q.db.QueryRowContext(ctx, createColumn,
		arg.BoardID,
		arg.Name,
		arg.SystemType,
		arg.WipLimit,
		arg.Order,
	)
	var i Column
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.Name,
		&i.SystemType,
		&i.WipLimit,
		&i.Order,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsSprintBacklog,
	)
	return i, err
}

const createNoteForColumn = `-- name: CreateNoteForColumn :one
INSERT INTO notes (column_id, content)
VALUES ($1, $2)
RETURNING id, column_id, swimlane_id, content, created_at, updated_at
`

type CreateNoteForColumnParams struct {
	ColumnID uuid.NullUUID `json:"column_id"`
	Content  string        `json:"content"`
}

func (q *Queries) CreateNoteForColumn(ctx context.Context, arg CreateNoteForColumnParams) (Note, error) {
	row := q.db.QueryRowContext(ctx, createNoteForColumn, arg.ColumnID, arg.Content)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.ColumnID,
		&i.SwimlaneID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createNoteForSwimlane = `-- name: CreateNoteForSwimlane :one
INSERT INTO notes (swimlane_id, content)
VALUES ($1, $2)
RETURNING id, column_id, swimlane_id, content, created_at, updated_at
`

type CreateNoteForSwimlaneParams struct {
	SwimlaneID uuid.NullUUID `json:"swimlane_id"`
	Content    string        `json:"content"`
}

func (q *Queries) CreateNoteForSwimlane(ctx context.Context, arg CreateNoteForSwimlaneParams) (Note, error) {
	row := q.db.QueryRowContext(ctx, createNoteForSwimlane, arg.SwimlaneID, arg.Content)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.ColumnID,
		&i.SwimlaneID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSwimlane = `-- name: CreateSwimlane :one
INSERT INTO swimlanes (board_id, name, wip_limit, "order")
VALUES ($1, $2, $3, $4)
RETURNING id, board_id, name, wip_limit, "order", created_at, updated_at, source_type, custom_field_id, value_mappings
`

type CreateSwimlaneParams struct {
	BoardID  uuid.UUID     `json:"board_id"`
	Name     string        `json:"name"`
	WipLimit sql.NullInt16 `json:"wip_limit"`
	Order    int16         `json:"order"`
}

func (q *Queries) CreateSwimlane(ctx context.Context, arg CreateSwimlaneParams) (Swimlane, error) {
	row := q.db.QueryRowContext(ctx, createSwimlane,
		arg.BoardID,
		arg.Name,
		arg.WipLimit,
		arg.Order,
	)
	var i Swimlane
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.Name,
		&i.WipLimit,
		&i.Order,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SourceType,
		&i.CustomFieldID,
		&i.ValueMappings,
	)
	return i, err
}

const deleteBoard = `-- name: DeleteBoard :exec
DELETE FROM boards
WHERE id = $1
`

func (q *Queries) DeleteBoard(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteBoard, id)
	return err
}

const deleteColumn = `-- name: DeleteColumn :exec
DELETE FROM columns
WHERE id = $1
`

func (q *Queries) DeleteColumn(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteColumn, id)
	return err
}

const deleteNote = `-- name: DeleteNote :exec
DELETE FROM notes
WHERE id = $1
`

func (q *Queries) DeleteNote(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteNote, id)
	return err
}

const deleteSwimlane = `-- name: DeleteSwimlane :exec
DELETE FROM swimlanes
WHERE id = $1
`

func (q *Queries) DeleteSwimlane(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteSwimlane, id)
	return err
}

const getBoardByID = `-- name: GetBoardByID :one
SELECT id, project_id, template_id, name, description, "order", created_at, updated_at
FROM boards
WHERE id = $1
`

func (q *Queries) GetBoardByID(ctx context.Context, id uuid.UUID) (Board, error) {
	row := q.db.QueryRowContext(ctx, getBoardByID, id)
	var i Board
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.TemplateID,
		&i.Name,
		&i.Description,
		&i.Order,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBoardColumns = `-- name: ListBoardColumns :many

SELECT id, board_id, name, system_type, wip_limit, "order", created_at, updated_at, is_sprint_backlog
FROM columns
WHERE board_id = $1
ORDER BY "order"
`

// Columns
func (q *Queries) ListBoardColumns(ctx context.Context, boardID uuid.UUID) ([]Column, error) {
	rows, err := q.db.QueryContext(ctx, listBoardColumns, boardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Column{}
	for rows.Next() {
		var i Column
		if err := rows.Scan(
			&i.ID,
			&i.BoardID,
			&i.Name,
			&i.SystemType,
			&i.WipLimit,
			&i.Order,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsSprintBacklog,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBoardNotes = `-- name: ListBoardNotes :many

SELECT n.id, n.column_id, n.swimlane_id, n.content, n.created_at, n.updated_at
FROM notes n
JOIN columns c ON n.column_id = c.id
WHERE c.board_id = $1
UNION ALL
SELECT n.id, n.column_id, n.swimlane_id, n.content, n.created_at, n.updated_at
FROM notes n
JOIN swimlanes s ON n.swimlane_id = s.id
WHERE s.board_id = $1
`

// Notes
func (q *Queries) ListBoardNotes(ctx context.Context, boardID uuid.UUID) ([]Note, error) {
	rows, err := q.db.QueryContext(ctx, listBoardNotes, boardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Note{}
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.ColumnID,
			&i.SwimlaneID,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBoardSwimlanes = `-- name: ListBoardSwimlanes :many

SELECT id, board_id, name, wip_limit, "order", created_at, updated_at, source_type, custom_field_id, value_mappings
FROM swimlanes
WHERE board_id = $1
ORDER BY "order"
`

// Swimlanes
func (q *Queries) ListBoardSwimlanes(ctx context.Context, boardID uuid.UUID) ([]Swimlane, error) {
	rows, err := q.db.QueryContext(ctx, listBoardSwimlanes, boardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Swimlane{}
	for rows.Next() {
		var i Swimlane
		if err := rows.Scan(
			&i.ID,
			&i.BoardID,
			&i.Name,
			&i.WipLimit,
			&i.Order,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SourceType,
			&i.CustomFieldID,
			&i.ValueMappings,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectBoards = `-- name: ListProjectBoards :many
SELECT id, project_id, template_id, name, description, "order", created_at, updated_at
FROM boards
WHERE project_id = $1
ORDER BY "order"
`

func (q *Queries) ListProjectBoards(ctx context.Context, projectID uuid.NullUUID) ([]Board, error) {
	rows, err := q.db.QueryContext(ctx, listProjectBoards, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Board{}
	for rows.Next() {
		var i Board
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.TemplateID,
			&i.Name,
			&i.Description,
			&i.Order,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBoard = `-- name: UpdateBoard :one
UPDATE boards
SET name        = COALESCE($1, name),
    description = COALESCE($2, description),
    "order"     = COALESCE($3, "order"),
    updated_at  = NOW()
WHERE id = $4
RETURNING id, project_id, template_id, name, description, "order", created_at, updated_at
`

type UpdateBoardParams struct {
	Name        sql.NullString `json:"name"`
	Description sql.NullString `json:"description"`
	Order       sql.NullInt16  `json:"order"`
	ID          uuid.UUID      `json:"id"`
}

func (q *Queries) UpdateBoard(ctx context.Context, arg UpdateBoardParams) (Board, error) {
	row := q.db.QueryRowContext(ctx, updateBoard,
		arg.Name,
		arg.Description,
		arg.Order,
		arg.ID,
	)
	var i Board
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.TemplateID,
		&i.Name,
		&i.Description,
		&i.Order,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateColumn = `-- name: UpdateColumn :one
UPDATE columns
SET name        = COALESCE($1, name),
    system_type = COALESCE($2, system_type),
    wip_limit   = COALESCE($3, wip_limit),
    "order"     = COALESCE($4, "order"),
    updated_at  = NOW()
WHERE id = $5
RETURNING id, board_id, name, system_type, wip_limit, "order", created_at, updated_at, is_sprint_backlog
`

type UpdateColumnParams struct {
	Name       sql.NullString `json:"name"`
	SystemType sql.NullString `json:"system_type"`
	WipLimit   sql.NullInt16  `json:"wip_limit"`
	Order      sql.NullInt16  `json:"order"`
	ID         uuid.UUID      `json:"id"`
}

func (q *Queries) UpdateColumn(ctx context.Context, arg UpdateColumnParams) (Column, error) {
	row := q.db.QueryRowContext(ctx, updateColumn,
		arg.Name,
		arg.SystemType,
		arg.WipLimit,
		arg.Order,
		arg.ID,
	)
	var i Column
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.Name,
		&i.SystemType,
		&i.WipLimit,
		&i.Order,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsSprintBacklog,
	)
	return i, err
}

const updateNote = `-- name: UpdateNote :one
UPDATE notes
SET content    = COALESCE($1, content),
    updated_at = NOW()
WHERE id = $2
RETURNING id, column_id, swimlane_id, content, created_at, updated_at
`

type UpdateNoteParams struct {
	Content sql.NullString `json:"content"`
	ID      uuid.UUID      `json:"id"`
}

func (q *Queries) UpdateNote(ctx context.Context, arg UpdateNoteParams) (Note, error) {
	row := q.db.QueryRowContext(ctx, updateNote, arg.Content, arg.ID)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.ColumnID,
		&i.SwimlaneID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSwimlane = `-- name: UpdateSwimlane :one
UPDATE swimlanes
SET name       = COALESCE($1, name),
    wip_limit  = COALESCE($2, wip_limit),
    "order"    = COALESCE($3, "order"),
    updated_at = NOW()
WHERE id = $4
RETURNING id, board_id, name, wip_limit, "order", created_at, updated_at, source_type, custom_field_id, value_mappings
`

type UpdateSwimlaneParams struct {
	Name     sql.NullString `json:"name"`
	WipLimit sql.NullInt16  `json:"wip_limit"`
	Order    sql.NullInt16  `json:"order"`
	ID       uuid.UUID      `json:"id"`
}

func (q *Queries) UpdateSwimlane(ctx context.Context, arg UpdateSwimlaneParams) (Swimlane, error) {
	row := q.db.QueryRowContext(ctx, updateSwimlane,
		arg.Name,
		arg.WipLimit,
		arg.Order,
		arg.ID,
	)
	var i Swimlane
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.Name,
		&i.WipLimit,
		&i.Order,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SourceType,
		&i.CustomFieldID,
		&i.ValueMappings,
	)
	return i, err
}
