// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: board_custom_fields.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const createBoardCustomField = `-- name: CreateBoardCustomField :one
INSERT INTO fields (kind, board_id, name, description, field_type, is_system, is_required, sort_order, options)
VALUES ('board_field', $1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, board_id, name, description, field_type, is_system, is_required, sort_order, options
`

type CreateBoardCustomFieldParams struct {
	BoardID     uuid.NullUUID         `json:"board_id"`
	Name        string                `json:"name"`
	Description string                `json:"description"`
	FieldType   string                `json:"field_type"`
	IsSystem    bool                  `json:"is_system"`
	IsRequired  bool                  `json:"is_required"`
	SortOrder   int32                 `json:"sort_order"`
	Options     pqtype.NullRawMessage `json:"options"`
}

type CreateBoardCustomFieldRow struct {
	ID          uuid.UUID             `json:"id"`
	BoardID     uuid.NullUUID         `json:"board_id"`
	Name        string                `json:"name"`
	Description string                `json:"description"`
	FieldType   string                `json:"field_type"`
	IsSystem    bool                  `json:"is_system"`
	IsRequired  bool                  `json:"is_required"`
	SortOrder   int32                 `json:"sort_order"`
	Options     pqtype.NullRawMessage `json:"options"`
}

func (q *Queries) CreateBoardCustomField(ctx context.Context, arg CreateBoardCustomFieldParams) (CreateBoardCustomFieldRow, error) {
	row := q.db.QueryRowContext(ctx, createBoardCustomField,
		arg.BoardID,
		arg.Name,
		arg.Description,
		arg.FieldType,
		arg.IsSystem,
		arg.IsRequired,
		arg.SortOrder,
		arg.Options,
	)
	var i CreateBoardCustomFieldRow
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.Name,
		&i.Description,
		&i.FieldType,
		&i.IsSystem,
		&i.IsRequired,
		&i.SortOrder,
		&i.Options,
	)
	return i, err
}

const deleteBoardCustomFieldByID = `-- name: DeleteBoardCustomFieldByID :exec
DELETE FROM fields WHERE id = $1 AND kind = 'board_field'
`

func (q *Queries) DeleteBoardCustomFieldByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteBoardCustomFieldByID, id)
	return err
}

const getBoardCustomFieldByID = `-- name: GetBoardCustomFieldByID :one
SELECT id, board_id, name, description, field_type, is_system, is_required, sort_order, options
FROM fields
WHERE id = $1 AND kind = 'board_field'
`

type GetBoardCustomFieldByIDRow struct {
	ID          uuid.UUID             `json:"id"`
	BoardID     uuid.NullUUID         `json:"board_id"`
	Name        string                `json:"name"`
	Description string                `json:"description"`
	FieldType   string                `json:"field_type"`
	IsSystem    bool                  `json:"is_system"`
	IsRequired  bool                  `json:"is_required"`
	SortOrder   int32                 `json:"sort_order"`
	Options     pqtype.NullRawMessage `json:"options"`
}

func (q *Queries) GetBoardCustomFieldByID(ctx context.Context, id uuid.UUID) (GetBoardCustomFieldByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getBoardCustomFieldByID, id)
	var i GetBoardCustomFieldByIDRow
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.Name,
		&i.Description,
		&i.FieldType,
		&i.IsSystem,
		&i.IsRequired,
		&i.SortOrder,
		&i.Options,
	)
	return i, err
}

const listBoardCustomFields = `-- name: ListBoardCustomFields :many

SELECT id, board_id, name, description, field_type, is_system, is_required, sort_order, options
FROM fields
WHERE board_id = $1 AND kind = 'board_field'
ORDER BY sort_order ASC
`

type ListBoardCustomFieldsRow struct {
	ID          uuid.UUID             `json:"id"`
	BoardID     uuid.NullUUID         `json:"board_id"`
	Name        string                `json:"name"`
	Description string                `json:"description"`
	FieldType   string                `json:"field_type"`
	IsSystem    bool                  `json:"is_system"`
	IsRequired  bool                  `json:"is_required"`
	SortOrder   int32                 `json:"sort_order"`
	Options     pqtype.NullRawMessage `json:"options"`
}

// Board custom fields (stored in unified `fields` table, kind='board_field')
func (q *Queries) ListBoardCustomFields(ctx context.Context, boardID uuid.NullUUID) ([]ListBoardCustomFieldsRow, error) {
	rows, err := q.db.QueryContext(ctx, listBoardCustomFields, boardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBoardCustomFieldsRow{}
	for rows.Next() {
		var i ListBoardCustomFieldsRow
		if err := rows.Scan(
			&i.ID,
			&i.BoardID,
			&i.Name,
			&i.Description,
			&i.FieldType,
			&i.IsSystem,
			&i.IsRequired,
			&i.SortOrder,
			&i.Options,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBoardCustomField = `-- name: UpdateBoardCustomField :one
UPDATE fields
SET name = $2, is_required = $3, options = $4
WHERE id = $1 AND kind = 'board_field'
RETURNING id, board_id, name, description, field_type, is_system, is_required, sort_order, options
`

type UpdateBoardCustomFieldParams struct {
	ID         uuid.UUID             `json:"id"`
	Name       string                `json:"name"`
	IsRequired bool                  `json:"is_required"`
	Options    pqtype.NullRawMessage `json:"options"`
}

type UpdateBoardCustomFieldRow struct {
	ID          uuid.UUID             `json:"id"`
	BoardID     uuid.NullUUID         `json:"board_id"`
	Name        string                `json:"name"`
	Description string                `json:"description"`
	FieldType   string                `json:"field_type"`
	IsSystem    bool                  `json:"is_system"`
	IsRequired  bool                  `json:"is_required"`
	SortOrder   int32                 `json:"sort_order"`
	Options     pqtype.NullRawMessage `json:"options"`
}

func (q *Queries) UpdateBoardCustomField(ctx context.Context, arg UpdateBoardCustomFieldParams) (UpdateBoardCustomFieldRow, error) {
	row := q.db.QueryRowContext(ctx, updateBoardCustomField,
		arg.ID,
		arg.Name,
		arg.IsRequired,
		arg.Options,
	)
	var i UpdateBoardCustomFieldRow
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.Name,
		&i.Description,
		&i.FieldType,
		&i.IsSystem,
		&i.IsRequired,
		&i.SortOrder,
		&i.Options,
	)
	return i, err
}

const updateBoardCustomFieldOrder = `-- name: UpdateBoardCustomFieldOrder :exec
UPDATE fields SET sort_order = $2 WHERE id = $1 AND kind = 'board_field'
`

type UpdateBoardCustomFieldOrderParams struct {
	ID        uuid.UUID `json:"id"`
	SortOrder int32     `json:"sort_order"`
}

func (q *Queries) UpdateBoardCustomFieldOrder(ctx context.Context, arg UpdateBoardCustomFieldOrderParams) error {
	_, err := q.db.ExecContext(ctx, updateBoardCustomFieldOrder, arg.ID, arg.SortOrder)
	return err
}
