// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: board_custom_fields.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const createBoardCustomField = `-- name: CreateBoardCustomField :one
INSERT INTO board_fields (board_id, name, field_type, is_required, options)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, board_id, name, field_type, is_required, options
`

type CreateBoardCustomFieldParams struct {
	BoardID    uuid.UUID             `json:"board_id"`
	Name       string                `json:"name"`
	FieldType  string                `json:"field_type"`
	IsRequired bool                  `json:"is_required"`
	Options    pqtype.NullRawMessage `json:"options"`
}

func (q *Queries) CreateBoardCustomField(ctx context.Context, arg CreateBoardCustomFieldParams) (BoardField, error) {
	row := q.db.QueryRowContext(ctx, createBoardCustomField,
		arg.BoardID,
		arg.Name,
		arg.FieldType,
		arg.IsRequired,
		arg.Options,
	)
	var i BoardField
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.Name,
		&i.FieldType,
		&i.IsRequired,
		&i.Options,
	)
	return i, err
}

const deleteBoardCustomFieldByID = `-- name: DeleteBoardCustomFieldByID :exec
DELETE FROM board_fields WHERE id = $1
`

func (q *Queries) DeleteBoardCustomFieldByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteBoardCustomFieldByID, id)
	return err
}

const getBoardCustomFieldByID = `-- name: GetBoardCustomFieldByID :one
SELECT id, board_id, name, field_type, is_required, options
FROM board_fields
WHERE id = $1
`

func (q *Queries) GetBoardCustomFieldByID(ctx context.Context, id uuid.UUID) (BoardField, error) {
	row := q.db.QueryRowContext(ctx, getBoardCustomFieldByID, id)
	var i BoardField
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.Name,
		&i.FieldType,
		&i.IsRequired,
		&i.Options,
	)
	return i, err
}

const listBoardCustomFields = `-- name: ListBoardCustomFields :many

SELECT id, board_id, name, field_type, is_required, options
FROM board_fields
WHERE board_id = $1
`

// Board custom fields (system fields generated from Go constants)
func (q *Queries) ListBoardCustomFields(ctx context.Context, boardID uuid.UUID) ([]BoardField, error) {
	rows, err := q.db.QueryContext(ctx, listBoardCustomFields, boardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BoardField{}
	for rows.Next() {
		var i BoardField
		if err := rows.Scan(
			&i.ID,
			&i.BoardID,
			&i.Name,
			&i.FieldType,
			&i.IsRequired,
			&i.Options,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBoardCustomField = `-- name: UpdateBoardCustomField :one
UPDATE board_fields
SET name = $2, is_required = $3, options = $4
WHERE id = $1
RETURNING id, board_id, name, field_type, is_required, options
`

type UpdateBoardCustomFieldParams struct {
	ID         uuid.UUID             `json:"id"`
	Name       string                `json:"name"`
	IsRequired bool                  `json:"is_required"`
	Options    pqtype.NullRawMessage `json:"options"`
}

func (q *Queries) UpdateBoardCustomField(ctx context.Context, arg UpdateBoardCustomFieldParams) (BoardField, error) {
	row := q.db.QueryRowContext(ctx, updateBoardCustomField,
		arg.ID,
		arg.Name,
		arg.IsRequired,
		arg.Options,
	)
	var i BoardField
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.Name,
		&i.FieldType,
		&i.IsRequired,
		&i.Options,
	)
	return i, err
}
