// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: checklists.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createChecklist = `-- name: CreateChecklist :one
INSERT INTO checklists (task_id, name)
VALUES ($1, $2)
RETURNING id, task_id, name, created_at
`

type CreateChecklistParams struct {
	TaskID uuid.UUID `json:"task_id"`
	Name   string    `json:"name"`
}

func (q *Queries) CreateChecklist(ctx context.Context, arg CreateChecklistParams) (Checklist, error) {
	row := q.db.QueryRowContext(ctx, createChecklist, arg.TaskID, arg.Name)
	var i Checklist
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const createChecklistItem = `-- name: CreateChecklistItem :one
INSERT INTO checklist_items (checklist_id, content, is_checked, sort_order)
VALUES ($1, $2, $3, $4)
RETURNING id, checklist_id, content, is_checked, sort_order
`

type CreateChecklistItemParams struct {
	ChecklistID uuid.UUID `json:"checklist_id"`
	Content     string    `json:"content"`
	IsChecked   bool      `json:"is_checked"`
	SortOrder   int16     `json:"sort_order"`
}

func (q *Queries) CreateChecklistItem(ctx context.Context, arg CreateChecklistItemParams) (ChecklistItem, error) {
	row := q.db.QueryRowContext(ctx, createChecklistItem,
		arg.ChecklistID,
		arg.Content,
		arg.IsChecked,
		arg.SortOrder,
	)
	var i ChecklistItem
	err := row.Scan(
		&i.ID,
		&i.ChecklistID,
		&i.Content,
		&i.IsChecked,
		&i.SortOrder,
	)
	return i, err
}

const deleteChecklist = `-- name: DeleteChecklist :exec
DELETE FROM checklists WHERE id = $1
`

func (q *Queries) DeleteChecklist(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteChecklist, id)
	return err
}

const deleteChecklistItem = `-- name: DeleteChecklistItem :exec
DELETE FROM checklist_items WHERE id = $1
`

func (q *Queries) DeleteChecklistItem(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteChecklistItem, id)
	return err
}

const listChecklistItems = `-- name: ListChecklistItems :many
SELECT id, checklist_id, content, is_checked, sort_order
FROM checklist_items
WHERE checklist_id = $1
ORDER BY sort_order
`

func (q *Queries) ListChecklistItems(ctx context.Context, checklistID uuid.UUID) ([]ChecklistItem, error) {
	rows, err := q.db.QueryContext(ctx, listChecklistItems, checklistID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChecklistItem{}
	for rows.Next() {
		var i ChecklistItem
		if err := rows.Scan(
			&i.ID,
			&i.ChecklistID,
			&i.Content,
			&i.IsChecked,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChecklistsByTask = `-- name: ListChecklistsByTask :many
SELECT id, task_id, name, created_at
FROM checklists
WHERE task_id = $1
ORDER BY created_at
`

func (q *Queries) ListChecklistsByTask(ctx context.Context, taskID uuid.UUID) ([]Checklist, error) {
	rows, err := q.db.QueryContext(ctx, listChecklistsByTask, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Checklist{}
	for rows.Next() {
		var i Checklist
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateChecklistItemContent = `-- name: UpdateChecklistItemContent :one
UPDATE checklist_items SET content = $2 WHERE id = $1
RETURNING id, checklist_id, content, is_checked, sort_order
`

type UpdateChecklistItemContentParams struct {
	ID      uuid.UUID `json:"id"`
	Content string    `json:"content"`
}

func (q *Queries) UpdateChecklistItemContent(ctx context.Context, arg UpdateChecklistItemContentParams) (ChecklistItem, error) {
	row := q.db.QueryRowContext(ctx, updateChecklistItemContent, arg.ID, arg.Content)
	var i ChecklistItem
	err := row.Scan(
		&i.ID,
		&i.ChecklistID,
		&i.Content,
		&i.IsChecked,
		&i.SortOrder,
	)
	return i, err
}

const updateChecklistItemStatus = `-- name: UpdateChecklistItemStatus :one
UPDATE checklist_items
SET is_checked = $2
WHERE id = $1
RETURNING id, checklist_id, content, is_checked, sort_order
`

type UpdateChecklistItemStatusParams struct {
	ID        uuid.UUID `json:"id"`
	IsChecked bool      `json:"is_checked"`
}

func (q *Queries) UpdateChecklistItemStatus(ctx context.Context, arg UpdateChecklistItemStatusParams) (ChecklistItem, error) {
	row := q.db.QueryRowContext(ctx, updateChecklistItemStatus, arg.ID, arg.IsChecked)
	var i ChecklistItem
	err := row.Scan(
		&i.ID,
		&i.ChecklistID,
		&i.Content,
		&i.IsChecked,
		&i.SortOrder,
	)
	return i, err
}

const updateChecklistName = `-- name: UpdateChecklistName :one
UPDATE checklists SET name = $2 WHERE id = $1
RETURNING id, task_id, name, created_at
`

type UpdateChecklistNameParams struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

func (q *Queries) UpdateChecklistName(ctx context.Context, arg UpdateChecklistNameParams) (Checklist, error) {
	row := q.db.QueryRowContext(ctx, updateChecklistName, arg.ID, arg.Name)
	var i Checklist
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}
