// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: classes_of_service.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const getDefaultClassesOfService = `-- name: GetDefaultClassesOfService :many
SELECT  FROM (
    VALUES
        ('expedite'::text),
        ('fixed_date'::text),
        ('standard'::text),
        ('intangible'::text)
) AS t(class_of_service)
`

type GetDefaultClassesOfServiceRow struct {
}

func (q *Queries) GetDefaultClassesOfService(ctx context.Context) ([]GetDefaultClassesOfServiceRow, error) {
	rows, err := q.db.QueryContext(ctx, getDefaultClassesOfService)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDefaultClassesOfServiceRow{}
	for rows.Next() {
		var i GetDefaultClassesOfServiceRow
		if err := rows.Scan(); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTasksByClassOfService = `-- name: GetTasksByClassOfService :many
SELECT id, key, project_id, owner_id, executor_id, name, description, deadline, column_id, swimlane_id, delete_reason, deleted_at, created_at, updated_at, story_points, backlog_type, class_of_service, cycle_time_seconds
FROM tasks
WHERE project_id = $1
  AND class_of_service = $2
  AND deleted_at IS NULL
ORDER BY created_at DESC
`

type GetTasksByClassOfServiceParams struct {
	ProjectID      uuid.UUID      `json:"project_id"`
	ClassOfService sql.NullString `json:"class_of_service"`
}

func (q *Queries) GetTasksByClassOfService(ctx context.Context, arg GetTasksByClassOfServiceParams) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, getTasksByClassOfService, arg.ProjectID, arg.ClassOfService)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.ProjectID,
			&i.OwnerID,
			&i.ExecutorID,
			&i.Name,
			&i.Description,
			&i.Deadline,
			&i.ColumnID,
			&i.SwimlaneID,
			&i.DeleteReason,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StoryPoints,
			&i.BacklogType,
			&i.ClassOfService,
			&i.CycleTimeSeconds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTaskClassOfService = `-- name: UpdateTaskClassOfService :exec

UPDATE tasks
SET class_of_service = $2
WHERE id = $1
`

type UpdateTaskClassOfServiceParams struct {
	ID             uuid.UUID      `json:"id"`
	ClassOfService sql.NullString `json:"class_of_service"`
}

// Classes of service helpers
func (q *Queries) UpdateTaskClassOfService(ctx context.Context, arg UpdateTaskClassOfServiceParams) error {
	_, err := q.db.ExecContext(ctx, updateTaskClassOfService, arg.ID, arg.ClassOfService)
	return err
}
