// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: comments.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createComment = `-- name: CreateComment :one

INSERT INTO comments (task_id, author_id, content)
VALUES ($1, $2, $3)
RETURNING id, task_id, author_id, content, created_at, updated_at
`

type CreateCommentParams struct {
	TaskID   uuid.UUID `json:"task_id"`
	AuthorID uuid.UUID `json:"author_id"`
	Content  string    `json:"content"`
}

// Task comments and mentions
func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error) {
	row := q.db.QueryRowContext(ctx, createComment, arg.TaskID, arg.AuthorID, arg.Content)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.AuthorID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createCommentMention = `-- name: CreateCommentMention :exec
INSERT INTO comment_mentions (comment_id, project_member_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type CreateCommentMentionParams struct {
	CommentID       uuid.UUID `json:"comment_id"`
	ProjectMemberID uuid.UUID `json:"project_member_id"`
}

func (q *Queries) CreateCommentMention(ctx context.Context, arg CreateCommentMentionParams) error {
	_, err := q.db.ExecContext(ctx, createCommentMention, arg.CommentID, arg.ProjectMemberID)
	return err
}

const listCommentMentions = `-- name: ListCommentMentions :many
SELECT id, comment_id, project_member_id
FROM comment_mentions
WHERE comment_id = $1
`

func (q *Queries) ListCommentMentions(ctx context.Context, commentID uuid.UUID) ([]CommentMention, error) {
	rows, err := q.db.QueryContext(ctx, listCommentMentions, commentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CommentMention{}
	for rows.Next() {
		var i CommentMention
		if err := rows.Scan(&i.ID, &i.CommentID, &i.ProjectMemberID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskComments = `-- name: ListTaskComments :many
SELECT id, task_id, author_id, content, created_at, updated_at
FROM comments
WHERE task_id = $1
ORDER BY created_at
`

func (q *Queries) ListTaskComments(ctx context.Context, taskID uuid.UUID) ([]Comment, error) {
	rows, err := q.db.QueryContext(ctx, listTaskComments, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Comment{}
	for rows.Next() {
		var i Comment
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.AuthorID,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
