// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: kanban_analytics.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const getBoardColumnsForAnalytics = `-- name: GetBoardColumnsForAnalytics :many
SELECT id, name, system_type, wip_limit, sort_order
FROM columns
WHERE board_id = $1
ORDER BY sort_order
`

type GetBoardColumnsForAnalyticsRow struct {
	ID         uuid.UUID      `json:"id"`
	Name       string         `json:"name"`
	SystemType sql.NullString `json:"system_type"`
	WipLimit   sql.NullInt16  `json:"wip_limit"`
	SortOrder  int16          `json:"sort_order"`
}

func (q *Queries) GetBoardColumnsForAnalytics(ctx context.Context, boardID uuid.UUID) ([]GetBoardColumnsForAnalyticsRow, error) {
	rows, err := q.db.QueryContext(ctx, getBoardColumnsForAnalytics, boardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetBoardColumnsForAnalyticsRow{}
	for rows.Next() {
		var i GetBoardColumnsForAnalyticsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.SystemType,
			&i.WipLimit,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCompletedTasksForKanban = `-- name: GetCompletedTasksForKanban :many
SELECT
    t.id AS task_id,
    t.key AS task_key,
    t.estimation,
    MIN(CASE WHEN c.system_type IN ('in_progress', 'paused') THEN h.entered_at END)::timestamptz AS started_at,
    MAX(CASE WHEN c.system_type = 'completed' THEN h.entered_at END)::timestamptz AS completed_at
FROM task_status_history h
JOIN tasks t ON t.id = h.task_id
JOIN columns c ON h.column_id = c.id
WHERE t.project_id = $1
  AND t.board_id = $2
  AND t.deleted_at IS NULL
GROUP BY t.id, t.key, t.estimation
HAVING MAX(CASE WHEN c.system_type = 'completed' THEN h.entered_at END) IS NOT NULL
  AND MIN(CASE WHEN c.system_type IN ('in_progress', 'paused') THEN h.entered_at END) IS NOT NULL
`

type GetCompletedTasksForKanbanParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	BoardID   uuid.UUID `json:"board_id"`
}

type GetCompletedTasksForKanbanRow struct {
	TaskID      uuid.UUID      `json:"task_id"`
	TaskKey     string         `json:"task_key"`
	Estimation  sql.NullString `json:"estimation"`
	StartedAt   time.Time      `json:"started_at"`
	CompletedAt time.Time      `json:"completed_at"`
}

func (q *Queries) GetCompletedTasksForKanban(ctx context.Context, arg GetCompletedTasksForKanbanParams) ([]GetCompletedTasksForKanbanRow, error) {
	rows, err := q.db.QueryContext(ctx, getCompletedTasksForKanban, arg.ProjectID, arg.BoardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCompletedTasksForKanbanRow{}
	for rows.Next() {
		var i GetCompletedTasksForKanbanRow
		if err := rows.Scan(
			&i.TaskID,
			&i.TaskKey,
			&i.Estimation,
			&i.StartedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCurrentWipCount = `-- name: GetCurrentWipCount :one
SELECT COUNT(*)::int AS wip_count
FROM tasks t
JOIN columns c ON t.column_id = c.id
WHERE t.project_id = $1
  AND t.board_id = $2
  AND t.deleted_at IS NULL
  AND c.system_type IN ('in_progress', 'paused')
`

type GetCurrentWipCountParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	BoardID   uuid.UUID `json:"board_id"`
}

func (q *Queries) GetCurrentWipCount(ctx context.Context, arg GetCurrentWipCountParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, getCurrentWipCount, arg.ProjectID, arg.BoardID)
	var wip_count int32
	err := row.Scan(&wip_count)
	return wip_count, err
}

const getDefaultBoardForProject = `-- name: GetDefaultBoardForProject :one

SELECT id, name, estimation_unit
FROM boards
WHERE project_id = $1
ORDER BY is_default DESC, sort_order ASC
LIMIT 1
`

type GetDefaultBoardForProjectRow struct {
	ID             uuid.UUID `json:"id"`
	Name           string    `json:"name"`
	EstimationUnit string    `json:"estimation_unit"`
}

// Kanban analytics queries
func (q *Queries) GetDefaultBoardForProject(ctx context.Context, projectID uuid.NullUUID) (GetDefaultBoardForProjectRow, error) {
	row := q.db.QueryRowContext(ctx, getDefaultBoardForProject, projectID)
	var i GetDefaultBoardForProjectRow
	err := row.Scan(&i.ID, &i.Name, &i.EstimationUnit)
	return i, err
}

const getProjectTaskHistoryForKanban = `-- name: GetProjectTaskHistoryForKanban :many
SELECT
    h.task_id,
    h.column_id,
    c.name AS column_name,
    c.system_type AS column_system_type,
    h.entered_at,
    h.left_at
FROM task_status_history h
JOIN tasks t ON t.id = h.task_id
JOIN columns c ON h.column_id = c.id
WHERE t.project_id = $1
  AND t.board_id = $2
  AND t.deleted_at IS NULL
ORDER BY h.entered_at
`

type GetProjectTaskHistoryForKanbanParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	BoardID   uuid.UUID `json:"board_id"`
}

type GetProjectTaskHistoryForKanbanRow struct {
	TaskID           uuid.UUID      `json:"task_id"`
	ColumnID         uuid.UUID      `json:"column_id"`
	ColumnName       string         `json:"column_name"`
	ColumnSystemType sql.NullString `json:"column_system_type"`
	EnteredAt        time.Time      `json:"entered_at"`
	LeftAt           sql.NullTime   `json:"left_at"`
}

func (q *Queries) GetProjectTaskHistoryForKanban(ctx context.Context, arg GetProjectTaskHistoryForKanbanParams) ([]GetProjectTaskHistoryForKanbanRow, error) {
	rows, err := q.db.QueryContext(ctx, getProjectTaskHistoryForKanban, arg.ProjectID, arg.BoardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetProjectTaskHistoryForKanbanRow{}
	for rows.Next() {
		var i GetProjectTaskHistoryForKanbanRow
		if err := rows.Scan(
			&i.TaskID,
			&i.ColumnID,
			&i.ColumnName,
			&i.ColumnSystemType,
			&i.EnteredAt,
			&i.LeftAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWipTaskIDsForKanban = `-- name: GetWipTaskIDsForKanban :many
SELECT t.id
FROM tasks t
JOIN columns c ON t.column_id = c.id
WHERE t.project_id = $1
  AND t.board_id = $2
  AND t.deleted_at IS NULL
  AND c.system_type IN ('in_progress', 'paused')
`

type GetWipTaskIDsForKanbanParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	BoardID   uuid.UUID `json:"board_id"`
}

func (q *Queries) GetWipTaskIDsForKanban(ctx context.Context, arg GetWipTaskIDsForKanbanParams) ([]uuid.UUID, error) {
	rows, err := q.db.QueryContext(ctx, getWipTaskIDsForKanban, arg.ProjectID, arg.BoardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
