// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: kanban_wip.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const getCurrentWipCounts = `-- name: GetCurrentWipCounts :many
SELECT c.board_id,
       t.column_id,
       t.swimlane_id,
       COUNT(*)::int AS count
FROM tasks t
JOIN columns c ON t.column_id = c.id
WHERE c.board_id = $1
  AND t.deleted_at IS NULL
GROUP BY c.board_id, t.column_id, t.swimlane_id
`

type GetCurrentWipCountsRow struct {
	BoardID    uuid.UUID     `json:"board_id"`
	ColumnID   uuid.UUID     `json:"column_id"`
	SwimlaneID uuid.NullUUID `json:"swimlane_id"`
	Count      int32         `json:"count"`
}

func (q *Queries) GetCurrentWipCounts(ctx context.Context, boardID uuid.UUID) ([]GetCurrentWipCountsRow, error) {
	rows, err := q.db.QueryContext(ctx, getCurrentWipCounts, boardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCurrentWipCountsRow{}
	for rows.Next() {
		var i GetCurrentWipCountsRow
		if err := rows.Scan(
			&i.BoardID,
			&i.ColumnID,
			&i.SwimlaneID,
			&i.Count,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWipLimits = `-- name: GetWipLimits :many

SELECT b.id AS board_id,
       c.id AS column_id,
       NULL::uuid AS swimlane_id,
       COALESCE(c.wip_limit, 0)::int AS limit
FROM columns c
JOIN boards b ON c.board_id = b.id
WHERE b.project_id = $1
UNION ALL
SELECT b2.id AS board_id,
       NULL::uuid AS column_id,
       s.id AS swimlane_id,
       COALESCE(s.wip_limit, 0)::int AS limit
FROM swimlanes s
JOIN boards b2 ON s.board_id = b2.id
WHERE b2.project_id = $1
ORDER BY board_id, column_id, swimlane_id
`

type GetWipLimitsRow struct {
	BoardID    uuid.UUID     `json:"board_id"`
	ColumnID   uuid.UUID     `json:"column_id"`
	SwimlaneID uuid.NullUUID `json:"swimlane_id"`
	Limit      int32         `json:"limit"`
}

// Kanban WIP limits and counts
func (q *Queries) GetWipLimits(ctx context.Context, projectID uuid.NullUUID) ([]GetWipLimitsRow, error) {
	rows, err := q.db.QueryContext(ctx, getWipLimits, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetWipLimitsRow{}
	for rows.Next() {
		var i GetWipLimitsRow
		if err := rows.Scan(
			&i.BoardID,
			&i.ColumnID,
			&i.SwimlaneID,
			&i.Limit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateColumnWipLimit = `-- name: UpdateColumnWipLimit :exec
UPDATE columns
SET wip_limit  = $2,
    updated_at = NOW()
WHERE id = $1
`

type UpdateColumnWipLimitParams struct {
	ID       uuid.UUID     `json:"id"`
	WipLimit sql.NullInt16 `json:"wip_limit"`
}

func (q *Queries) UpdateColumnWipLimit(ctx context.Context, arg UpdateColumnWipLimitParams) error {
	_, err := q.db.ExecContext(ctx, updateColumnWipLimit, arg.ID, arg.WipLimit)
	return err
}

const updateSwimlaneWipLimit = `-- name: UpdateSwimlaneWipLimit :exec
UPDATE swimlanes
SET wip_limit  = $2,
    updated_at = NOW()
WHERE id = $1
`

type UpdateSwimlaneWipLimitParams struct {
	ID       uuid.UUID     `json:"id"`
	WipLimit sql.NullInt16 `json:"wip_limit"`
}

func (q *Queries) UpdateSwimlaneWipLimit(ctx context.Context, arg UpdateSwimlaneWipLimitParams) error {
	_, err := q.db.ExecContext(ctx, updateSwimlaneWipLimit, arg.ID, arg.WipLimit)
	return err
}
