// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: kanban_forecast.sql

package db

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const cleanExpiredForecastCache = `-- name: CleanExpiredForecastCache :exec
DELETE FROM kanban_forecast_cache
WHERE expires_at <= NOW()
`

func (q *Queries) CleanExpiredForecastCache(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, cleanExpiredForecastCache)
	return err
}

const getForecastCache = `-- name: GetForecastCache :one
SELECT id, project_id, work_item_count, forecast_data, created_at, expires_at
FROM kanban_forecast_cache
WHERE project_id = $1
  AND work_item_count = $2
  AND expires_at > NOW()
ORDER BY created_at DESC
LIMIT 1
`

type GetForecastCacheParams struct {
	ProjectID     uuid.UUID `json:"project_id"`
	WorkItemCount int32     `json:"work_item_count"`
}

func (q *Queries) GetForecastCache(ctx context.Context, arg GetForecastCacheParams) (KanbanForecastCache, error) {
	row := q.db.QueryRowContext(ctx, getForecastCache, arg.ProjectID, arg.WorkItemCount)
	var i KanbanForecastCache
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.WorkItemCount,
		&i.ForecastData,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const saveForecastCache = `-- name: SaveForecastCache :one

INSERT INTO kanban_forecast_cache (project_id, work_item_count, forecast_data, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, project_id, work_item_count, forecast_data, created_at, expires_at
`

type SaveForecastCacheParams struct {
	ProjectID     uuid.UUID       `json:"project_id"`
	WorkItemCount int32           `json:"work_item_count"`
	ForecastData  json.RawMessage `json:"forecast_data"`
	ExpiresAt     time.Time       `json:"expires_at"`
}

// Kanban Monte Carlo forecast cache
func (q *Queries) SaveForecastCache(ctx context.Context, arg SaveForecastCacheParams) (KanbanForecastCache, error) {
	row := q.db.QueryRowContext(ctx, saveForecastCache,
		arg.ProjectID,
		arg.WorkItemCount,
		arg.ForecastData,
		arg.ExpiresAt,
	)
	var i KanbanForecastCache
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.WorkItemCount,
		&i.ForecastData,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}
