// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: meetings.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const addMeetingParticipant = `-- name: AddMeetingParticipant :one

INSERT INTO meeting_participants (meeting_id, user_id, status)
VALUES ($1, $2, $3)
ON CONFLICT (meeting_id, user_id) DO UPDATE
SET status = EXCLUDED.status
RETURNING id, meeting_id, user_id, status
`

type AddMeetingParticipantParams struct {
	MeetingID uuid.UUID `json:"meeting_id"`
	UserID    uuid.UUID `json:"user_id"`
	Status    string    `json:"status"`
}

// Participants
func (q *Queries) AddMeetingParticipant(ctx context.Context, arg AddMeetingParticipantParams) (MeetingParticipant, error) {
	row := q.db.QueryRowContext(ctx, addMeetingParticipant, arg.MeetingID, arg.UserID, arg.Status)
	var i MeetingParticipant
	err := row.Scan(
		&i.ID,
		&i.MeetingID,
		&i.UserID,
		&i.Status,
	)
	return i, err
}

const cancelMeeting = `-- name: CancelMeeting :one
UPDATE meetings
SET status = 'cancelled'
WHERE id = $1
RETURNING id, project_id, name, description, meeting_type, start_time, end_time, created_by, location, status
`

func (q *Queries) CancelMeeting(ctx context.Context, id uuid.UUID) (Meeting, error) {
	row := q.db.QueryRowContext(ctx, cancelMeeting, id)
	var i Meeting
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Description,
		&i.MeetingType,
		&i.StartTime,
		&i.EndTime,
		&i.CreatedBy,
		&i.Location,
		&i.Status,
	)
	return i, err
}

const createMeeting = `-- name: CreateMeeting :one

INSERT INTO meetings (project_id, name, description, meeting_type, location, start_time, end_time, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, project_id, name, description, meeting_type, start_time, end_time, created_by, location, status
`

type CreateMeetingParams struct {
	ProjectID   uuid.NullUUID  `json:"project_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	MeetingType string         `json:"meeting_type"`
	Location    sql.NullString `json:"location"`
	StartTime   time.Time      `json:"start_time"`
	EndTime     time.Time      `json:"end_time"`
	CreatedBy   uuid.UUID      `json:"created_by"`
}

// Meetings
func (q *Queries) CreateMeeting(ctx context.Context, arg CreateMeetingParams) (Meeting, error) {
	row := q.db.QueryRowContext(ctx, createMeeting,
		arg.ProjectID,
		arg.Name,
		arg.Description,
		arg.MeetingType,
		arg.Location,
		arg.StartTime,
		arg.EndTime,
		arg.CreatedBy,
	)
	var i Meeting
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Description,
		&i.MeetingType,
		&i.StartTime,
		&i.EndTime,
		&i.CreatedBy,
		&i.Location,
		&i.Status,
	)
	return i, err
}

const deleteMeeting = `-- name: DeleteMeeting :exec
DELETE FROM meetings
WHERE id = $1
`

func (q *Queries) DeleteMeeting(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteMeeting, id)
	return err
}

const getMeetingByID = `-- name: GetMeetingByID :one
SELECT id, project_id, name, description, meeting_type, start_time, end_time, created_by, location, status
FROM meetings
WHERE id = $1
`

func (q *Queries) GetMeetingByID(ctx context.Context, id uuid.UUID) (Meeting, error) {
	row := q.db.QueryRowContext(ctx, getMeetingByID, id)
	var i Meeting
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Description,
		&i.MeetingType,
		&i.StartTime,
		&i.EndTime,
		&i.CreatedBy,
		&i.Location,
		&i.Status,
	)
	return i, err
}

const getMeetingParticipants = `-- name: GetMeetingParticipants :many
SELECT id, meeting_id, user_id, status
FROM meeting_participants
WHERE meeting_id = $1
`

func (q *Queries) GetMeetingParticipants(ctx context.Context, meetingID uuid.UUID) ([]MeetingParticipant, error) {
	rows, err := q.db.QueryContext(ctx, getMeetingParticipants, meetingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MeetingParticipant{}
	for rows.Next() {
		var i MeetingParticipant
		if err := rows.Scan(
			&i.ID,
			&i.MeetingID,
			&i.UserID,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectMeetings = `-- name: ListProjectMeetings :many
SELECT id, project_id, name, description, meeting_type, start_time, end_time, created_by, location, status
FROM meetings
WHERE project_id = $1
ORDER BY start_time
`

func (q *Queries) ListProjectMeetings(ctx context.Context, projectID uuid.NullUUID) ([]Meeting, error) {
	rows, err := q.db.QueryContext(ctx, listProjectMeetings, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Meeting{}
	for rows.Next() {
		var i Meeting
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Description,
			&i.MeetingType,
			&i.StartTime,
			&i.EndTime,
			&i.CreatedBy,
			&i.Location,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserMeetings = `-- name: ListUserMeetings :many
SELECT m.id, m.project_id, m.name, m.description, m.meeting_type, m.start_time, m.end_time, m.created_by, m.location, m.status
FROM meetings m
JOIN meeting_participants mp ON mp.meeting_id = m.id
WHERE mp.user_id = $1
  AND ($2::timestamptz IS NULL OR m.start_time >= $2)
  AND ($3::timestamptz IS NULL OR m.start_time <= $3)
ORDER BY m.start_time
`

type ListUserMeetingsParams struct {
	UserID   uuid.UUID    `json:"user_id"`
	FromTime sql.NullTime `json:"from_time"`
	ToTime   sql.NullTime `json:"to_time"`
}

func (q *Queries) ListUserMeetings(ctx context.Context, arg ListUserMeetingsParams) ([]Meeting, error) {
	rows, err := q.db.QueryContext(ctx, listUserMeetings, arg.UserID, arg.FromTime, arg.ToTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Meeting{}
	for rows.Next() {
		var i Meeting
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Description,
			&i.MeetingType,
			&i.StartTime,
			&i.EndTime,
			&i.CreatedBy,
			&i.Location,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMeeting = `-- name: UpdateMeeting :exec
UPDATE meetings
SET name = $2,
    description = $3,
    meeting_type = $4,
    location = $5,
    start_time = $6,
    end_time = $7,
    project_id = $8
WHERE id = $1
`

type UpdateMeetingParams struct {
	ID          uuid.UUID      `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	MeetingType string         `json:"meeting_type"`
	Location    sql.NullString `json:"location"`
	StartTime   time.Time      `json:"start_time"`
	EndTime     time.Time      `json:"end_time"`
	ProjectID   uuid.NullUUID  `json:"project_id"`
}

func (q *Queries) UpdateMeeting(ctx context.Context, arg UpdateMeetingParams) error {
	_, err := q.db.ExecContext(ctx, updateMeeting,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.MeetingType,
		arg.Location,
		arg.StartTime,
		arg.EndTime,
		arg.ProjectID,
	)
	return err
}

const updateParticipantStatus = `-- name: UpdateParticipantStatus :exec
UPDATE meeting_participants
SET status = $3
WHERE meeting_id = $1 AND user_id = $2
`

type UpdateParticipantStatusParams struct {
	MeetingID uuid.UUID `json:"meeting_id"`
	UserID    uuid.UUID `json:"user_id"`
	Status    string    `json:"status"`
}

func (q *Queries) UpdateParticipantStatus(ctx context.Context, arg UpdateParticipantStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateParticipantStatus, arg.MeetingID, arg.UserID, arg.Status)
	return err
}
