// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: meetings.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const addMeetingParticipant = `-- name: AddMeetingParticipant :one

INSERT INTO meeting_participants (meeting_id, user_id, status)
VALUES ($1, $2, $3)
ON CONFLICT (meeting_id, user_id) DO UPDATE
SET status = EXCLUDED.status,
    updated_at = NOW()
RETURNING id, meeting_id, user_id, status, created_at, updated_at
`

type AddMeetingParticipantParams struct {
	MeetingID uuid.UUID `json:"meeting_id"`
	UserID    uuid.UUID `json:"user_id"`
	Status    string    `json:"status"`
}

// Participants
func (q *Queries) AddMeetingParticipant(ctx context.Context, arg AddMeetingParticipantParams) (MeetingParticipant, error) {
	row := q.db.QueryRowContext(ctx, addMeetingParticipant, arg.MeetingID, arg.UserID, arg.Status)
	var i MeetingParticipant
	err := row.Scan(
		&i.ID,
		&i.MeetingID,
		&i.UserID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const cancelMeeting = `-- name: CancelMeeting :exec
UPDATE meetings
SET canceled_at = NOW(),
    updated_at  = NOW()
WHERE id = $1
`

func (q *Queries) CancelMeeting(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, cancelMeeting, id)
	return err
}

const createMeeting = `-- name: CreateMeeting :one

INSERT INTO meetings (project_id, name, description, meeting_type, start_time, end_time, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, project_id, name, description, meeting_type, start_time, end_time, created_by, created_at, updated_at, canceled_at
`

type CreateMeetingParams struct {
	ProjectID   uuid.NullUUID  `json:"project_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	MeetingType string         `json:"meeting_type"`
	StartTime   time.Time      `json:"start_time"`
	EndTime     time.Time      `json:"end_time"`
	CreatedBy   uuid.UUID      `json:"created_by"`
}

// Meetings
func (q *Queries) CreateMeeting(ctx context.Context, arg CreateMeetingParams) (Meeting, error) {
	row := q.db.QueryRowContext(ctx, createMeeting,
		arg.ProjectID,
		arg.Name,
		arg.Description,
		arg.MeetingType,
		arg.StartTime,
		arg.EndTime,
		arg.CreatedBy,
	)
	var i Meeting
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Description,
		&i.MeetingType,
		&i.StartTime,
		&i.EndTime,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CanceledAt,
	)
	return i, err
}

const createMeetingReminder = `-- name: CreateMeetingReminder :exec

INSERT INTO meeting_reminders (meeting_id, user_id, channel, reminder_time, sent_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (meeting_id, user_id, channel, reminder_time) DO NOTHING
`

type CreateMeetingReminderParams struct {
	MeetingID    uuid.UUID    `json:"meeting_id"`
	UserID       uuid.UUID    `json:"user_id"`
	Channel      string       `json:"channel"`
	ReminderTime time.Time    `json:"reminder_time"`
	SentAt       sql.NullTime `json:"sent_at"`
}

// Reminders
func (q *Queries) CreateMeetingReminder(ctx context.Context, arg CreateMeetingReminderParams) error {
	_, err := q.db.ExecContext(ctx, createMeetingReminder,
		arg.MeetingID,
		arg.UserID,
		arg.Channel,
		arg.ReminderTime,
		arg.SentAt,
	)
	return err
}

const deleteMeeting = `-- name: DeleteMeeting :exec
DELETE FROM meetings
WHERE id = $1
`

func (q *Queries) DeleteMeeting(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteMeeting, id)
	return err
}

const getMeetingByID = `-- name: GetMeetingByID :one
SELECT id, project_id, name, description, meeting_type, start_time, end_time, created_by, created_at, updated_at, canceled_at
FROM meetings
WHERE id = $1
`

func (q *Queries) GetMeetingByID(ctx context.Context, id uuid.UUID) (Meeting, error) {
	row := q.db.QueryRowContext(ctx, getMeetingByID, id)
	var i Meeting
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Description,
		&i.MeetingType,
		&i.StartTime,
		&i.EndTime,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CanceledAt,
	)
	return i, err
}

const getMeetingParticipants = `-- name: GetMeetingParticipants :many
SELECT id, meeting_id, user_id, status, created_at, updated_at
FROM meeting_participants
WHERE meeting_id = $1
`

func (q *Queries) GetMeetingParticipants(ctx context.Context, meetingID uuid.UUID) ([]MeetingParticipant, error) {
	rows, err := q.db.QueryContext(ctx, getMeetingParticipants, meetingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MeetingParticipant{}
	for rows.Next() {
		var i MeetingParticipant
		if err := rows.Scan(
			&i.ID,
			&i.MeetingID,
			&i.UserID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUpcomingMeetingsForUser = `-- name: GetUpcomingMeetingsForUser :many
SELECT m.id, m.project_id, m.name, m.description, m.meeting_type, m.start_time, m.end_time, m.created_by, m.created_at, m.updated_at, m.canceled_at, mr.channel, mr.reminder_time, mr.sent_at
FROM meetings m
JOIN meeting_participants mp ON mp.meeting_id = m.id
LEFT JOIN meeting_reminders mr
  ON mr.meeting_id = m.id
 AND mr.user_id = mp.user_id
WHERE mp.user_id = $1
  AND m.start_time BETWEEN $2 AND $3
  AND (mr.sent_at IS NULL)
ORDER BY m.start_time
`

type GetUpcomingMeetingsForUserParams struct {
	UserID      uuid.UUID `json:"user_id"`
	StartTime   time.Time `json:"start_time"`
	StartTime_2 time.Time `json:"start_time_2"`
}

type GetUpcomingMeetingsForUserRow struct {
	ID           uuid.UUID      `json:"id"`
	ProjectID    uuid.NullUUID  `json:"project_id"`
	Name         string         `json:"name"`
	Description  sql.NullString `json:"description"`
	MeetingType  string         `json:"meeting_type"`
	StartTime    time.Time      `json:"start_time"`
	EndTime      time.Time      `json:"end_time"`
	CreatedBy    uuid.UUID      `json:"created_by"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
	CanceledAt   sql.NullTime   `json:"canceled_at"`
	Channel      sql.NullString `json:"channel"`
	ReminderTime sql.NullTime   `json:"reminder_time"`
	SentAt       sql.NullTime   `json:"sent_at"`
}

func (q *Queries) GetUpcomingMeetingsForUser(ctx context.Context, arg GetUpcomingMeetingsForUserParams) ([]GetUpcomingMeetingsForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, getUpcomingMeetingsForUser, arg.UserID, arg.StartTime, arg.StartTime_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUpcomingMeetingsForUserRow{}
	for rows.Next() {
		var i GetUpcomingMeetingsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Description,
			&i.MeetingType,
			&i.StartTime,
			&i.EndTime,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CanceledAt,
			&i.Channel,
			&i.ReminderTime,
			&i.SentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectMeetings = `-- name: ListProjectMeetings :many
SELECT id, project_id, name, description, meeting_type, start_time, end_time, created_by, created_at, updated_at, canceled_at
FROM meetings
WHERE project_id = $1
ORDER BY start_time
`

func (q *Queries) ListProjectMeetings(ctx context.Context, projectID uuid.NullUUID) ([]Meeting, error) {
	rows, err := q.db.QueryContext(ctx, listProjectMeetings, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Meeting{}
	for rows.Next() {
		var i Meeting
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Description,
			&i.MeetingType,
			&i.StartTime,
			&i.EndTime,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CanceledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserMeetings = `-- name: ListUserMeetings :many
SELECT m.id, m.project_id, m.name, m.description, m.meeting_type, m.start_time, m.end_time, m.created_by, m.created_at, m.updated_at, m.canceled_at
FROM meetings m
JOIN meeting_participants mp ON mp.meeting_id = m.id
WHERE mp.user_id = $1
  AND m.start_time >= $2
  AND m.end_time <= $3
ORDER BY m.start_time
`

type ListUserMeetingsParams struct {
	UserID    uuid.UUID `json:"user_id"`
	StartTime time.Time `json:"start_time"`
	EndTime   time.Time `json:"end_time"`
}

func (q *Queries) ListUserMeetings(ctx context.Context, arg ListUserMeetingsParams) ([]Meeting, error) {
	rows, err := q.db.QueryContext(ctx, listUserMeetings, arg.UserID, arg.StartTime, arg.EndTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Meeting{}
	for rows.Next() {
		var i Meeting
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Description,
			&i.MeetingType,
			&i.StartTime,
			&i.EndTime,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CanceledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMeeting = `-- name: UpdateMeeting :exec
UPDATE meetings
SET name = $2,
    description = $3,
    meeting_type = $4,
    start_time = $5,
    end_time = $6,
    updated_at = NOW()
WHERE id = $1
`

type UpdateMeetingParams struct {
	ID          uuid.UUID      `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	MeetingType string         `json:"meeting_type"`
	StartTime   time.Time      `json:"start_time"`
	EndTime     time.Time      `json:"end_time"`
}

func (q *Queries) UpdateMeeting(ctx context.Context, arg UpdateMeetingParams) error {
	_, err := q.db.ExecContext(ctx, updateMeeting,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.MeetingType,
		arg.StartTime,
		arg.EndTime,
	)
	return err
}

const updateParticipantStatus = `-- name: UpdateParticipantStatus :exec
UPDATE meeting_participants
SET status = $3,
    updated_at = NOW()
WHERE meeting_id = $1 AND user_id = $2
`

type UpdateParticipantStatusParams struct {
	MeetingID uuid.UUID `json:"meeting_id"`
	UserID    uuid.UUID `json:"user_id"`
	Status    string    `json:"status"`
}

func (q *Queries) UpdateParticipantStatus(ctx context.Context, arg UpdateParticipantStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateParticipantStatus, arg.MeetingID, arg.UserID, arg.Status)
	return err
}
