// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type Backlog struct {
	ProjectID uuid.UUID `json:"project_id"`
	TaskID    uuid.UUID `json:"task_id"`
	SortOrder int32     `json:"sort_order"`
}

type BlockedIp struct {
	IpAddress    pqtype.Inet `json:"ip_address"`
	BlockedUntil time.Time   `json:"blocked_until"`
}

type Board struct {
	ID              uuid.UUID      `json:"id"`
	ProjectID       uuid.NullUUID  `json:"project_id"`
	TemplateID      uuid.NullUUID  `json:"template_id"`
	Name            string         `json:"name"`
	Description     sql.NullString `json:"description"`
	SortOrder       int16          `json:"sort_order"`
	IsDefault       bool           `json:"is_default"`
	PriorityType    string         `json:"priority_type"`
	EstimationUnit  string         `json:"estimation_unit"`
	SwimlaneGroupBy string         `json:"swimlane_group_by"`
}

type Column struct {
	ID         uuid.UUID      `json:"id"`
	BoardID    uuid.UUID      `json:"board_id"`
	Name       string         `json:"name"`
	SystemType sql.NullString `json:"system_type"`
	WipLimit   sql.NullInt16  `json:"wip_limit"`
	SortOrder  int16          `json:"sort_order"`
	IsLocked   bool           `json:"is_locked"`
	Note       string         `json:"note"`
}

type Field struct {
	ID          uuid.UUID             `json:"id"`
	Kind        string                `json:"kind"`
	ProjectID   uuid.NullUUID         `json:"project_id"`
	TemplateID  uuid.NullUUID         `json:"template_id"`
	BoardID     uuid.NullUUID         `json:"board_id"`
	Name        string                `json:"name"`
	Description string                `json:"description"`
	FieldType   string                `json:"field_type"`
	IsSystem    bool                  `json:"is_system"`
	IsRequired  bool                  `json:"is_required"`
	SortOrder   int32                 `json:"sort_order"`
	Options     pqtype.NullRawMessage `json:"options"`
	Value       sql.NullString        `json:"value"`
}

type LoginAttempt struct {
	ID          int64          `json:"id"`
	Username    sql.NullString `json:"username"`
	IpAddress   pqtype.Inet    `json:"ip_address"`
	Success     bool           `json:"success"`
	AttemptedAt time.Time      `json:"attempted_at"`
}

type Meeting struct {
	ID          uuid.UUID      `json:"id"`
	ProjectID   uuid.NullUUID  `json:"project_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	MeetingType string         `json:"meeting_type"`
	StartTime   time.Time      `json:"start_time"`
	EndTime     time.Time      `json:"end_time"`
	CreatedBy   uuid.UUID      `json:"created_by"`
	Location    sql.NullString `json:"location"`
	Status      string         `json:"status"`
}

type MeetingParticipant struct {
	ID        uuid.UUID `json:"id"`
	MeetingID uuid.UUID `json:"meeting_id"`
	UserID    uuid.UUID `json:"user_id"`
	Status    string    `json:"status"`
}

type Member struct {
	ID        uuid.UUID `json:"id"`
	ProjectID uuid.UUID `json:"project_id"`
	UserID    uuid.UUID `json:"user_id"`
}

type MemberRole struct {
	MemberID uuid.UUID `json:"member_id"`
	RoleID   uuid.UUID `json:"role_id"`
}

type Note struct {
	ID         uuid.UUID     `json:"id"`
	ColumnID   uuid.NullUUID `json:"column_id"`
	SwimlaneID uuid.NullUUID `json:"swimlane_id"`
	Content    string        `json:"content"`
}

type Notification struct {
	ID        uuid.UUID             `json:"id"`
	UserID    uuid.UUID             `json:"user_id"`
	EventType string                `json:"event_type"`
	Title     string                `json:"title"`
	Body      sql.NullString        `json:"body"`
	Payload   pqtype.NullRawMessage `json:"payload"`
	IsRead    bool                  `json:"is_read"`
	CreatedAt time.Time             `json:"created_at"`
}

type NotificationSetting struct {
	ID                    uuid.UUID     `json:"id"`
	UserID                uuid.UUID     `json:"user_id"`
	EventType             string        `json:"event_type"`
	InSystem              bool          `json:"in_system"`
	InEmail               bool          `json:"in_email"`
	ReminderOffsetMinutes sql.NullInt32 `json:"reminder_offset_minutes"`
}

type PasswordHistory struct {
	ID           uuid.UUID `json:"id"`
	UserID       uuid.UUID `json:"user_id"`
	PasswordHash string    `json:"password_hash"`
	CreatedAt    time.Time `json:"created_at"`
}

type PasswordPolicy struct {
	ID               uuid.UUID      `json:"id"`
	MinLength        int32          `json:"min_length"`
	RequireDigits    bool           `json:"require_digits"`
	RequireLowercase bool           `json:"require_lowercase"`
	RequireUppercase bool           `json:"require_uppercase"`
	RequireSpecial   bool           `json:"require_special"`
	Notes            sql.NullString `json:"notes"`
	UpdatedAt        time.Time      `json:"updated_at"`
	UpdatedBy        uuid.NullUUID  `json:"updated_by"`
}

type Project struct {
	ID          uuid.UUID      `json:"id"`
	Key         string         `json:"key"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	ProjectType string         `json:"project_type"`
	OwnerID     uuid.UUID      `json:"owner_id"`
	Status      string         `json:"status"`
	CreatedAt   time.Time      `json:"created_at"`
}

type Role struct {
	ID          uuid.UUID     `json:"id"`
	Scope       string        `json:"scope"`
	ProjectID   uuid.NullUUID `json:"project_id"`
	TemplateID  uuid.NullUUID `json:"template_id"`
	Name        string        `json:"name"`
	Description string        `json:"description"`
	IsAdmin     bool          `json:"is_admin"`
}

type RolePermission struct {
	RoleID         uuid.UUID      `json:"role_id"`
	PermissionCode string         `json:"permission_code"`
	Access         sql.NullString `json:"access"`
}

type Sprint struct {
	ID        uuid.UUID      `json:"id"`
	ProjectID uuid.UUID      `json:"project_id"`
	Name      string         `json:"name"`
	Goal      sql.NullString `json:"goal"`
	StartDate time.Time      `json:"start_date"`
	EndDate   time.Time      `json:"end_date"`
	Status    string         `json:"status"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
}

type SprintTask struct {
	SprintID  uuid.UUID     `json:"sprint_id"`
	TaskID    uuid.UUID     `json:"task_id"`
	SortOrder sql.NullInt32 `json:"sort_order"`
}

type Swimlane struct {
	ID        uuid.UUID     `json:"id"`
	BoardID   uuid.UUID     `json:"board_id"`
	Name      string        `json:"name"`
	WipLimit  sql.NullInt16 `json:"wip_limit"`
	SortOrder int16         `json:"sort_order"`
	Note      string        `json:"note"`
}

type Tag struct {
	ID        uuid.UUID `json:"id"`
	BoardID   uuid.UUID `json:"board_id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
}

type Task struct {
	ID           uuid.UUID      `json:"id"`
	Key          string         `json:"key"`
	ProjectID    uuid.UUID      `json:"project_id"`
	OwnerID      uuid.UUID      `json:"owner_id"`
	ExecutorID   uuid.NullUUID  `json:"executor_id"`
	Name         string         `json:"name"`
	Description  sql.NullString `json:"description"`
	Deadline     sql.NullTime   `json:"deadline"`
	ColumnID     uuid.UUID      `json:"column_id"`
	SwimlaneID   uuid.NullUUID  `json:"swimlane_id"`
	StatusType   string         `json:"status_type"`
	DeletedAt    sql.NullTime   `json:"deleted_at"`
	DeleteReason sql.NullString `json:"delete_reason"`
	CreatedAt    time.Time      `json:"created_at"`
}

type TaskDependency struct {
	ID              uuid.UUID `json:"id"`
	TaskID          uuid.UUID `json:"task_id"`
	DependsOnTaskID uuid.UUID `json:"depends_on_task_id"`
	DependencyType  string    `json:"dependency_type"`
}

type TaskFieldValue struct {
	TaskID        uuid.UUID             `json:"task_id"`
	FieldID       uuid.UUID             `json:"field_id"`
	ValueText     sql.NullString        `json:"value_text"`
	ValueNumber   sql.NullString        `json:"value_number"`
	ValueDatetime sql.NullTime          `json:"value_datetime"`
	ValueJson     pqtype.NullRawMessage `json:"value_json"`
}

type TaskStatusHistory struct {
	ID        uuid.UUID    `json:"id"`
	TaskID    uuid.UUID    `json:"task_id"`
	ColumnID  uuid.UUID    `json:"column_id"`
	EnteredAt time.Time    `json:"entered_at"`
	LeftAt    sql.NullTime `json:"left_at"`
}

type TaskTag struct {
	TaskID uuid.UUID `json:"task_id"`
	TagID  uuid.UUID `json:"tag_id"`
}

type Template struct {
	ID          uuid.UUID      `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	ProjectType string         `json:"project_type"`
}

type Token struct {
	ID        uuid.UUID    `json:"id"`
	UserID    uuid.UUID    `json:"user_id"`
	TokenHash string       `json:"token_hash"`
	ExpiresAt time.Time    `json:"expires_at"`
	RevokedAt sql.NullTime `json:"revoked_at"`
}

type User struct {
	ID                uuid.UUID      `json:"id"`
	Username          string         `json:"username"`
	Email             string         `json:"email"`
	PasswordHash      string         `json:"password_hash"`
	FullName          string         `json:"full_name"`
	AvatarUrl         sql.NullString `json:"avatar_url"`
	Position          sql.NullString `json:"position"`
	IsActive          bool           `json:"is_active"`
	OnVacation        bool           `json:"on_vacation"`
	IsSick            bool           `json:"is_sick"`
	AltContactChannel sql.NullString `json:"alt_contact_channel"`
	AltContactInfo    sql.NullString `json:"alt_contact_info"`
	DeletedAt         sql.NullTime   `json:"deleted_at"`
}

type UserRole struct {
	UserID uuid.UUID `json:"user_id"`
	RoleID uuid.UUID `json:"role_id"`
}
