// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type AnalyticsCache struct {
	ID          uuid.UUID       `json:"id"`
	ProjectID   uuid.UUID       `json:"project_id"`
	ReportType  string          `json:"report_type"`
	Parameters  json.RawMessage `json:"parameters"`
	ResultData  json.RawMessage `json:"result_data"`
	GeneratedAt time.Time       `json:"generated_at"`
	ExpiresAt   time.Time       `json:"expires_at"`
}

type Attachment struct {
	ID         uuid.UUID     `json:"id"`
	TaskID     uuid.NullUUID `json:"task_id"`
	CommentID  uuid.NullUUID `json:"comment_id"`
	FileName   string        `json:"file_name"`
	FilePath   string        `json:"file_path"`
	UploadedBy uuid.UUID     `json:"uploaded_by"`
	UploadedAt time.Time     `json:"uploaded_at"`
}

type BlockedIp struct {
	IpAddress    pqtype.Inet `json:"ip_address"`
	BlockedUntil time.Time   `json:"blocked_until"`
}

type BlockedUser struct {
	UserID       uuid.UUID `json:"user_id"`
	BlockedUntil time.Time `json:"blocked_until"`
}

type Board struct {
	ID          uuid.UUID      `json:"id"`
	ProjectID   uuid.NullUUID  `json:"project_id"`
	TemplateID  uuid.NullUUID  `json:"template_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Order       int16          `json:"order"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

type ChecklistItem struct {
	ID          uuid.UUID `json:"id"`
	ChecklistID uuid.UUID `json:"checklist_id"`
	Content     string    `json:"content"`
	IsChecked   bool      `json:"is_checked"`
	Order       int16     `json:"order"`
	CreatedAt   time.Time `json:"created_at"`
}

type Column struct {
	ID              uuid.UUID      `json:"id"`
	BoardID         uuid.UUID      `json:"board_id"`
	Name            string         `json:"name"`
	SystemType      sql.NullString `json:"system_type"`
	WipLimit        sql.NullInt16  `json:"wip_limit"`
	Order           int16          `json:"order"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
	IsSprintBacklog bool           `json:"is_sprint_backlog"`
}

type Comment struct {
	ID        uuid.UUID `json:"id"`
	TaskID    uuid.UUID `json:"task_id"`
	AuthorID  uuid.UUID `json:"author_id"`
	Content   string    `json:"content"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type CommentMention struct {
	ID              uuid.UUID `json:"id"`
	CommentID       uuid.UUID `json:"comment_id"`
	ProjectMemberID uuid.UUID `json:"project_member_id"`
}

type KanbanForecastCache struct {
	ID            uuid.UUID       `json:"id"`
	ProjectID     uuid.UUID       `json:"project_id"`
	WorkItemCount int32           `json:"work_item_count"`
	ForecastData  json.RawMessage `json:"forecast_data"`
	CreatedAt     time.Time       `json:"created_at"`
	ExpiresAt     time.Time       `json:"expires_at"`
}

type LoginAttempt struct {
	ID          int64          `json:"id"`
	Email       sql.NullString `json:"email"`
	IpAddress   pqtype.Inet    `json:"ip_address"`
	Success     bool           `json:"success"`
	AttemptedAt time.Time      `json:"attempted_at"`
}

type Meeting struct {
	ID          uuid.UUID      `json:"id"`
	ProjectID   uuid.NullUUID  `json:"project_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	MeetingType string         `json:"meeting_type"`
	StartTime   time.Time      `json:"start_time"`
	EndTime     time.Time      `json:"end_time"`
	CreatedBy   uuid.UUID      `json:"created_by"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
	CanceledAt  sql.NullTime   `json:"canceled_at"`
}

type MeetingParticipant struct {
	ID        uuid.UUID `json:"id"`
	MeetingID uuid.UUID `json:"meeting_id"`
	UserID    uuid.UUID `json:"user_id"`
	Status    string    `json:"status"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type MeetingReminder struct {
	ID           uuid.UUID    `json:"id"`
	MeetingID    uuid.UUID    `json:"meeting_id"`
	UserID       uuid.UUID    `json:"user_id"`
	Channel      string       `json:"channel"`
	ReminderTime time.Time    `json:"reminder_time"`
	SentAt       sql.NullTime `json:"sent_at"`
}

type Note struct {
	ID         uuid.UUID     `json:"id"`
	ColumnID   uuid.NullUUID `json:"column_id"`
	SwimlaneID uuid.NullUUID `json:"swimlane_id"`
	Content    string        `json:"content"`
	CreatedAt  time.Time     `json:"created_at"`
	UpdatedAt  time.Time     `json:"updated_at"`
}

type Notification struct {
	ID          uuid.UUID             `json:"id"`
	UserID      uuid.UUID             `json:"user_id"`
	EventType   string                `json:"event_type"`
	Channel     string                `json:"channel"`
	Title       string                `json:"title"`
	Body        sql.NullString        `json:"body"`
	Payload     pqtype.NullRawMessage `json:"payload"`
	IsRead      bool                  `json:"is_read"`
	CreatedAt   time.Time             `json:"created_at"`
	ReadAt      sql.NullTime          `json:"read_at"`
	EmailStatus sql.NullString        `json:"email_status"`
	EmailSentAt sql.NullTime          `json:"email_sent_at"`
}

type NotificationSetting struct {
	ID                    uuid.UUID     `json:"id"`
	UserID                uuid.UUID     `json:"user_id"`
	EventType             string        `json:"event_type"`
	InSystem              bool          `json:"in_system"`
	InEmail               bool          `json:"in_email"`
	ReminderOffsetMinutes sql.NullInt32 `json:"reminder_offset_minutes"`
	CreatedAt             time.Time     `json:"created_at"`
	UpdatedAt             time.Time     `json:"updated_at"`
}

type PasswordHistory struct {
	ID           uuid.UUID `json:"id"`
	UserID       uuid.UUID `json:"user_id"`
	PasswordHash string    `json:"password_hash"`
	CreatedAt    time.Time `json:"created_at"`
}

type Permission struct {
	ID          uuid.UUID      `json:"id"`
	Code        string         `json:"code"`
	Description sql.NullString `json:"description"`
	CreatedAt   time.Time      `json:"created_at"`
}

type ProductBacklog struct {
	ID        uuid.UUID `json:"id"`
	ProjectID uuid.UUID `json:"project_id"`
	TaskID    uuid.UUID `json:"task_id"`
	Order     int32     `json:"order"`
	AddedAt   time.Time `json:"added_at"`
}

type Project struct {
	ID          uuid.UUID      `json:"id"`
	Key         string         `json:"key"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	ProjectType string         `json:"project_type"`
	OwnerID     uuid.UUID      `json:"owner_id"`
	Status      string         `json:"status"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

type ProjectMember struct {
	ID        uuid.UUID `json:"id"`
	ProjectID uuid.UUID `json:"project_id"`
	UserID    uuid.UUID `json:"user_id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type ProjectMemberRole struct {
	ProjectMemberID uuid.UUID `json:"project_member_id"`
	RoleID          uuid.UUID `json:"role_id"`
}

type ProjectTemplate struct {
	ID          uuid.UUID      `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	ProjectType string         `json:"project_type"`
	CreatedAt   time.Time      `json:"created_at"`
}

type RefreshToken struct {
	ID        uuid.UUID    `json:"id"`
	UserID    uuid.UUID    `json:"user_id"`
	TokenHash string       `json:"token_hash"`
	ExpiresAt time.Time    `json:"expires_at"`
	RevokedAt sql.NullTime `json:"revoked_at"`
	CreatedAt time.Time    `json:"created_at"`
}

type Role struct {
	ID          uuid.UUID      `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Scope       string         `json:"scope"`
	ProjectID   uuid.NullUUID  `json:"project_id"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

type RolePermission struct {
	RoleID       uuid.UUID `json:"role_id"`
	PermissionID uuid.UUID `json:"permission_id"`
}

type RoleUser struct {
	RoleID uuid.UUID `json:"role_id"`
	UserID uuid.UUID `json:"user_id"`
}

type Sprint struct {
	ID        uuid.UUID      `json:"id"`
	ProjectID uuid.UUID      `json:"project_id"`
	Name      string         `json:"name"`
	Goal      sql.NullString `json:"goal"`
	StartDate time.Time      `json:"start_date"`
	EndDate   time.Time      `json:"end_date"`
	Status    string         `json:"status"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
}

type SprintTask struct {
	ID       uuid.UUID     `json:"id"`
	SprintID uuid.UUID     `json:"sprint_id"`
	TaskID   uuid.UUID     `json:"task_id"`
	Order    sql.NullInt32 `json:"order"`
	AddedAt  time.Time     `json:"added_at"`
}

type Swimlane struct {
	ID            uuid.UUID             `json:"id"`
	BoardID       uuid.UUID             `json:"board_id"`
	Name          string                `json:"name"`
	WipLimit      sql.NullInt16         `json:"wip_limit"`
	Order         int16                 `json:"order"`
	CreatedAt     time.Time             `json:"created_at"`
	UpdatedAt     time.Time             `json:"updated_at"`
	SourceType    sql.NullString        `json:"source_type"`
	CustomFieldID uuid.NullUUID         `json:"custom_field_id"`
	ValueMappings pqtype.NullRawMessage `json:"value_mappings"`
}

type Task struct {
	ID               uuid.UUID      `json:"id"`
	Key              string         `json:"key"`
	ProjectID        uuid.UUID      `json:"project_id"`
	OwnerID          uuid.UUID      `json:"owner_id"`
	ExecutorID       uuid.NullUUID  `json:"executor_id"`
	Name             string         `json:"name"`
	Description      sql.NullString `json:"description"`
	Deadline         sql.NullTime   `json:"deadline"`
	ColumnID         uuid.UUID      `json:"column_id"`
	SwimlaneID       uuid.NullUUID  `json:"swimlane_id"`
	DeleteReason     sql.NullString `json:"delete_reason"`
	DeletedAt        sql.NullTime   `json:"deleted_at"`
	CreatedAt        time.Time      `json:"created_at"`
	UpdatedAt        time.Time      `json:"updated_at"`
	StoryPoints      sql.NullInt32  `json:"story_points"`
	BacklogType      sql.NullString `json:"backlog_type"`
	ClassOfService   sql.NullString `json:"class_of_service"`
	CycleTimeSeconds sql.NullInt64  `json:"cycle_time_seconds"`
}

type TaskChecklist struct {
	ID        uuid.UUID `json:"id"`
	TaskID    uuid.UUID `json:"task_id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
}

type TaskDependency struct {
	ID              uuid.UUID `json:"id"`
	TaskID          uuid.UUID `json:"task_id"`
	DependsOnTaskID uuid.UUID `json:"depends_on_task_id"`
	DependencyType  string    `json:"dependency_type"`
	CreatedAt       time.Time `json:"created_at"`
}

type TaskStatusHistory struct {
	ID        uuid.UUID    `json:"id"`
	TaskID    uuid.UUID    `json:"task_id"`
	ColumnID  uuid.UUID    `json:"column_id"`
	EnteredAt time.Time    `json:"entered_at"`
	LeftAt    sql.NullTime `json:"left_at"`
}

type TaskWatcher struct {
	ID              uuid.UUID `json:"id"`
	TaskID          uuid.UUID `json:"task_id"`
	ProjectMemberID uuid.UUID `json:"project_member_id"`
	CreatedAt       time.Time `json:"created_at"`
}

type User struct {
	ID           uuid.UUID      `json:"id"`
	Username     string         `json:"username"`
	Email        string         `json:"email"`
	PasswordHash string         `json:"password_hash"`
	FullName     string         `json:"full_name"`
	AvatarUrl    sql.NullString `json:"avatar_url"`
	IsActive     bool           `json:"is_active"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
}
