// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type BlockedIp struct {
	IpAddress    pqtype.Inet `json:"ip_address"`
	BlockedUntil time.Time   `json:"blocked_until"`
}

type BlockedUser struct {
	UserID       uuid.UUID `json:"user_id"`
	BlockedUntil time.Time `json:"blocked_until"`
}

type LoginAttempt struct {
	ID          int64          `json:"id"`
	Email       sql.NullString `json:"email"`
	IpAddress   pqtype.Inet    `json:"ip_address"`
	Success     bool           `json:"success"`
	AttemptedAt time.Time      `json:"attempted_at"`
}

type PasswordHistory struct {
	ID           uuid.UUID `json:"id"`
	UserID       uuid.UUID `json:"user_id"`
	PasswordHash string    `json:"password_hash"`
	CreatedAt    time.Time `json:"created_at"`
}

type RefreshToken struct {
	ID        uuid.UUID    `json:"id"`
	UserID    uuid.UUID    `json:"user_id"`
	TokenHash string       `json:"token_hash"`
	ExpiresAt time.Time    `json:"expires_at"`
	RevokedAt sql.NullTime `json:"revoked_at"`
	CreatedAt time.Time    `json:"created_at"`
}

type User struct {
	ID           uuid.UUID      `json:"id"`
	Username     string         `json:"username"`
	Email        string         `json:"email"`
	PasswordHash string         `json:"password_hash"`
	FullName     string         `json:"full_name"`
	AvatarUrl    sql.NullString `json:"avatar_url"`
	IsActive     bool           `json:"is_active"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
}
