// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notifications.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const createNotification = `-- name: CreateNotification :one

INSERT INTO notifications (user_id, event_type, title, body, payload)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, event_type, title, body, payload, is_read, created_at
`

type CreateNotificationParams struct {
	UserID    uuid.UUID             `json:"user_id"`
	EventType string                `json:"event_type"`
	Title     string                `json:"title"`
	Body      sql.NullString        `json:"body"`
	Payload   pqtype.NullRawMessage `json:"payload"`
}

// Notification feed
func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRowContext(ctx, createNotification,
		arg.UserID,
		arg.EventType,
		arg.Title,
		arg.Body,
		arg.Payload,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EventType,
		&i.Title,
		&i.Body,
		&i.Payload,
		&i.IsRead,
		&i.CreatedAt,
	)
	return i, err
}

const getNotificationSetting = `-- name: GetNotificationSetting :one
SELECT id, user_id, event_type, in_system, in_email, reminder_offset_minutes
FROM notification_settings
WHERE user_id = $1 AND event_type = $2
`

type GetNotificationSettingParams struct {
	UserID    uuid.UUID `json:"user_id"`
	EventType string    `json:"event_type"`
}

func (q *Queries) GetNotificationSetting(ctx context.Context, arg GetNotificationSettingParams) (NotificationSetting, error) {
	row := q.db.QueryRowContext(ctx, getNotificationSetting, arg.UserID, arg.EventType)
	var i NotificationSetting
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EventType,
		&i.InSystem,
		&i.InEmail,
		&i.ReminderOffsetMinutes,
	)
	return i, err
}

const getNotificationSettingsByUser = `-- name: GetNotificationSettingsByUser :many

SELECT id, user_id, event_type, in_system, in_email, reminder_offset_minutes
FROM notification_settings
WHERE user_id = $1
ORDER BY event_type
`

// Notification settings
func (q *Queries) GetNotificationSettingsByUser(ctx context.Context, userID uuid.UUID) ([]NotificationSetting, error) {
	rows, err := q.db.QueryContext(ctx, getNotificationSettingsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationSetting{}
	for rows.Next() {
		var i NotificationSetting
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EventType,
			&i.InSystem,
			&i.InEmail,
			&i.ReminderOffsetMinutes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUnreadNotificationCount = `-- name: GetUnreadNotificationCount :one
SELECT COUNT(*)::INT
FROM notifications
WHERE user_id = $1
  AND is_read = FALSE
`

func (q *Queries) GetUnreadNotificationCount(ctx context.Context, userID uuid.UUID) (int32, error) {
	row := q.db.QueryRowContext(ctx, getUnreadNotificationCount, userID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const getUserNotifications = `-- name: GetUserNotifications :many
SELECT id, user_id, event_type, title, body, payload, is_read, created_at
FROM notifications
WHERE user_id = $1
  AND ($2::bool IS FALSE OR is_read = FALSE)
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type GetUserNotificationsParams struct {
	UserID  uuid.UUID `json:"user_id"`
	Column2 bool      `json:"column_2"`
	Limit   int32     `json:"limit"`
	Offset  int32     `json:"offset"`
}

func (q *Queries) GetUserNotifications(ctx context.Context, arg GetUserNotificationsParams) ([]Notification, error) {
	rows, err := q.db.QueryContext(ctx, getUserNotifications,
		arg.UserID,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EventType,
			&i.Title,
			&i.Body,
			&i.Payload,
			&i.IsRead,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsAsRead = `-- name: MarkAllNotificationsAsRead :exec
UPDATE notifications
SET is_read = TRUE
WHERE user_id = $1
  AND is_read = FALSE
`

func (q *Queries) MarkAllNotificationsAsRead(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, markAllNotificationsAsRead, userID)
	return err
}

const markNotificationAsRead = `-- name: MarkNotificationAsRead :exec
UPDATE notifications
SET is_read = TRUE
WHERE id = $1
  AND user_id = $2
`

type MarkNotificationAsReadParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) MarkNotificationAsRead(ctx context.Context, arg MarkNotificationAsReadParams) error {
	_, err := q.db.ExecContext(ctx, markNotificationAsRead, arg.ID, arg.UserID)
	return err
}

const upsertNotificationSetting = `-- name: UpsertNotificationSetting :exec
INSERT INTO notification_settings (user_id, event_type, in_system, in_email, reminder_offset_minutes)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (user_id, event_type) DO UPDATE
SET in_system = EXCLUDED.in_system,
    in_email = EXCLUDED.in_email,
    reminder_offset_minutes = EXCLUDED.reminder_offset_minutes
`

type UpsertNotificationSettingParams struct {
	UserID                uuid.UUID     `json:"user_id"`
	EventType             string        `json:"event_type"`
	InSystem              bool          `json:"in_system"`
	InEmail               bool          `json:"in_email"`
	ReminderOffsetMinutes sql.NullInt32 `json:"reminder_offset_minutes"`
}

func (q *Queries) UpsertNotificationSetting(ctx context.Context, arg UpsertNotificationSettingParams) error {
	_, err := q.db.ExecContext(ctx, upsertNotificationSetting,
		arg.UserID,
		arg.EventType,
		arg.InSystem,
		arg.InEmail,
		arg.ReminderOffsetMinutes,
	)
	return err
}
