// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: password_policy.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const getCurrentPasswordPolicy = `-- name: GetCurrentPasswordPolicy :one
SELECT id, min_length, require_digits, require_lowercase, require_uppercase, require_special, notes, updated_at, updated_by FROM password_policy
ORDER BY updated_at DESC
LIMIT 1
`

// Текущая парольная политика (последняя по дате обновления)
func (q *Queries) GetCurrentPasswordPolicy(ctx context.Context) (PasswordPolicy, error) {
	row := q.db.QueryRowContext(ctx, getCurrentPasswordPolicy)
	var i PasswordPolicy
	err := row.Scan(
		&i.ID,
		&i.MinLength,
		&i.RequireDigits,
		&i.RequireLowercase,
		&i.RequireUppercase,
		&i.RequireSpecial,
		&i.Notes,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const insertPasswordPolicy = `-- name: InsertPasswordPolicy :one
INSERT INTO password_policy (min_length, require_digits, require_lowercase, require_uppercase, require_special, notes, updated_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, min_length, require_digits, require_lowercase, require_uppercase, require_special, notes, updated_at, updated_by
`

type InsertPasswordPolicyParams struct {
	MinLength        int32          `json:"min_length"`
	RequireDigits    bool           `json:"require_digits"`
	RequireLowercase bool           `json:"require_lowercase"`
	RequireUppercase bool           `json:"require_uppercase"`
	RequireSpecial   bool           `json:"require_special"`
	Notes            sql.NullString `json:"notes"`
	UpdatedBy        uuid.NullUUID  `json:"updated_by"`
}

// Добавить новую версию политики (актуальной считается последняя)
func (q *Queries) InsertPasswordPolicy(ctx context.Context, arg InsertPasswordPolicyParams) (PasswordPolicy, error) {
	row := q.db.QueryRowContext(ctx, insertPasswordPolicy,
		arg.MinLength,
		arg.RequireDigits,
		arg.RequireLowercase,
		arg.RequireUppercase,
		arg.RequireSpecial,
		arg.Notes,
		arg.UpdatedBy,
	)
	var i PasswordPolicy
	err := row.Scan(
		&i.ID,
		&i.MinLength,
		&i.RequireDigits,
		&i.RequireLowercase,
		&i.RequireUppercase,
		&i.RequireSpecial,
		&i.Notes,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}
