// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: product_backlog.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const addToProductBacklog = `-- name: AddToProductBacklog :one

INSERT INTO backlog (project_id, task_id, sort_order)
VALUES ($1, $2, $3)
RETURNING project_id, task_id, sort_order
`

type AddToProductBacklogParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	TaskID    uuid.UUID `json:"task_id"`
	SortOrder int32     `json:"sort_order"`
}

// Backlog ordering
func (q *Queries) AddToProductBacklog(ctx context.Context, arg AddToProductBacklogParams) (Backlog, error) {
	row := q.db.QueryRowContext(ctx, addToProductBacklog, arg.ProjectID, arg.TaskID, arg.SortOrder)
	var i Backlog
	err := row.Scan(&i.ProjectID, &i.TaskID, &i.SortOrder)
	return i, err
}

const getProductBacklog = `-- name: GetProductBacklog :many
SELECT project_id, task_id, sort_order
FROM backlog
WHERE project_id = $1
ORDER BY sort_order
`

func (q *Queries) GetProductBacklog(ctx context.Context, projectID uuid.UUID) ([]Backlog, error) {
	rows, err := q.db.QueryContext(ctx, getProductBacklog, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Backlog{}
	for rows.Next() {
		var i Backlog
		if err := rows.Scan(&i.ProjectID, &i.TaskID, &i.SortOrder); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeFromProductBacklog = `-- name: RemoveFromProductBacklog :exec
DELETE FROM backlog
WHERE project_id = $1 AND task_id = $2
`

type RemoveFromProductBacklogParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	TaskID    uuid.UUID `json:"task_id"`
}

func (q *Queries) RemoveFromProductBacklog(ctx context.Context, arg RemoveFromProductBacklogParams) error {
	_, err := q.db.ExecContext(ctx, removeFromProductBacklog, arg.ProjectID, arg.TaskID)
	return err
}

const updateProductBacklogOrder = `-- name: UpdateProductBacklogOrder :exec
UPDATE backlog
SET sort_order = $3
WHERE project_id = $1 AND task_id = $2
`

type UpdateProductBacklogOrderParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	TaskID    uuid.UUID `json:"task_id"`
	SortOrder int32     `json:"sort_order"`
}

func (q *Queries) UpdateProductBacklogOrder(ctx context.Context, arg UpdateProductBacklogOrderParams) error {
	_, err := q.db.ExecContext(ctx, updateProductBacklogOrder, arg.ProjectID, arg.TaskID, arg.SortOrder)
	return err
}
