// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: product_backlog.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const addToProductBacklog = `-- name: AddToProductBacklog :one

INSERT INTO product_backlog (project_id, task_id, "order")
VALUES ($1, $2, $3)
RETURNING id, project_id, task_id, "order", added_at
`

type AddToProductBacklogParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	TaskID    uuid.UUID `json:"task_id"`
	Order     int32     `json:"order"`
}

// Product backlog ordering
func (q *Queries) AddToProductBacklog(ctx context.Context, arg AddToProductBacklogParams) (ProductBacklog, error) {
	row := q.db.QueryRowContext(ctx, addToProductBacklog, arg.ProjectID, arg.TaskID, arg.Order)
	var i ProductBacklog
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.TaskID,
		&i.Order,
		&i.AddedAt,
	)
	return i, err
}

const getProductBacklog = `-- name: GetProductBacklog :many
SELECT id, project_id, task_id, "order", added_at
FROM product_backlog
WHERE project_id = $1
ORDER BY "order"
`

func (q *Queries) GetProductBacklog(ctx context.Context, projectID uuid.UUID) ([]ProductBacklog, error) {
	rows, err := q.db.QueryContext(ctx, getProductBacklog, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProductBacklog{}
	for rows.Next() {
		var i ProductBacklog
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.TaskID,
			&i.Order,
			&i.AddedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeFromProductBacklog = `-- name: RemoveFromProductBacklog :exec
DELETE FROM product_backlog
WHERE project_id = $1 AND task_id = $2
`

type RemoveFromProductBacklogParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	TaskID    uuid.UUID `json:"task_id"`
}

func (q *Queries) RemoveFromProductBacklog(ctx context.Context, arg RemoveFromProductBacklogParams) error {
	_, err := q.db.ExecContext(ctx, removeFromProductBacklog, arg.ProjectID, arg.TaskID)
	return err
}

const updateProductBacklogOrder = `-- name: UpdateProductBacklogOrder :exec
UPDATE product_backlog
SET "order" = $3
WHERE project_id = $1 AND task_id = $2
`

type UpdateProductBacklogOrderParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	TaskID    uuid.UUID `json:"task_id"`
	Order     int32     `json:"order"`
}

func (q *Queries) UpdateProductBacklogOrder(ctx context.Context, arg UpdateProductBacklogOrderParams) error {
	_, err := q.db.ExecContext(ctx, updateProductBacklogOrder, arg.ProjectID, arg.TaskID, arg.Order)
	return err
}
