// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: project_params.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const createProjectParam = `-- name: CreateProjectParam :one
INSERT INTO project_params (project_id, name, field_type, is_required, options, value)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, project_id, name, field_type, is_required, options, value
`

type CreateProjectParamParams struct {
	ProjectID  uuid.NullUUID         `json:"project_id"`
	Name       string                `json:"name"`
	FieldType  string                `json:"field_type"`
	IsRequired bool                  `json:"is_required"`
	Options    pqtype.NullRawMessage `json:"options"`
	Value      sql.NullString        `json:"value"`
}

type CreateProjectParamRow struct {
	ID         uuid.UUID             `json:"id"`
	ProjectID  uuid.NullUUID         `json:"project_id"`
	Name       string                `json:"name"`
	FieldType  string                `json:"field_type"`
	IsRequired bool                  `json:"is_required"`
	Options    pqtype.NullRawMessage `json:"options"`
	Value      sql.NullString        `json:"value"`
}

func (q *Queries) CreateProjectParam(ctx context.Context, arg CreateProjectParamParams) (CreateProjectParamRow, error) {
	row := q.db.QueryRowContext(ctx, createProjectParam,
		arg.ProjectID,
		arg.Name,
		arg.FieldType,
		arg.IsRequired,
		arg.Options,
		arg.Value,
	)
	var i CreateProjectParamRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.FieldType,
		&i.IsRequired,
		&i.Options,
		&i.Value,
	)
	return i, err
}

const deleteProjectParamByID = `-- name: DeleteProjectParamByID :exec
DELETE FROM project_params WHERE id = $1
`

func (q *Queries) DeleteProjectParamByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteProjectParamByID, id)
	return err
}

const getProjectParamByID = `-- name: GetProjectParamByID :one
SELECT id, project_id, name, field_type, is_required, options, value
FROM project_params
WHERE id = $1
`

type GetProjectParamByIDRow struct {
	ID         uuid.UUID             `json:"id"`
	ProjectID  uuid.NullUUID         `json:"project_id"`
	Name       string                `json:"name"`
	FieldType  string                `json:"field_type"`
	IsRequired bool                  `json:"is_required"`
	Options    pqtype.NullRawMessage `json:"options"`
	Value      sql.NullString        `json:"value"`
}

func (q *Queries) GetProjectParamByID(ctx context.Context, id uuid.UUID) (GetProjectParamByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getProjectParamByID, id)
	var i GetProjectParamByIDRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.FieldType,
		&i.IsRequired,
		&i.Options,
		&i.Value,
	)
	return i, err
}

const listProjectParams = `-- name: ListProjectParams :many

SELECT id, project_id, name, field_type, is_required, options, value
FROM project_params
WHERE project_id = $1
`

type ListProjectParamsRow struct {
	ID         uuid.UUID             `json:"id"`
	ProjectID  uuid.NullUUID         `json:"project_id"`
	Name       string                `json:"name"`
	FieldType  string                `json:"field_type"`
	IsRequired bool                  `json:"is_required"`
	Options    pqtype.NullRawMessage `json:"options"`
	Value      sql.NullString        `json:"value"`
}

// Project params (custom only; system params generated from Go constants)
func (q *Queries) ListProjectParams(ctx context.Context, projectID uuid.NullUUID) ([]ListProjectParamsRow, error) {
	rows, err := q.db.QueryContext(ctx, listProjectParams, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectParamsRow{}
	for rows.Next() {
		var i ListProjectParamsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.FieldType,
			&i.IsRequired,
			&i.Options,
			&i.Value,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProjectParam = `-- name: UpdateProjectParam :one
UPDATE project_params
SET name = COALESCE($1, name),
    is_required = COALESCE($2, is_required),
    options = COALESCE($3, options),
    value = $4
WHERE id = $5
RETURNING id, project_id, name, field_type, is_required, options, value
`

type UpdateProjectParamParams struct {
	Name       sql.NullString        `json:"name"`
	IsRequired sql.NullBool          `json:"is_required"`
	Options    pqtype.NullRawMessage `json:"options"`
	Value      sql.NullString        `json:"value"`
	ID         uuid.UUID             `json:"id"`
}

type UpdateProjectParamRow struct {
	ID         uuid.UUID             `json:"id"`
	ProjectID  uuid.NullUUID         `json:"project_id"`
	Name       string                `json:"name"`
	FieldType  string                `json:"field_type"`
	IsRequired bool                  `json:"is_required"`
	Options    pqtype.NullRawMessage `json:"options"`
	Value      sql.NullString        `json:"value"`
}

func (q *Queries) UpdateProjectParam(ctx context.Context, arg UpdateProjectParamParams) (UpdateProjectParamRow, error) {
	row := q.db.QueryRowContext(ctx, updateProjectParam,
		arg.Name,
		arg.IsRequired,
		arg.Options,
		arg.Value,
		arg.ID,
	)
	var i UpdateProjectParamRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.FieldType,
		&i.IsRequired,
		&i.Options,
		&i.Value,
	)
	return i, err
}
