// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: project_roles.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const countMembersWithRole = `-- name: CountMembersWithRole :one
SELECT COUNT(*)::int AS count
FROM member_roles mr
JOIN members m ON m.id = mr.member_id
WHERE m.project_id = $1 AND mr.role_id = $2
`

type CountMembersWithRoleParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	RoleID    uuid.UUID `json:"role_id"`
}

func (q *Queries) CountMembersWithRole(ctx context.Context, arg CountMembersWithRoleParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, countMembersWithRole, arg.ProjectID, arg.RoleID)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const countProjRoleDefinitionMembers = `-- name: CountProjRoleDefinitionMembers :one
SELECT COUNT(*)::int AS count
FROM member_roles mr
WHERE mr.role_id = $1
`

func (q *Queries) CountProjRoleDefinitionMembers(ctx context.Context, roleID uuid.UUID) (int32, error) {
	row := q.db.QueryRowContext(ctx, countProjRoleDefinitionMembers, roleID)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const countProjRoleDefinitions = `-- name: CountProjRoleDefinitions :one
SELECT COUNT(*)::int AS count FROM roles WHERE project_id = $1
`

func (q *Queries) CountProjRoleDefinitions(ctx context.Context, projectID uuid.NullUUID) (int32, error) {
	row := q.db.QueryRowContext(ctx, countProjRoleDefinitions, projectID)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const createProjRoleDefinition = `-- name: CreateProjRoleDefinition :one
INSERT INTO roles (project_id, scope, name, description, is_admin)
VALUES ($1, 'project', $2, $3, $4)
RETURNING id, project_id, name, description, is_admin
`

type CreateProjRoleDefinitionParams struct {
	ProjectID   uuid.NullUUID `json:"project_id"`
	Name        string        `json:"name"`
	Description string        `json:"description"`
	IsAdmin     bool          `json:"is_admin"`
}

type CreateProjRoleDefinitionRow struct {
	ID          uuid.UUID     `json:"id"`
	ProjectID   uuid.NullUUID `json:"project_id"`
	Name        string        `json:"name"`
	Description string        `json:"description"`
	IsAdmin     bool          `json:"is_admin"`
}

func (q *Queries) CreateProjRoleDefinition(ctx context.Context, arg CreateProjRoleDefinitionParams) (CreateProjRoleDefinitionRow, error) {
	row := q.db.QueryRowContext(ctx, createProjRoleDefinition,
		arg.ProjectID,
		arg.Name,
		arg.Description,
		arg.IsAdmin,
	)
	var i CreateProjRoleDefinitionRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Description,
		&i.IsAdmin,
	)
	return i, err
}

const deleteProjRoleDefPermissionsByRoleID = `-- name: DeleteProjRoleDefPermissionsByRoleID :exec
DELETE FROM role_permissions WHERE role_id = $1
`

func (q *Queries) DeleteProjRoleDefPermissionsByRoleID(ctx context.Context, roleID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteProjRoleDefPermissionsByRoleID, roleID)
	return err
}

const deleteProjRoleDefinitionByID = `-- name: DeleteProjRoleDefinitionByID :exec
DELETE FROM roles WHERE id = $1
`

func (q *Queries) DeleteProjRoleDefinitionByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteProjRoleDefinitionByID, id)
	return err
}

const getProjRoleDefinitionByID = `-- name: GetProjRoleDefinitionByID :one
SELECT id, project_id, name, description, is_admin
FROM roles
WHERE id = $1
`

type GetProjRoleDefinitionByIDRow struct {
	ID          uuid.UUID     `json:"id"`
	ProjectID   uuid.NullUUID `json:"project_id"`
	Name        string        `json:"name"`
	Description string        `json:"description"`
	IsAdmin     bool          `json:"is_admin"`
}

func (q *Queries) GetProjRoleDefinitionByID(ctx context.Context, id uuid.UUID) (GetProjRoleDefinitionByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getProjRoleDefinitionByID, id)
	var i GetProjRoleDefinitionByIDRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Description,
		&i.IsAdmin,
	)
	return i, err
}

const getProjectAdminRoleID = `-- name: GetProjectAdminRoleID :one
SELECT id FROM roles WHERE project_id = $1 AND is_admin = true LIMIT 1
`

func (q *Queries) GetProjectAdminRoleID(ctx context.Context, projectID uuid.NullUUID) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, getProjectAdminRoleID, projectID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const listProjRoleDefPermissions = `-- name: ListProjRoleDefPermissions :many

SELECT rp.role_id, rp.permission_code, rp.access
FROM role_permissions rp
WHERE rp.role_id = $1
`

// Role permissions (uses permission_code directly)
func (q *Queries) ListProjRoleDefPermissions(ctx context.Context, roleID uuid.UUID) ([]RolePermission, error) {
	rows, err := q.db.QueryContext(ctx, listProjRoleDefPermissions, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RolePermission{}
	for rows.Next() {
		var i RolePermission
		if err := rows.Scan(&i.RoleID, &i.PermissionCode, &i.Access); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjRoleDefinitions = `-- name: ListProjRoleDefinitions :many

SELECT id, project_id, name, description, is_admin
FROM roles
WHERE project_id = $1
`

type ListProjRoleDefinitionsRow struct {
	ID          uuid.UUID     `json:"id"`
	ProjectID   uuid.NullUUID `json:"project_id"`
	Name        string        `json:"name"`
	Description string        `json:"description"`
	IsAdmin     bool          `json:"is_admin"`
}

// Roles for projects (scope='project', filtered by project_id)
func (q *Queries) ListProjRoleDefinitions(ctx context.Context, projectID uuid.NullUUID) ([]ListProjRoleDefinitionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listProjRoleDefinitions, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjRoleDefinitionsRow{}
	for rows.Next() {
		var i ListProjRoleDefinitionsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Description,
			&i.IsAdmin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProjRoleDefinition = `-- name: UpdateProjRoleDefinition :one
UPDATE roles
SET name = $2, description = $3
WHERE id = $1
RETURNING id, project_id, name, description, is_admin
`

type UpdateProjRoleDefinitionParams struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
}

type UpdateProjRoleDefinitionRow struct {
	ID          uuid.UUID     `json:"id"`
	ProjectID   uuid.NullUUID `json:"project_id"`
	Name        string        `json:"name"`
	Description string        `json:"description"`
	IsAdmin     bool          `json:"is_admin"`
}

func (q *Queries) UpdateProjRoleDefinition(ctx context.Context, arg UpdateProjRoleDefinitionParams) (UpdateProjRoleDefinitionRow, error) {
	row := q.db.QueryRowContext(ctx, updateProjRoleDefinition, arg.ID, arg.Name, arg.Description)
	var i UpdateProjRoleDefinitionRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Description,
		&i.IsAdmin,
	)
	return i, err
}

const upsertProjRoleDefPermission = `-- name: UpsertProjRoleDefPermission :exec
INSERT INTO role_permissions (role_id, permission_code, access)
VALUES ($1, $2, $3)
ON CONFLICT (role_id, permission_code) DO UPDATE SET access = EXCLUDED.access
`

type UpsertProjRoleDefPermissionParams struct {
	RoleID         uuid.UUID      `json:"role_id"`
	PermissionCode string         `json:"permission_code"`
	Access         sql.NullString `json:"access"`
}

func (q *Queries) UpsertProjRoleDefPermission(ctx context.Context, arg UpsertProjRoleDefPermissionParams) error {
	_, err := q.db.ExecContext(ctx, upsertProjRoleDefPermission, arg.RoleID, arg.PermissionCode, arg.Access)
	return err
}
