// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: project_member_roles.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const addRoleToMember = `-- name: AddRoleToMember :exec
INSERT INTO member_roles (member_id, role_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddRoleToMemberParams struct {
	MemberID uuid.UUID `json:"member_id"`
	RoleID   uuid.UUID `json:"role_id"`
}

func (q *Queries) AddRoleToMember(ctx context.Context, arg AddRoleToMemberParams) error {
	_, err := q.db.ExecContext(ctx, addRoleToMember, arg.MemberID, arg.RoleID)
	return err
}

const deleteMemberRoles = `-- name: DeleteMemberRoles :exec
DELETE FROM member_roles
WHERE member_id = $1
`

func (q *Queries) DeleteMemberRoles(ctx context.Context, memberID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteMemberRoles, memberID)
	return err
}

const listMemberRoleIDs = `-- name: ListMemberRoleIDs :many
SELECT mr.role_id
FROM member_roles mr
WHERE mr.member_id = $1
`

func (q *Queries) ListMemberRoleIDs(ctx context.Context, memberID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.QueryContext(ctx, listMemberRoleIDs, memberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var role_id uuid.UUID
		if err := rows.Scan(&role_id); err != nil {
			return nil, err
		}
		items = append(items, role_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMemberRoles = `-- name: ListMemberRoles :many

SELECT r.id::text
FROM member_roles mr
JOIN roles r ON r.id = mr.role_id
WHERE mr.member_id = $1
`

// Member roles
func (q *Queries) ListMemberRoles(ctx context.Context, memberID uuid.UUID) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listMemberRoles, memberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var r_id string
		if err := rows.Scan(&r_id); err != nil {
			return nil, err
		}
		items = append(items, r_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
