// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: project_member_roles.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const addRoleToMember = `-- name: AddRoleToMember :exec
INSERT INTO project_member_roles (project_member_id, role_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddRoleToMemberParams struct {
	ProjectMemberID uuid.UUID `json:"project_member_id"`
	RoleID          uuid.UUID `json:"role_id"`
}

func (q *Queries) AddRoleToMember(ctx context.Context, arg AddRoleToMemberParams) error {
	_, err := q.db.ExecContext(ctx, addRoleToMember, arg.ProjectMemberID, arg.RoleID)
	return err
}

const deleteMemberRoles = `-- name: DeleteMemberRoles :exec
DELETE FROM project_member_roles
WHERE project_member_id = $1
`

func (q *Queries) DeleteMemberRoles(ctx context.Context, projectMemberID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteMemberRoles, projectMemberID)
	return err
}

const listMemberRoleIDs = `-- name: ListMemberRoleIDs :many
SELECT pmr.role_id
FROM project_member_roles pmr
WHERE pmr.project_member_id = $1
`

func (q *Queries) ListMemberRoleIDs(ctx context.Context, projectMemberID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.QueryContext(ctx, listMemberRoleIDs, projectMemberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var role_id uuid.UUID
		if err := rows.Scan(&role_id); err != nil {
			return nil, err
		}
		items = append(items, role_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMemberRoles = `-- name: ListMemberRoles :many

SELECT r.name
FROM project_member_roles pmr
JOIN roles r ON r.id = pmr.role_id
WHERE pmr.project_member_id = $1
ORDER BY r.name
`

// Project member roles
func (q *Queries) ListMemberRoles(ctx context.Context, projectMemberID uuid.UUID) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listMemberRoles, projectMemberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
