// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: project_members.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const addProjectMember = `-- name: AddProjectMember :one
INSERT INTO members (project_id, user_id)
VALUES ($1, $2)
ON CONFLICT (project_id, user_id) DO NOTHING
RETURNING id, project_id, user_id
`

type AddProjectMemberParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) AddProjectMember(ctx context.Context, arg AddProjectMemberParams) (Member, error) {
	row := q.db.QueryRowContext(ctx, addProjectMember, arg.ProjectID, arg.UserID)
	var i Member
	err := row.Scan(&i.ID, &i.ProjectID, &i.UserID)
	return i, err
}

const getProjectMember = `-- name: GetProjectMember :one
SELECT m.id, m.project_id, m.user_id
FROM members m
WHERE m.id = $1
`

func (q *Queries) GetProjectMember(ctx context.Context, id uuid.UUID) (Member, error) {
	row := q.db.QueryRowContext(ctx, getProjectMember, id)
	var i Member
	err := row.Scan(&i.ID, &i.ProjectID, &i.UserID)
	return i, err
}

const listProjectMembers = `-- name: ListProjectMembers :many

SELECT m.id, m.project_id, m.user_id
FROM members m
WHERE m.project_id = $1
ORDER BY m.id ASC
`

// Project members
func (q *Queries) ListProjectMembers(ctx context.Context, projectID uuid.UUID) ([]Member, error) {
	rows, err := q.db.QueryContext(ctx, listProjectMembers, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Member{}
	for rows.Next() {
		var i Member
		if err := rows.Scan(&i.ID, &i.ProjectID, &i.UserID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectMembersByUser = `-- name: ListProjectMembersByUser :many
SELECT m.id, m.project_id, m.user_id, p.name AS project_name
FROM members m
JOIN projects p ON p.id = m.project_id
WHERE m.user_id = $1
ORDER BY p.name
`

type ListProjectMembersByUserRow struct {
	ID          uuid.UUID `json:"id"`
	ProjectID   uuid.UUID `json:"project_id"`
	UserID      uuid.UUID `json:"user_id"`
	ProjectName string    `json:"project_name"`
}

func (q *Queries) ListProjectMembersByUser(ctx context.Context, userID uuid.UUID) ([]ListProjectMembersByUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listProjectMembersByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectMembersByUserRow{}
	for rows.Next() {
		var i ListProjectMembersByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.UserID,
			&i.ProjectName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeProjectMember = `-- name: RemoveProjectMember :exec
DELETE FROM members
WHERE id = $1
`

func (q *Queries) RemoveProjectMember(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, removeProjectMember, id)
	return err
}
