// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: project_templates.sql

package db

import (
	"context"
	"database/sql"
)

const createProjectTemplate = `-- name: CreateProjectTemplate :one
INSERT INTO project_templates (name, description, project_type)
VALUES ($1, $2, $3)
RETURNING id, name, description, project_type, created_at
`

type CreateProjectTemplateParams struct {
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	ProjectType string         `json:"project_type"`
}

func (q *Queries) CreateProjectTemplate(ctx context.Context, arg CreateProjectTemplateParams) (ProjectTemplate, error) {
	row := q.db.QueryRowContext(ctx, createProjectTemplate, arg.Name, arg.Description, arg.ProjectType)
	var i ProjectTemplate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ProjectType,
		&i.CreatedAt,
	)
	return i, err
}

const listProjectTemplates = `-- name: ListProjectTemplates :many

SELECT id, name, description, project_type, created_at
FROM project_templates
ORDER BY created_at DESC
`

// Project templates
func (q *Queries) ListProjectTemplates(ctx context.Context) ([]ProjectTemplate, error) {
	rows, err := q.db.QueryContext(ctx, listProjectTemplates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProjectTemplate{}
	for rows.Next() {
		var i ProjectTemplate
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.ProjectType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
