// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: project_params.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const createProjectParam = `-- name: CreateProjectParam :one
INSERT INTO fields (kind, project_id, name, description, field_type, is_system, is_required, sort_order, options, value)
VALUES ('project_param', $1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, project_id, name, description, field_type, is_system, is_required, sort_order, options, value
`

type CreateProjectParamParams struct {
	ProjectID   uuid.NullUUID         `json:"project_id"`
	Name        string                `json:"name"`
	Description string                `json:"description"`
	FieldType   string                `json:"field_type"`
	IsSystem    bool                  `json:"is_system"`
	IsRequired  bool                  `json:"is_required"`
	SortOrder   int32                 `json:"sort_order"`
	Options     pqtype.NullRawMessage `json:"options"`
	Value       sql.NullString        `json:"value"`
}

type CreateProjectParamRow struct {
	ID          uuid.UUID             `json:"id"`
	ProjectID   uuid.NullUUID         `json:"project_id"`
	Name        string                `json:"name"`
	Description string                `json:"description"`
	FieldType   string                `json:"field_type"`
	IsSystem    bool                  `json:"is_system"`
	IsRequired  bool                  `json:"is_required"`
	SortOrder   int32                 `json:"sort_order"`
	Options     pqtype.NullRawMessage `json:"options"`
	Value       sql.NullString        `json:"value"`
}

func (q *Queries) CreateProjectParam(ctx context.Context, arg CreateProjectParamParams) (CreateProjectParamRow, error) {
	row := q.db.QueryRowContext(ctx, createProjectParam,
		arg.ProjectID,
		arg.Name,
		arg.Description,
		arg.FieldType,
		arg.IsSystem,
		arg.IsRequired,
		arg.SortOrder,
		arg.Options,
		arg.Value,
	)
	var i CreateProjectParamRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Description,
		&i.FieldType,
		&i.IsSystem,
		&i.IsRequired,
		&i.SortOrder,
		&i.Options,
		&i.Value,
	)
	return i, err
}

const deleteProjectParamByID = `-- name: DeleteProjectParamByID :exec
DELETE FROM fields WHERE id = $1 AND kind = 'project_param'
`

func (q *Queries) DeleteProjectParamByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteProjectParamByID, id)
	return err
}

const getProjectParamByID = `-- name: GetProjectParamByID :one
SELECT id, project_id, name, description, field_type, is_system, is_required, sort_order, options, value
FROM fields
WHERE id = $1 AND kind = 'project_param'
`

type GetProjectParamByIDRow struct {
	ID          uuid.UUID             `json:"id"`
	ProjectID   uuid.NullUUID         `json:"project_id"`
	Name        string                `json:"name"`
	Description string                `json:"description"`
	FieldType   string                `json:"field_type"`
	IsSystem    bool                  `json:"is_system"`
	IsRequired  bool                  `json:"is_required"`
	SortOrder   int32                 `json:"sort_order"`
	Options     pqtype.NullRawMessage `json:"options"`
	Value       sql.NullString        `json:"value"`
}

func (q *Queries) GetProjectParamByID(ctx context.Context, id uuid.UUID) (GetProjectParamByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getProjectParamByID, id)
	var i GetProjectParamByIDRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Description,
		&i.FieldType,
		&i.IsSystem,
		&i.IsRequired,
		&i.SortOrder,
		&i.Options,
		&i.Value,
	)
	return i, err
}

const listProjectParams = `-- name: ListProjectParams :many

SELECT id, project_id, name, description, field_type, is_system, is_required, sort_order, options, value
FROM fields
WHERE project_id = $1 AND kind = 'project_param'
ORDER BY sort_order ASC
`

type ListProjectParamsRow struct {
	ID          uuid.UUID             `json:"id"`
	ProjectID   uuid.NullUUID         `json:"project_id"`
	Name        string                `json:"name"`
	Description string                `json:"description"`
	FieldType   string                `json:"field_type"`
	IsSystem    bool                  `json:"is_system"`
	IsRequired  bool                  `json:"is_required"`
	SortOrder   int32                 `json:"sort_order"`
	Options     pqtype.NullRawMessage `json:"options"`
	Value       sql.NullString        `json:"value"`
}

// Project params (stored in unified `fields` table, kind='project_param')
func (q *Queries) ListProjectParams(ctx context.Context, projectID uuid.NullUUID) ([]ListProjectParamsRow, error) {
	rows, err := q.db.QueryContext(ctx, listProjectParams, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectParamsRow{}
	for rows.Next() {
		var i ListProjectParamsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Description,
			&i.FieldType,
			&i.IsSystem,
			&i.IsRequired,
			&i.SortOrder,
			&i.Options,
			&i.Value,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProjectParam = `-- name: UpdateProjectParam :one
UPDATE fields
SET name = COALESCE($1, name),
    is_required = COALESCE($2, is_required),
    options = COALESCE($3, options),
    value = COALESCE($4, value)
WHERE id = $5 AND kind = 'project_param'
RETURNING id, project_id, name, description, field_type, is_system, is_required, sort_order, options, value
`

type UpdateProjectParamParams struct {
	Name       sql.NullString        `json:"name"`
	IsRequired sql.NullBool          `json:"is_required"`
	Options    pqtype.NullRawMessage `json:"options"`
	Value      sql.NullString        `json:"value"`
	ID         uuid.UUID             `json:"id"`
}

type UpdateProjectParamRow struct {
	ID          uuid.UUID             `json:"id"`
	ProjectID   uuid.NullUUID         `json:"project_id"`
	Name        string                `json:"name"`
	Description string                `json:"description"`
	FieldType   string                `json:"field_type"`
	IsSystem    bool                  `json:"is_system"`
	IsRequired  bool                  `json:"is_required"`
	SortOrder   int32                 `json:"sort_order"`
	Options     pqtype.NullRawMessage `json:"options"`
	Value       sql.NullString        `json:"value"`
}

func (q *Queries) UpdateProjectParam(ctx context.Context, arg UpdateProjectParamParams) (UpdateProjectParamRow, error) {
	row := q.db.QueryRowContext(ctx, updateProjectParam,
		arg.Name,
		arg.IsRequired,
		arg.Options,
		arg.Value,
		arg.ID,
	)
	var i UpdateProjectParamRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Description,
		&i.FieldType,
		&i.IsSystem,
		&i.IsRequired,
		&i.SortOrder,
		&i.Options,
		&i.Value,
	)
	return i, err
}

const updateProjectParamOrder = `-- name: UpdateProjectParamOrder :exec
UPDATE fields SET sort_order = $2 WHERE id = $1 AND kind = 'project_param'
`

type UpdateProjectParamOrderParams struct {
	ID        uuid.UUID `json:"id"`
	SortOrder int32     `json:"sort_order"`
}

func (q *Queries) UpdateProjectParamOrder(ctx context.Context, arg UpdateProjectParamOrderParams) error {
	_, err := q.db.ExecContext(ctx, updateProjectParamOrder, arg.ID, arg.SortOrder)
	return err
}
