// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: projects.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createProject = `-- name: CreateProject :one

INSERT INTO projects (key, name, description, project_type, owner_id, status)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, key, name, description, project_type, owner_id, status, created_at, updated_at
`

type CreateProjectParams struct {
	Key         string         `json:"key"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	ProjectType string         `json:"project_type"`
	OwnerID     uuid.UUID      `json:"owner_id"`
	Status      string         `json:"status"`
}

// Projects
func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, createProject,
		arg.Key,
		arg.Name,
		arg.Description,
		arg.ProjectType,
		arg.OwnerID,
		arg.Status,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.ProjectType,
		&i.OwnerID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProject = `-- name: DeleteProject :exec
DELETE FROM projects
WHERE id = $1
`

func (q *Queries) DeleteProject(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteProject, id)
	return err
}

const getProjectByID = `-- name: GetProjectByID :one
SELECT id, key, name, description, project_type, owner_id, status, created_at, updated_at
FROM projects
WHERE id = $1
`

func (q *Queries) GetProjectByID(ctx context.Context, id uuid.UUID) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProjectByID, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.ProjectType,
		&i.OwnerID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectByKey = `-- name: GetProjectByKey :one
SELECT id, key, name, description, project_type, owner_id, status, created_at, updated_at
FROM projects
WHERE key = $1
`

func (q *Queries) GetProjectByKey(ctx context.Context, key string) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProjectByKey, key)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.ProjectType,
		&i.OwnerID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUserProjects = `-- name: ListUserProjects :many
SELECT id, key, name, description, project_type, owner_id, status, created_at, updated_at
FROM projects
WHERE owner_id = $1
  AND ($2::text IS NULL OR status = $2)
  AND ($3::text IS NULL OR project_type = $3)
ORDER BY created_at DESC
`

type ListUserProjectsParams struct {
	OwnerID uuid.UUID `json:"owner_id"`
	Column2 string    `json:"column_2"`
	Column3 string    `json:"column_3"`
}

func (q *Queries) ListUserProjects(ctx context.Context, arg ListUserProjectsParams) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, listUserProjects, arg.OwnerID, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Name,
			&i.Description,
			&i.ProjectType,
			&i.OwnerID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects
SET name = COALESCE($1, name),
    description = COALESCE($2, description),
    status = COALESCE($3, status),
    updated_at = NOW()
WHERE id = $4
RETURNING id, key, name, description, project_type, owner_id, status, created_at, updated_at
`

type UpdateProjectParams struct {
	Name        sql.NullString `json:"name"`
	Description sql.NullString `json:"description"`
	Status      sql.NullString `json:"status"`
	ID          uuid.UUID      `json:"id"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, updateProject,
		arg.Name,
		arg.Description,
		arg.Status,
		arg.ID,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.ProjectType,
		&i.OwnerID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
