// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: projects.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createProject = `-- name: CreateProject :one

INSERT INTO projects (key, name, description, project_type, owner_id, status, sprint_duration_weeks, incomplete_tasks_action)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, key, name, description, project_type, owner_id, status, created_at, sprint_duration_weeks, incomplete_tasks_action
`

type CreateProjectParams struct {
	Key                   string         `json:"key"`
	Name                  string         `json:"name"`
	Description           sql.NullString `json:"description"`
	ProjectType           string         `json:"project_type"`
	OwnerID               uuid.UUID      `json:"owner_id"`
	Status                string         `json:"status"`
	SprintDurationWeeks   sql.NullInt32  `json:"sprint_duration_weeks"`
	IncompleteTasksAction string         `json:"incomplete_tasks_action"`
}

// Projects
func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, createProject,
		arg.Key,
		arg.Name,
		arg.Description,
		arg.ProjectType,
		arg.OwnerID,
		arg.Status,
		arg.SprintDurationWeeks,
		arg.IncompleteTasksAction,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.ProjectType,
		&i.OwnerID,
		&i.Status,
		&i.CreatedAt,
		&i.SprintDurationWeeks,
		&i.IncompleteTasksAction,
	)
	return i, err
}

const deleteProject = `-- name: DeleteProject :exec
DELETE FROM projects
WHERE id = $1
`

func (q *Queries) DeleteProject(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteProject, id)
	return err
}

const getProjectByID = `-- name: GetProjectByID :one
SELECT id, key, name, description, project_type, owner_id, status, created_at, sprint_duration_weeks, incomplete_tasks_action
FROM projects
WHERE id = $1
`

func (q *Queries) GetProjectByID(ctx context.Context, id uuid.UUID) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProjectByID, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.ProjectType,
		&i.OwnerID,
		&i.Status,
		&i.CreatedAt,
		&i.SprintDurationWeeks,
		&i.IncompleteTasksAction,
	)
	return i, err
}

const getProjectByKey = `-- name: GetProjectByKey :one
SELECT id, key, name, description, project_type, owner_id, status, created_at, sprint_duration_weeks, incomplete_tasks_action
FROM projects
WHERE key = $1
`

func (q *Queries) GetProjectByKey(ctx context.Context, key string) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProjectByKey, key)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.ProjectType,
		&i.OwnerID,
		&i.Status,
		&i.CreatedAt,
		&i.SprintDurationWeeks,
		&i.IncompleteTasksAction,
	)
	return i, err
}

const listUserProjects = `-- name: ListUserProjects :many
SELECT DISTINCT p.id, p.key, p.name, p.description, p.project_type, p.owner_id, p.status, p.created_at,
       u.full_name AS owner_full_name, u.avatar_url AS owner_avatar_url, u.email AS owner_email
FROM projects p
JOIN users u ON u.id = p.owner_id
LEFT JOIN members m ON m.project_id = p.id AND m.user_id = $1
WHERE (p.owner_id = $1 OR m.user_id IS NOT NULL)
  AND ($2::text IS NULL OR p.status = $2)
  AND ($3::text IS NULL OR p.project_type = $3)
  AND ($4::text IS NULL OR $4::text = '' OR (
       p.name ILIKE '%' || $4 || '%'
       OR p.key ILIKE '%' || $4 || '%'
       OR COALESCE(p.description, '') ILIKE '%' || $4 || '%'
       OR u.full_name ILIKE '%' || $4 || '%'))
ORDER BY p.created_at DESC
`

type ListUserProjectsParams struct {
	UserID       uuid.UUID      `json:"user_id"`
	StatusFilter sql.NullString `json:"status_filter"`
	TypeFilter   sql.NullString `json:"type_filter"`
	SearchQuery  sql.NullString `json:"search_query"`
}

type ListUserProjectsRow struct {
	ID             uuid.UUID      `json:"id"`
	Key            string         `json:"key"`
	Name           string         `json:"name"`
	Description    sql.NullString `json:"description"`
	ProjectType    string         `json:"project_type"`
	OwnerID        uuid.UUID      `json:"owner_id"`
	Status         string         `json:"status"`
	CreatedAt      time.Time      `json:"created_at"`
	OwnerFullName  string         `json:"owner_full_name"`
	OwnerAvatarUrl sql.NullString `json:"owner_avatar_url"`
	OwnerEmail     string         `json:"owner_email"`
}

func (q *Queries) ListUserProjects(ctx context.Context, arg ListUserProjectsParams) ([]ListUserProjectsRow, error) {
	rows, err := q.db.QueryContext(ctx, listUserProjects,
		arg.UserID,
		arg.StatusFilter,
		arg.TypeFilter,
		arg.SearchQuery,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserProjectsRow{}
	for rows.Next() {
		var i ListUserProjectsRow
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Name,
			&i.Description,
			&i.ProjectType,
			&i.OwnerID,
			&i.Status,
			&i.CreatedAt,
			&i.OwnerFullName,
			&i.OwnerAvatarUrl,
			&i.OwnerEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects
SET name = COALESCE($1, name),
    description = $2,
    status = COALESCE($3, status),
    owner_id = COALESCE($4, owner_id),
    sprint_duration_weeks = COALESCE($5, sprint_duration_weeks),
    incomplete_tasks_action = COALESCE($6, incomplete_tasks_action)
WHERE id = $7
RETURNING id, key, name, description, project_type, owner_id, status, created_at, sprint_duration_weeks, incomplete_tasks_action
`

type UpdateProjectParams struct {
	Name                  sql.NullString `json:"name"`
	Description           sql.NullString `json:"description"`
	Status                sql.NullString `json:"status"`
	OwnerID               uuid.NullUUID  `json:"owner_id"`
	SprintDurationWeeks   sql.NullInt32  `json:"sprint_duration_weeks"`
	IncompleteTasksAction sql.NullString `json:"incomplete_tasks_action"`
	ID                    uuid.UUID      `json:"id"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, updateProject,
		arg.Name,
		arg.Description,
		arg.Status,
		arg.OwnerID,
		arg.SprintDurationWeeks,
		arg.IncompleteTasksAction,
		arg.ID,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.ProjectType,
		&i.OwnerID,
		&i.Status,
		&i.CreatedAt,
		&i.SprintDurationWeeks,
		&i.IncompleteTasksAction,
	)
	return i, err
}
