// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: project_members.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addProjectMember = `-- name: AddProjectMember :one
INSERT INTO project_members (project_id, user_id)
VALUES ($1, $2)
ON CONFLICT (project_id, user_id) DO NOTHING
RETURNING id, project_id, user_id, created_at, updated_at
`

type AddProjectMemberParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) AddProjectMember(ctx context.Context, arg AddProjectMemberParams) (ProjectMember, error) {
	row := q.db.QueryRowContext(ctx, addProjectMember, arg.ProjectID, arg.UserID)
	var i ProjectMember
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectMember = `-- name: GetProjectMember :one
SELECT pm.id,
       pm.project_id,
       pm.user_id,
       pm.created_at,
       pm.updated_at
FROM project_members pm
WHERE pm.id = $1
`

func (q *Queries) GetProjectMember(ctx context.Context, id uuid.UUID) (ProjectMember, error) {
	row := q.db.QueryRowContext(ctx, getProjectMember, id)
	var i ProjectMember
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProjectMembers = `-- name: ListProjectMembers :many

SELECT pm.id,
       pm.project_id,
       pm.user_id,
       pm.created_at,
       pm.updated_at
FROM project_members pm
WHERE pm.project_id = $1
ORDER BY pm.created_at ASC
`

// Project members
func (q *Queries) ListProjectMembers(ctx context.Context, projectID uuid.UUID) ([]ProjectMember, error) {
	rows, err := q.db.QueryContext(ctx, listProjectMembers, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProjectMember{}
	for rows.Next() {
		var i ProjectMember
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectMembersByUser = `-- name: ListProjectMembersByUser :many
SELECT pm.id,
       pm.project_id,
       pm.user_id,
       p.name AS project_name,
       pm.created_at,
       pm.updated_at
FROM project_members pm
JOIN projects p ON p.id = pm.project_id
WHERE pm.user_id = $1
ORDER BY p.name
`

type ListProjectMembersByUserRow struct {
	ID          uuid.UUID `json:"id"`
	ProjectID   uuid.UUID `json:"project_id"`
	UserID      uuid.UUID `json:"user_id"`
	ProjectName string    `json:"project_name"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

func (q *Queries) ListProjectMembersByUser(ctx context.Context, userID uuid.UUID) ([]ListProjectMembersByUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listProjectMembersByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectMembersByUserRow{}
	for rows.Next() {
		var i ListProjectMembersByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.UserID,
			&i.ProjectName,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeProjectMember = `-- name: RemoveProjectMember :exec
DELETE FROM project_members
WHERE id = $1
`

func (q *Queries) RemoveProjectMember(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, removeProjectMember, id)
	return err
}
