// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: references.sql

package db

import (
	"context"

	"github.com/lib/pq"
)

const listRefColumnSystemTypes = `-- name: ListRefColumnSystemTypes :many

SELECT key, name, description, sort_order
FROM ref_column_system_types
ORDER BY sort_order ASC
`

// Reference data queries
func (q *Queries) ListRefColumnSystemTypes(ctx context.Context) ([]RefColumnSystemType, error) {
	rows, err := q.db.QueryContext(ctx, listRefColumnSystemTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RefColumnSystemType{}
	for rows.Next() {
		var i RefColumnSystemType
		if err := rows.Scan(
			&i.Key,
			&i.Name,
			&i.Description,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRefEstimationUnits = `-- name: ListRefEstimationUnits :many
SELECT key, name, available_for
FROM ref_estimation_units
ORDER BY key ASC
`

func (q *Queries) ListRefEstimationUnits(ctx context.Context) ([]RefEstimationUnit, error) {
	rows, err := q.db.QueryContext(ctx, listRefEstimationUnits)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RefEstimationUnit{}
	for rows.Next() {
		var i RefEstimationUnit
		if err := rows.Scan(&i.Key, &i.Name, pq.Array(&i.AvailableFor)); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRefFieldTypes = `-- name: ListRefFieldTypes :many
SELECT key, name
FROM ref_field_types
ORDER BY key ASC
`

func (q *Queries) ListRefFieldTypes(ctx context.Context) ([]RefFieldType, error) {
	rows, err := q.db.QueryContext(ctx, listRefFieldTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RefFieldType{}
	for rows.Next() {
		var i RefFieldType
		if err := rows.Scan(&i.Key, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRefPriorityTypes = `-- name: ListRefPriorityTypes :many
SELECT key, name, available_for, default_values
FROM ref_priority_types
ORDER BY key ASC
`

func (q *Queries) ListRefPriorityTypes(ctx context.Context) ([]RefPriorityType, error) {
	rows, err := q.db.QueryContext(ctx, listRefPriorityTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RefPriorityType{}
	for rows.Next() {
		var i RefPriorityType
		if err := rows.Scan(
			&i.Key,
			&i.Name,
			pq.Array(&i.AvailableFor),
			pq.Array(&i.DefaultValues),
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRefSystemTaskFields = `-- name: ListRefSystemTaskFields :many
SELECT key, name, field_type, available_for, description, sort_order
FROM ref_system_task_fields
ORDER BY sort_order ASC
`

func (q *Queries) ListRefSystemTaskFields(ctx context.Context) ([]RefSystemTaskField, error) {
	rows, err := q.db.QueryContext(ctx, listRefSystemTaskFields)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RefSystemTaskField{}
	for rows.Next() {
		var i RefSystemTaskField
		if err := rows.Scan(
			&i.Key,
			&i.Name,
			&i.FieldType,
			pq.Array(&i.AvailableFor),
			&i.Description,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRefTaskStatusTypes = `-- name: ListRefTaskStatusTypes :many
SELECT key, name, description, is_column_type
FROM ref_task_status_types
ORDER BY key ASC
`

func (q *Queries) ListRefTaskStatusTypes(ctx context.Context) ([]RefTaskStatusType, error) {
	rows, err := q.db.QueryContext(ctx, listRefTaskStatusTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RefTaskStatusType{}
	for rows.Next() {
		var i RefTaskStatusType
		if err := rows.Scan(
			&i.Key,
			&i.Name,
			&i.Description,
			&i.IsColumnType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
