// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: role_users.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const assignRoleToUser = `-- name: AssignRoleToUser :exec
INSERT INTO user_roles (user_id, role_id)
VALUES ($2, $1)
ON CONFLICT DO NOTHING
`

type AssignRoleToUserParams struct {
	RoleID uuid.UUID `json:"role_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) AssignRoleToUser(ctx context.Context, arg AssignRoleToUserParams) error {
	_, err := q.db.ExecContext(ctx, assignRoleToUser, arg.RoleID, arg.UserID)
	return err
}

const countUsersWithRole = `-- name: CountUsersWithRole :one
SELECT COUNT(*)::int AS count
FROM user_roles
WHERE role_id = $1
`

func (q *Queries) CountUsersWithRole(ctx context.Context, roleID uuid.UUID) (int32, error) {
	row := q.db.QueryRowContext(ctx, countUsersWithRole, roleID)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const deleteUserRoles = `-- name: DeleteUserRoles :exec
DELETE FROM user_roles
WHERE user_id = $1
`

func (q *Queries) DeleteUserRoles(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteUserRoles, userID)
	return err
}

const deleteUserSystemRoles = `-- name: DeleteUserSystemRoles :exec
DELETE FROM user_roles
WHERE user_id = $1
  AND role_id IN (SELECT id FROM roles WHERE scope = 'system')
`

func (q *Queries) DeleteUserSystemRoles(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteUserSystemRoles, userID)
	return err
}

const listUserSystemRoles = `-- name: ListUserSystemRoles :many

SELECT r.id, r.name, r.description, r.scope, r.is_admin
FROM user_roles ur
JOIN roles r ON r.id = ur.role_id
WHERE ur.user_id = $1
  AND r.scope = 'system'
`

type ListUserSystemRolesRow struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	Scope       string    `json:"scope"`
	IsAdmin     bool      `json:"is_admin"`
}

// User role assignments (system roles)
func (q *Queries) ListUserSystemRoles(ctx context.Context, userID uuid.UUID) ([]ListUserSystemRolesRow, error) {
	rows, err := q.db.QueryContext(ctx, listUserSystemRoles, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserSystemRolesRow{}
	for rows.Next() {
		var i ListUserSystemRolesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Scope,
			&i.IsAdmin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeRoleFromUser = `-- name: RemoveRoleFromUser :exec
DELETE FROM user_roles
WHERE role_id = $1 AND user_id = $2
`

type RemoveRoleFromUserParams struct {
	RoleID uuid.UUID `json:"role_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) RemoveRoleFromUser(ctx context.Context, arg RemoveRoleFromUserParams) error {
	_, err := q.db.ExecContext(ctx, removeRoleFromUser, arg.RoleID, arg.UserID)
	return err
}

const userHasSystemPermission = `-- name: UserHasSystemPermission :one
SELECT EXISTS (
    SELECT 1
    FROM user_roles ur
    JOIN roles r ON r.id = ur.role_id
    JOIN role_permissions rp ON rp.role_id = r.id
    WHERE ur.user_id = $1
      AND r.scope = 'system'
      AND rp.permission_code = $2
) AS has_permission
`

type UserHasSystemPermissionParams struct {
	UserID         uuid.UUID `json:"user_id"`
	PermissionCode string    `json:"permission_code"`
}

func (q *Queries) UserHasSystemPermission(ctx context.Context, arg UserHasSystemPermissionParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, userHasSystemPermission, arg.UserID, arg.PermissionCode)
	var has_permission bool
	err := row.Scan(&has_permission)
	return has_permission, err
}
