// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: roles.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const countSystemRoles = `-- name: CountSystemRoles :one
SELECT COUNT(*) FROM roles WHERE scope = 'system'
`

func (q *Queries) CountSystemRoles(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSystemRoles)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProjectRole = `-- name: CreateProjectRole :one
INSERT INTO roles (name, description, scope, project_id)
VALUES ($1, $2, 'project', $3)
RETURNING id, name, description, scope, project_id, created_at, updated_at
`

type CreateProjectRoleParams struct {
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	ProjectID   uuid.NullUUID  `json:"project_id"`
}

func (q *Queries) CreateProjectRole(ctx context.Context, arg CreateProjectRoleParams) (Role, error) {
	row := q.db.QueryRowContext(ctx, createProjectRole, arg.Name, arg.Description, arg.ProjectID)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Scope,
		&i.ProjectID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSystemRole = `-- name: CreateSystemRole :one
INSERT INTO roles (name, description, scope, project_id)
VALUES ($1, $2, 'system', NULL)
RETURNING id, name, description, scope, project_id, created_at, updated_at
`

type CreateSystemRoleParams struct {
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
}

func (q *Queries) CreateSystemRole(ctx context.Context, arg CreateSystemRoleParams) (Role, error) {
	row := q.db.QueryRowContext(ctx, createSystemRole, arg.Name, arg.Description)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Scope,
		&i.ProjectID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRole = `-- name: DeleteRole :exec
DELETE FROM roles
WHERE id = $1
`

func (q *Queries) DeleteRole(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteRole, id)
	return err
}

const getRoleByID = `-- name: GetRoleByID :one
SELECT id, name, description, scope, project_id, created_at, updated_at
FROM roles
WHERE id = $1
`

func (q *Queries) GetRoleByID(ctx context.Context, id uuid.UUID) (Role, error) {
	row := q.db.QueryRowContext(ctx, getRoleByID, id)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Scope,
		&i.ProjectID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProjectRoles = `-- name: ListProjectRoles :many
SELECT id, name, description, scope, project_id, created_at, updated_at
FROM roles
WHERE scope = 'project' AND project_id = $1
ORDER BY name
`

func (q *Queries) ListProjectRoles(ctx context.Context, projectID uuid.NullUUID) ([]Role, error) {
	rows, err := q.db.QueryContext(ctx, listProjectRoles, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Role{}
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Scope,
			&i.ProjectID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSystemRoles = `-- name: ListSystemRoles :many

SELECT id, name, description, scope, project_id, created_at, updated_at
FROM roles
WHERE scope = 'system'
ORDER BY name
`

// System roles and permissions
func (q *Queries) ListSystemRoles(ctx context.Context) ([]Role, error) {
	rows, err := q.db.QueryContext(ctx, listSystemRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Role{}
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Scope,
			&i.ProjectID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSystemRolesPaginated = `-- name: ListSystemRolesPaginated :many
SELECT id, name, description, scope, project_id, created_at, updated_at
FROM roles
WHERE scope = 'system'
ORDER BY name
LIMIT $1 OFFSET $2
`

type ListSystemRolesPaginatedParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListSystemRolesPaginated(ctx context.Context, arg ListSystemRolesPaginatedParams) ([]Role, error) {
	rows, err := q.db.QueryContext(ctx, listSystemRolesPaginated, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Role{}
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Scope,
			&i.ProjectID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSystemRole = `-- name: UpdateSystemRole :one
UPDATE roles
SET name = $2,
    description = $3,
    updated_at = NOW()
WHERE id = $1 AND scope = 'system'
RETURNING id, name, description, scope, project_id, created_at, updated_at
`

type UpdateSystemRoleParams struct {
	ID          uuid.UUID      `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
}

func (q *Queries) UpdateSystemRole(ctx context.Context, arg UpdateSystemRoleParams) (Role, error) {
	row := q.db.QueryRowContext(ctx, updateSystemRole, arg.ID, arg.Name, arg.Description)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Scope,
		&i.ProjectID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
