// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: scrum_analytics.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const getSprintTaskStatusHistory = `-- name: GetSprintTaskStatusHistory :many
SELECT h.task_id, h.column_id, h.entered_at, h.left_at, c.system_type AS column_system_type
FROM task_status_history h
JOIN sprint_tasks st ON st.task_id = h.task_id
LEFT JOIN columns c ON h.column_id = c.id
WHERE st.sprint_id = $1
ORDER BY h.entered_at
`

type GetSprintTaskStatusHistoryRow struct {
	TaskID           uuid.UUID      `json:"task_id"`
	ColumnID         uuid.UUID      `json:"column_id"`
	EnteredAt        time.Time      `json:"entered_at"`
	LeftAt           sql.NullTime   `json:"left_at"`
	ColumnSystemType sql.NullString `json:"column_system_type"`
}

func (q *Queries) GetSprintTaskStatusHistory(ctx context.Context, sprintID uuid.UUID) ([]GetSprintTaskStatusHistoryRow, error) {
	rows, err := q.db.QueryContext(ctx, getSprintTaskStatusHistory, sprintID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetSprintTaskStatusHistoryRow{}
	for rows.Next() {
		var i GetSprintTaskStatusHistoryRow
		if err := rows.Scan(
			&i.TaskID,
			&i.ColumnID,
			&i.EnteredAt,
			&i.LeftAt,
			&i.ColumnSystemType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSprintTasksForAnalytics = `-- name: GetSprintTasksForAnalytics :many

SELECT t.id, t.estimation, c.system_type AS column_system_type
FROM tasks t
JOIN sprint_tasks st ON st.task_id = t.id
LEFT JOIN columns c ON t.column_id = c.id
WHERE st.sprint_id = $1 AND t.deleted_at IS NULL
`

type GetSprintTasksForAnalyticsRow struct {
	ID               uuid.UUID      `json:"id"`
	Estimation       sql.NullString `json:"estimation"`
	ColumnSystemType sql.NullString `json:"column_system_type"`
}

// Scrum analytics queries
func (q *Queries) GetSprintTasksForAnalytics(ctx context.Context, sprintID uuid.UUID) ([]GetSprintTasksForAnalyticsRow, error) {
	rows, err := q.db.QueryContext(ctx, getSprintTasksForAnalytics, sprintID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetSprintTasksForAnalyticsRow{}
	for rows.Next() {
		var i GetSprintTasksForAnalyticsRow
		if err := rows.Scan(&i.ID, &i.Estimation, &i.ColumnSystemType); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
