// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sprints.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createSprint = `-- name: CreateSprint :one

INSERT INTO sprints (project_id, name, goal, start_date, end_date, status)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, project_id, name, goal, start_date, end_date, status, created_at, updated_at
`

type CreateSprintParams struct {
	ProjectID uuid.UUID      `json:"project_id"`
	Name      string         `json:"name"`
	Goal      sql.NullString `json:"goal"`
	StartDate time.Time      `json:"start_date"`
	EndDate   time.Time      `json:"end_date"`
	Status    string         `json:"status"`
}

// Sprints basic CRUD
func (q *Queries) CreateSprint(ctx context.Context, arg CreateSprintParams) (Sprint, error) {
	row := q.db.QueryRowContext(ctx, createSprint,
		arg.ProjectID,
		arg.Name,
		arg.Goal,
		arg.StartDate,
		arg.EndDate,
		arg.Status,
	)
	var i Sprint
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Goal,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSprint = `-- name: DeleteSprint :exec
DELETE FROM sprints
WHERE id = $1
`

func (q *Queries) DeleteSprint(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteSprint, id)
	return err
}

const getActiveSprint = `-- name: GetActiveSprint :one
SELECT id, project_id, name, goal, start_date, end_date, status, created_at, updated_at
FROM sprints
WHERE project_id = $1
  AND status = 'active'
LIMIT 1
`

func (q *Queries) GetActiveSprint(ctx context.Context, projectID uuid.UUID) (Sprint, error) {
	row := q.db.QueryRowContext(ctx, getActiveSprint, projectID)
	var i Sprint
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Goal,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectSprints = `-- name: GetProjectSprints :many
SELECT id, project_id, name, goal, start_date, end_date, status, created_at, updated_at
FROM sprints
WHERE project_id = $1
ORDER BY start_date DESC
`

func (q *Queries) GetProjectSprints(ctx context.Context, projectID uuid.UUID) ([]Sprint, error) {
	rows, err := q.db.QueryContext(ctx, getProjectSprints, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Sprint{}
	for rows.Next() {
		var i Sprint
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Goal,
			&i.StartDate,
			&i.EndDate,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSprintByID = `-- name: GetSprintByID :one
SELECT id, project_id, name, goal, start_date, end_date, status, created_at, updated_at
FROM sprints
WHERE id = $1
`

func (q *Queries) GetSprintByID(ctx context.Context, id uuid.UUID) (Sprint, error) {
	row := q.db.QueryRowContext(ctx, getSprintByID, id)
	var i Sprint
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Goal,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSprint = `-- name: UpdateSprint :one
UPDATE sprints
SET name       = COALESCE($1, name),
    goal       = $2,
    start_date = COALESCE($3, start_date),
    end_date   = COALESCE($4, end_date),
    status     = COALESCE($5, status),
    updated_at = NOW()
WHERE id = $6
RETURNING id, project_id, name, goal, start_date, end_date, status, created_at, updated_at
`

type UpdateSprintParams struct {
	Name      sql.NullString `json:"name"`
	Goal      sql.NullString `json:"goal"`
	StartDate sql.NullTime   `json:"start_date"`
	EndDate   sql.NullTime   `json:"end_date"`
	Status    sql.NullString `json:"status"`
	ID        uuid.UUID      `json:"id"`
}

func (q *Queries) UpdateSprint(ctx context.Context, arg UpdateSprintParams) (Sprint, error) {
	row := q.db.QueryRowContext(ctx, updateSprint,
		arg.Name,
		arg.Goal,
		arg.StartDate,
		arg.EndDate,
		arg.Status,
		arg.ID,
	)
	var i Sprint
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Goal,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSprintStatuses = `-- name: UpdateSprintStatuses :exec
UPDATE sprints
SET status = CASE
                 WHEN CURRENT_DATE < start_date THEN 'planned'
                 WHEN CURRENT_DATE > end_date THEN 'completed'
                 ELSE 'active'
             END,
    updated_at = NOW()
`

func (q *Queries) UpdateSprintStatuses(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, updateSprintStatuses)
	return err
}
