// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sprint_tasks.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const addTaskToSprint = `-- name: AddTaskToSprint :one

INSERT INTO sprint_tasks (sprint_id, task_id, sort_order)
VALUES ($1, $2, $3)
ON CONFLICT (sprint_id, task_id) DO UPDATE
SET sort_order = EXCLUDED.sort_order
RETURNING sprint_id, task_id, sort_order
`

type AddTaskToSprintParams struct {
	SprintID  uuid.UUID     `json:"sprint_id"`
	TaskID    uuid.UUID     `json:"task_id"`
	SortOrder sql.NullInt32 `json:"sort_order"`
}

// Sprint tasks: linking tasks to sprints
func (q *Queries) AddTaskToSprint(ctx context.Context, arg AddTaskToSprintParams) (SprintTask, error) {
	row := q.db.QueryRowContext(ctx, addTaskToSprint, arg.SprintID, arg.TaskID, arg.SortOrder)
	var i SprintTask
	err := row.Scan(&i.SprintID, &i.TaskID, &i.SortOrder)
	return i, err
}

const getSprintTasks = `-- name: GetSprintTasks :many
SELECT st.sprint_id, st.task_id, st.sort_order
FROM sprint_tasks st
JOIN tasks t ON t.id = st.task_id
WHERE st.sprint_id = $1 AND t.deleted_at IS NULL
ORDER BY st.sort_order NULLS LAST
`

func (q *Queries) GetSprintTasks(ctx context.Context, sprintID uuid.UUID) ([]SprintTask, error) {
	rows, err := q.db.QueryContext(ctx, getSprintTasks, sprintID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SprintTask{}
	for rows.Next() {
		var i SprintTask
		if err := rows.Scan(&i.SprintID, &i.TaskID, &i.SortOrder); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSprintTasksFull = `-- name: ListSprintTasksFull :many
SELECT t.id, t.key, t.project_id, t.owner_id, t.executor_id, t.name, t.description,
       t.deadline, t.column_id, t.swimlane_id, t.deleted_at, t.created_at,
       t.priority, t.estimation, t.board_id,
       c.name AS column_name, c.system_type AS column_system_type,
       m_owner.user_id AS owner_user_id,
       m_exec.user_id AS executor_user_id
FROM tasks t
JOIN sprint_tasks st ON st.task_id = t.id
LEFT JOIN columns c ON t.column_id = c.id
JOIN members m_owner ON m_owner.id = t.owner_id
LEFT JOIN members m_exec ON m_exec.id = t.executor_id
WHERE st.sprint_id = $1 AND t.deleted_at IS NULL
ORDER BY st.sort_order NULLS LAST
`

type ListSprintTasksFullRow struct {
	ID               uuid.UUID      `json:"id"`
	Key              string         `json:"key"`
	ProjectID        uuid.UUID      `json:"project_id"`
	OwnerID          uuid.UUID      `json:"owner_id"`
	ExecutorID       uuid.NullUUID  `json:"executor_id"`
	Name             string         `json:"name"`
	Description      sql.NullString `json:"description"`
	Deadline         sql.NullTime   `json:"deadline"`
	ColumnID         uuid.NullUUID  `json:"column_id"`
	SwimlaneID       uuid.NullUUID  `json:"swimlane_id"`
	DeletedAt        sql.NullTime   `json:"deleted_at"`
	CreatedAt        time.Time      `json:"created_at"`
	Priority         sql.NullString `json:"priority"`
	Estimation       sql.NullString `json:"estimation"`
	BoardID          uuid.UUID      `json:"board_id"`
	ColumnName       sql.NullString `json:"column_name"`
	ColumnSystemType sql.NullString `json:"column_system_type"`
	OwnerUserID      uuid.UUID      `json:"owner_user_id"`
	ExecutorUserID   uuid.NullUUID  `json:"executor_user_id"`
}

func (q *Queries) ListSprintTasksFull(ctx context.Context, sprintID uuid.UUID) ([]ListSprintTasksFullRow, error) {
	rows, err := q.db.QueryContext(ctx, listSprintTasksFull, sprintID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSprintTasksFullRow{}
	for rows.Next() {
		var i ListSprintTasksFullRow
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.ProjectID,
			&i.OwnerID,
			&i.ExecutorID,
			&i.Name,
			&i.Description,
			&i.Deadline,
			&i.ColumnID,
			&i.SwimlaneID,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.Priority,
			&i.Estimation,
			&i.BoardID,
			&i.ColumnName,
			&i.ColumnSystemType,
			&i.OwnerUserID,
			&i.ExecutorUserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeTaskFromAllSprints = `-- name: RemoveTaskFromAllSprints :exec
DELETE FROM sprint_tasks
WHERE task_id = $1
`

func (q *Queries) RemoveTaskFromAllSprints(ctx context.Context, taskID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, removeTaskFromAllSprints, taskID)
	return err
}

const removeTaskFromSprint = `-- name: RemoveTaskFromSprint :exec
DELETE FROM sprint_tasks
WHERE sprint_id = $1 AND task_id = $2
`

type RemoveTaskFromSprintParams struct {
	SprintID uuid.UUID `json:"sprint_id"`
	TaskID   uuid.UUID `json:"task_id"`
}

func (q *Queries) RemoveTaskFromSprint(ctx context.Context, arg RemoveTaskFromSprintParams) error {
	_, err := q.db.ExecContext(ctx, removeTaskFromSprint, arg.SprintID, arg.TaskID)
	return err
}

const updateTaskOrder = `-- name: UpdateTaskOrder :exec
UPDATE sprint_tasks
SET sort_order = $3
WHERE sprint_id = $1 AND task_id = $2
`

type UpdateTaskOrderParams struct {
	SprintID  uuid.UUID     `json:"sprint_id"`
	TaskID    uuid.UUID     `json:"task_id"`
	SortOrder sql.NullInt32 `json:"sort_order"`
}

func (q *Queries) UpdateTaskOrder(ctx context.Context, arg UpdateTaskOrderParams) error {
	_, err := q.db.ExecContext(ctx, updateTaskOrder, arg.SprintID, arg.TaskID, arg.SortOrder)
	return err
}
