// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sprint_tasks.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const addTaskToSprint = `-- name: AddTaskToSprint :one

INSERT INTO sprint_tasks (sprint_id, task_id, "order")
VALUES ($1, $2, $3)
ON CONFLICT (sprint_id, task_id) DO UPDATE
SET "order" = EXCLUDED."order",
    added_at = NOW()
RETURNING id, sprint_id, task_id, "order", added_at
`

type AddTaskToSprintParams struct {
	SprintID uuid.UUID     `json:"sprint_id"`
	TaskID   uuid.UUID     `json:"task_id"`
	Order    sql.NullInt32 `json:"order"`
}

// Sprint tasks: linking tasks to sprints
func (q *Queries) AddTaskToSprint(ctx context.Context, arg AddTaskToSprintParams) (SprintTask, error) {
	row := q.db.QueryRowContext(ctx, addTaskToSprint, arg.SprintID, arg.TaskID, arg.Order)
	var i SprintTask
	err := row.Scan(
		&i.ID,
		&i.SprintID,
		&i.TaskID,
		&i.Order,
		&i.AddedAt,
	)
	return i, err
}

const getSprintTasks = `-- name: GetSprintTasks :many
SELECT id, sprint_id, task_id, "order", added_at
FROM sprint_tasks
WHERE sprint_id = $1
ORDER BY "order" NULLS LAST, added_at
`

func (q *Queries) GetSprintTasks(ctx context.Context, sprintID uuid.UUID) ([]SprintTask, error) {
	rows, err := q.db.QueryContext(ctx, getSprintTasks, sprintID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SprintTask{}
	for rows.Next() {
		var i SprintTask
		if err := rows.Scan(
			&i.ID,
			&i.SprintID,
			&i.TaskID,
			&i.Order,
			&i.AddedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeTaskFromSprint = `-- name: RemoveTaskFromSprint :exec
DELETE FROM sprint_tasks
WHERE sprint_id = $1 AND task_id = $2
`

type RemoveTaskFromSprintParams struct {
	SprintID uuid.UUID `json:"sprint_id"`
	TaskID   uuid.UUID `json:"task_id"`
}

func (q *Queries) RemoveTaskFromSprint(ctx context.Context, arg RemoveTaskFromSprintParams) error {
	_, err := q.db.ExecContext(ctx, removeTaskFromSprint, arg.SprintID, arg.TaskID)
	return err
}

const updateTaskOrder = `-- name: UpdateTaskOrder :exec
UPDATE sprint_tasks
SET "order" = $3
WHERE sprint_id = $1 AND task_id = $2
`

type UpdateTaskOrderParams struct {
	SprintID uuid.UUID     `json:"sprint_id"`
	TaskID   uuid.UUID     `json:"task_id"`
	Order    sql.NullInt32 `json:"order"`
}

func (q *Queries) UpdateTaskOrder(ctx context.Context, arg UpdateTaskOrderParams) error {
	_, err := q.db.ExecContext(ctx, updateTaskOrder, arg.SprintID, arg.TaskID, arg.Order)
	return err
}
