// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sprint_tasks.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const addTaskToSprint = `-- name: AddTaskToSprint :one

INSERT INTO sprint_tasks (sprint_id, task_id, sort_order)
VALUES ($1, $2, $3)
ON CONFLICT (sprint_id, task_id) DO UPDATE
SET sort_order = EXCLUDED.sort_order
RETURNING sprint_id, task_id, sort_order
`

type AddTaskToSprintParams struct {
	SprintID  uuid.UUID     `json:"sprint_id"`
	TaskID    uuid.UUID     `json:"task_id"`
	SortOrder sql.NullInt32 `json:"sort_order"`
}

// Sprint tasks: linking tasks to sprints
func (q *Queries) AddTaskToSprint(ctx context.Context, arg AddTaskToSprintParams) (SprintTask, error) {
	row := q.db.QueryRowContext(ctx, addTaskToSprint, arg.SprintID, arg.TaskID, arg.SortOrder)
	var i SprintTask
	err := row.Scan(&i.SprintID, &i.TaskID, &i.SortOrder)
	return i, err
}

const getSprintTasks = `-- name: GetSprintTasks :many
SELECT sprint_id, task_id, sort_order
FROM sprint_tasks
WHERE sprint_id = $1
ORDER BY sort_order NULLS LAST
`

func (q *Queries) GetSprintTasks(ctx context.Context, sprintID uuid.UUID) ([]SprintTask, error) {
	rows, err := q.db.QueryContext(ctx, getSprintTasks, sprintID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SprintTask{}
	for rows.Next() {
		var i SprintTask
		if err := rows.Scan(&i.SprintID, &i.TaskID, &i.SortOrder); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeTaskFromSprint = `-- name: RemoveTaskFromSprint :exec
DELETE FROM sprint_tasks
WHERE sprint_id = $1 AND task_id = $2
`

type RemoveTaskFromSprintParams struct {
	SprintID uuid.UUID `json:"sprint_id"`
	TaskID   uuid.UUID `json:"task_id"`
}

func (q *Queries) RemoveTaskFromSprint(ctx context.Context, arg RemoveTaskFromSprintParams) error {
	_, err := q.db.ExecContext(ctx, removeTaskFromSprint, arg.SprintID, arg.TaskID)
	return err
}

const updateTaskOrder = `-- name: UpdateTaskOrder :exec
UPDATE sprint_tasks
SET sort_order = $3
WHERE sprint_id = $1 AND task_id = $2
`

type UpdateTaskOrderParams struct {
	SprintID  uuid.UUID     `json:"sprint_id"`
	TaskID    uuid.UUID     `json:"task_id"`
	SortOrder sql.NullInt32 `json:"sort_order"`
}

func (q *Queries) UpdateTaskOrder(ctx context.Context, arg UpdateTaskOrderParams) error {
	_, err := q.db.ExecContext(ctx, updateTaskOrder, arg.SprintID, arg.TaskID, arg.SortOrder)
	return err
}
