// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: swimlane_config.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const getSwimlaneConfig = `-- name: GetSwimlaneConfig :one
SELECT id, board_id, name, wip_limit, "order", created_at, updated_at, source_type, custom_field_id, value_mappings
FROM swimlanes
WHERE id = $1
`

func (q *Queries) GetSwimlaneConfig(ctx context.Context, id uuid.UUID) (Swimlane, error) {
	row := q.db.QueryRowContext(ctx, getSwimlaneConfig, id)
	var i Swimlane
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.Name,
		&i.WipLimit,
		&i.Order,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SourceType,
		&i.CustomFieldID,
		&i.ValueMappings,
	)
	return i, err
}

const getSwimlanesWithConfig = `-- name: GetSwimlanesWithConfig :many
SELECT id, board_id, name, wip_limit, "order", created_at, updated_at, source_type, custom_field_id, value_mappings
FROM swimlanes
WHERE board_id = $1
ORDER BY "order"
`

func (q *Queries) GetSwimlanesWithConfig(ctx context.Context, boardID uuid.UUID) ([]Swimlane, error) {
	rows, err := q.db.QueryContext(ctx, getSwimlanesWithConfig, boardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Swimlane{}
	for rows.Next() {
		var i Swimlane
		if err := rows.Scan(
			&i.ID,
			&i.BoardID,
			&i.Name,
			&i.WipLimit,
			&i.Order,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SourceType,
			&i.CustomFieldID,
			&i.ValueMappings,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSwimlaneConfig = `-- name: UpdateSwimlaneConfig :one

UPDATE swimlanes
SET source_type    = $2,
    custom_field_id = $3,
    value_mappings = $4,
    updated_at     = NOW()
WHERE id = $1
RETURNING id, board_id, name, wip_limit, "order", created_at, updated_at, source_type, custom_field_id, value_mappings
`

type UpdateSwimlaneConfigParams struct {
	ID            uuid.UUID             `json:"id"`
	SourceType    sql.NullString        `json:"source_type"`
	CustomFieldID uuid.NullUUID         `json:"custom_field_id"`
	ValueMappings pqtype.NullRawMessage `json:"value_mappings"`
}

// Swimlane configuration for Kanban boards
func (q *Queries) UpdateSwimlaneConfig(ctx context.Context, arg UpdateSwimlaneConfigParams) (Swimlane, error) {
	row := q.db.QueryRowContext(ctx, updateSwimlaneConfig,
		arg.ID,
		arg.SourceType,
		arg.CustomFieldID,
		arg.ValueMappings,
	)
	var i Swimlane
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.Name,
		&i.WipLimit,
		&i.Order,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SourceType,
		&i.CustomFieldID,
		&i.ValueMappings,
	)
	return i, err
}
