// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tags.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const addTagToTask = `-- name: AddTagToTask :exec
INSERT INTO task_tags (task_id, tag_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddTagToTaskParams struct {
	TaskID uuid.UUID `json:"task_id"`
	TagID  uuid.UUID `json:"tag_id"`
}

func (q *Queries) AddTagToTask(ctx context.Context, arg AddTagToTaskParams) error {
	_, err := q.db.ExecContext(ctx, addTagToTask, arg.TaskID, arg.TagID)
	return err
}

const countTasksWithTag = `-- name: CountTasksWithTag :one
SELECT COUNT(*)::int AS count
FROM task_tags
WHERE tag_id = $1
`

func (q *Queries) CountTasksWithTag(ctx context.Context, tagID uuid.UUID) (int32, error) {
	row := q.db.QueryRowContext(ctx, countTasksWithTag, tagID)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const createTag = `-- name: CreateTag :one
INSERT INTO tags (board_id, name)
VALUES ($1, $2)
RETURNING id, board_id, name, created_at
`

type CreateTagParams struct {
	BoardID uuid.UUID `json:"board_id"`
	Name    string    `json:"name"`
}

func (q *Queries) CreateTag(ctx context.Context, arg CreateTagParams) (Tag, error) {
	row := q.db.QueryRowContext(ctx, createTag, arg.BoardID, arg.Name)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTag = `-- name: DeleteTag :exec
DELETE FROM tags WHERE id = $1
`

func (q *Queries) DeleteTag(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteTag, id)
	return err
}

const getTagByBoardAndName = `-- name: GetTagByBoardAndName :one
SELECT id, board_id, name, created_at
FROM tags
WHERE board_id = $1 AND name = $2
`

type GetTagByBoardAndNameParams struct {
	BoardID uuid.UUID `json:"board_id"`
	Name    string    `json:"name"`
}

func (q *Queries) GetTagByBoardAndName(ctx context.Context, arg GetTagByBoardAndNameParams) (Tag, error) {
	row := q.db.QueryRowContext(ctx, getTagByBoardAndName, arg.BoardID, arg.Name)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getTagByID = `-- name: GetTagByID :one
SELECT id, board_id, name, created_at
FROM tags
WHERE id = $1
`

func (q *Queries) GetTagByID(ctx context.Context, id uuid.UUID) (Tag, error) {
	row := q.db.QueryRowContext(ctx, getTagByID, id)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const listTagsByBoard = `-- name: ListTagsByBoard :many

SELECT id, board_id, name, created_at
FROM tags
WHERE board_id = $1
ORDER BY name
`

// Tags for tasks within a board
func (q *Queries) ListTagsByBoard(ctx context.Context, boardID uuid.UUID) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, listTagsByBoard, boardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tag{}
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.BoardID,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagsByTaskIDs = `-- name: ListTagsByTaskIDs :many
SELECT tt.task_id, t.id, t.board_id, t.name
FROM tags t
JOIN task_tags tt ON tt.tag_id = t.id
WHERE tt.task_id = ANY($1::uuid[])
ORDER BY t.name
`

type ListTagsByTaskIDsRow struct {
	TaskID  uuid.UUID `json:"task_id"`
	ID      uuid.UUID `json:"id"`
	BoardID uuid.UUID `json:"board_id"`
	Name    string    `json:"name"`
}

func (q *Queries) ListTagsByTaskIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]ListTagsByTaskIDsRow, error) {
	rows, err := q.db.QueryContext(ctx, listTagsByTaskIDs, pq.Array(dollar_1))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTagsByTaskIDsRow{}
	for rows.Next() {
		var i ListTagsByTaskIDsRow
		if err := rows.Scan(
			&i.TaskID,
			&i.ID,
			&i.BoardID,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskTags = `-- name: ListTaskTags :many

SELECT t.id, t.board_id, t.name, t.created_at
FROM tags t
JOIN task_tags tt ON tt.tag_id = t.id
WHERE tt.task_id = $1
ORDER BY t.name
`

// Task-tag assignments
func (q *Queries) ListTaskTags(ctx context.Context, taskID uuid.UUID) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, listTaskTags, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tag{}
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.BoardID,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeAllTagsFromTask = `-- name: RemoveAllTagsFromTask :exec
DELETE FROM task_tags
WHERE task_id = $1
`

func (q *Queries) RemoveAllTagsFromTask(ctx context.Context, taskID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, removeAllTagsFromTask, taskID)
	return err
}

const removeTagFromTask = `-- name: RemoveTagFromTask :exec
DELETE FROM task_tags
WHERE task_id = $1 AND tag_id = $2
`

type RemoveTagFromTaskParams struct {
	TaskID uuid.UUID `json:"task_id"`
	TagID  uuid.UUID `json:"tag_id"`
}

func (q *Queries) RemoveTagFromTask(ctx context.Context, arg RemoveTagFromTaskParams) error {
	_, err := q.db.ExecContext(ctx, removeTagFromTask, arg.TaskID, arg.TagID)
	return err
}
