// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tasks.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const addTaskDependency = `-- name: AddTaskDependency :one

INSERT INTO task_dependencies (task_id, depends_on_task_id, dependency_type)
VALUES ($1, $2, $3)
RETURNING id, task_id, depends_on_task_id, dependency_type
`

type AddTaskDependencyParams struct {
	TaskID          uuid.UUID `json:"task_id"`
	DependsOnTaskID uuid.UUID `json:"depends_on_task_id"`
	DependencyType  string    `json:"dependency_type"`
}

// Dependencies
func (q *Queries) AddTaskDependency(ctx context.Context, arg AddTaskDependencyParams) (TaskDependency, error) {
	row := q.db.QueryRowContext(ctx, addTaskDependency, arg.TaskID, arg.DependsOnTaskID, arg.DependencyType)
	var i TaskDependency
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.DependsOnTaskID,
		&i.DependencyType,
	)
	return i, err
}

const assignColumnToTask = `-- name: AssignColumnToTask :exec
UPDATE tasks SET column_id = $2 WHERE id = $1
`

type AssignColumnToTaskParams struct {
	ID       uuid.UUID     `json:"id"`
	ColumnID uuid.NullUUID `json:"column_id"`
}

func (q *Queries) AssignColumnToTask(ctx context.Context, arg AssignColumnToTaskParams) error {
	_, err := q.db.ExecContext(ctx, assignColumnToTask, arg.ID, arg.ColumnID)
	return err
}

const clearColumnFromTask = `-- name: ClearColumnFromTask :exec
UPDATE tasks SET column_id = NULL WHERE id = $1
`

func (q *Queries) ClearColumnFromTask(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, clearColumnFromTask, id)
	return err
}

const createTask = `-- name: CreateTask :one

INSERT INTO tasks (key, project_id, owner_id, executor_id, name, description, deadline, column_id, swimlane_id, priority, estimation, board_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, key, project_id, owner_id, executor_id, name, description, deadline, column_id, swimlane_id, deleted_at, created_at, priority, estimation, board_id
`

type CreateTaskParams struct {
	Key         string         `json:"key"`
	ProjectID   uuid.UUID      `json:"project_id"`
	OwnerID     uuid.UUID      `json:"owner_id"`
	ExecutorID  uuid.NullUUID  `json:"executor_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Deadline    sql.NullTime   `json:"deadline"`
	ColumnID    uuid.NullUUID  `json:"column_id"`
	SwimlaneID  uuid.NullUUID  `json:"swimlane_id"`
	Priority    sql.NullString `json:"priority"`
	Estimation  sql.NullString `json:"estimation"`
	BoardID     uuid.UUID      `json:"board_id"`
}

// Tasks basic CRUD
func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, createTask,
		arg.Key,
		arg.ProjectID,
		arg.OwnerID,
		arg.ExecutorID,
		arg.Name,
		arg.Description,
		arg.Deadline,
		arg.ColumnID,
		arg.SwimlaneID,
		arg.Priority,
		arg.Estimation,
		arg.BoardID,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.ProjectID,
		&i.OwnerID,
		&i.ExecutorID,
		&i.Name,
		&i.Description,
		&i.Deadline,
		&i.ColumnID,
		&i.SwimlaneID,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.Priority,
		&i.Estimation,
		&i.BoardID,
	)
	return i, err
}

const deleteTaskFieldValue = `-- name: DeleteTaskFieldValue :exec
DELETE FROM task_field_values
WHERE task_id = $1 AND field_id = $2
`

type DeleteTaskFieldValueParams struct {
	TaskID  uuid.UUID `json:"task_id"`
	FieldID uuid.UUID `json:"field_id"`
}

func (q *Queries) DeleteTaskFieldValue(ctx context.Context, arg DeleteTaskFieldValueParams) error {
	_, err := q.db.ExecContext(ctx, deleteTaskFieldValue, arg.TaskID, arg.FieldID)
	return err
}

const getTaskByID = `-- name: GetTaskByID :one
SELECT t.id, t.key, t.project_id, t.owner_id, t.executor_id, t.name, t.description,
       t.deadline, t.column_id, t.swimlane_id, t.deleted_at, t.created_at,
       t.priority, t.estimation, t.board_id,
       c.name AS column_name, c.system_type AS column_system_type,
       m_owner.user_id AS owner_user_id,
       m_exec.user_id AS executor_user_id
FROM tasks t
LEFT JOIN columns c ON t.column_id = c.id
JOIN members m_owner ON m_owner.id = t.owner_id
LEFT JOIN members m_exec ON m_exec.id = t.executor_id
WHERE t.id = $1
`

type GetTaskByIDRow struct {
	ID               uuid.UUID      `json:"id"`
	Key              string         `json:"key"`
	ProjectID        uuid.UUID      `json:"project_id"`
	OwnerID          uuid.UUID      `json:"owner_id"`
	ExecutorID       uuid.NullUUID  `json:"executor_id"`
	Name             string         `json:"name"`
	Description      sql.NullString `json:"description"`
	Deadline         sql.NullTime   `json:"deadline"`
	ColumnID         uuid.NullUUID  `json:"column_id"`
	SwimlaneID       uuid.NullUUID  `json:"swimlane_id"`
	DeletedAt        sql.NullTime   `json:"deleted_at"`
	CreatedAt        time.Time      `json:"created_at"`
	Priority         sql.NullString `json:"priority"`
	Estimation       sql.NullString `json:"estimation"`
	BoardID          uuid.UUID      `json:"board_id"`
	ColumnName       sql.NullString `json:"column_name"`
	ColumnSystemType sql.NullString `json:"column_system_type"`
	OwnerUserID      uuid.UUID      `json:"owner_user_id"`
	ExecutorUserID   uuid.NullUUID  `json:"executor_user_id"`
}

func (q *Queries) GetTaskByID(ctx context.Context, id uuid.UUID) (GetTaskByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getTaskByID, id)
	var i GetTaskByIDRow
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.ProjectID,
		&i.OwnerID,
		&i.ExecutorID,
		&i.Name,
		&i.Description,
		&i.Deadline,
		&i.ColumnID,
		&i.SwimlaneID,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.Priority,
		&i.Estimation,
		&i.BoardID,
		&i.ColumnName,
		&i.ColumnSystemType,
		&i.OwnerUserID,
		&i.ExecutorUserID,
	)
	return i, err
}

const getTaskDependencyByID = `-- name: GetTaskDependencyByID :one
SELECT id, task_id, depends_on_task_id, dependency_type
FROM task_dependencies
WHERE id = $1
`

func (q *Queries) GetTaskDependencyByID(ctx context.Context, id uuid.UUID) (TaskDependency, error) {
	row := q.db.QueryRowContext(ctx, getTaskDependencyByID, id)
	var i TaskDependency
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.DependsOnTaskID,
		&i.DependencyType,
	)
	return i, err
}

const getTaskFieldValues = `-- name: GetTaskFieldValues :many
SELECT task_id, field_id, value_text, value_number, value_datetime, value_json
FROM task_field_values
WHERE task_id = $1
`

func (q *Queries) GetTaskFieldValues(ctx context.Context, taskID uuid.UUID) ([]TaskFieldValue, error) {
	rows, err := q.db.QueryContext(ctx, getTaskFieldValues, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskFieldValue{}
	for rows.Next() {
		var i TaskFieldValue
		if err := rows.Scan(
			&i.TaskID,
			&i.FieldID,
			&i.ValueText,
			&i.ValueNumber,
			&i.ValueDatetime,
			&i.ValueJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectTaskKeys = `-- name: ListProjectTaskKeys :many
SELECT key
FROM tasks
WHERE project_id = $1
`

func (q *Queries) ListProjectTaskKeys(ctx context.Context, projectID uuid.UUID) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listProjectTaskKeys, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var key string
		if err := rows.Scan(&key); err != nil {
			return nil, err
		}
		items = append(items, key)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectTasks = `-- name: ListProjectTasks :many
SELECT t.id, t.key, t.project_id, t.owner_id, t.executor_id, t.name, t.description,
       t.deadline, t.column_id, t.swimlane_id, t.deleted_at, t.created_at,
       t.priority, t.estimation, t.board_id,
       c.name AS column_name, c.system_type AS column_system_type,
       m_owner.user_id AS owner_user_id,
       m_exec.user_id AS executor_user_id
FROM tasks t
LEFT JOIN columns c ON t.column_id = c.id
JOIN members m_owner ON m_owner.id = t.owner_id
LEFT JOIN members m_exec ON m_exec.id = t.executor_id
WHERE t.project_id = $1
  AND t.deleted_at IS NULL
ORDER BY t.created_at DESC
`

type ListProjectTasksRow struct {
	ID               uuid.UUID      `json:"id"`
	Key              string         `json:"key"`
	ProjectID        uuid.UUID      `json:"project_id"`
	OwnerID          uuid.UUID      `json:"owner_id"`
	ExecutorID       uuid.NullUUID  `json:"executor_id"`
	Name             string         `json:"name"`
	Description      sql.NullString `json:"description"`
	Deadline         sql.NullTime   `json:"deadline"`
	ColumnID         uuid.NullUUID  `json:"column_id"`
	SwimlaneID       uuid.NullUUID  `json:"swimlane_id"`
	DeletedAt        sql.NullTime   `json:"deleted_at"`
	CreatedAt        time.Time      `json:"created_at"`
	Priority         sql.NullString `json:"priority"`
	Estimation       sql.NullString `json:"estimation"`
	BoardID          uuid.UUID      `json:"board_id"`
	ColumnName       sql.NullString `json:"column_name"`
	ColumnSystemType sql.NullString `json:"column_system_type"`
	OwnerUserID      uuid.UUID      `json:"owner_user_id"`
	ExecutorUserID   uuid.NullUUID  `json:"executor_user_id"`
}

func (q *Queries) ListProjectTasks(ctx context.Context, projectID uuid.UUID) ([]ListProjectTasksRow, error) {
	rows, err := q.db.QueryContext(ctx, listProjectTasks, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectTasksRow{}
	for rows.Next() {
		var i ListProjectTasksRow
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.ProjectID,
			&i.OwnerID,
			&i.ExecutorID,
			&i.Name,
			&i.Description,
			&i.Deadline,
			&i.ColumnID,
			&i.SwimlaneID,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.Priority,
			&i.Estimation,
			&i.BoardID,
			&i.ColumnName,
			&i.ColumnSystemType,
			&i.OwnerUserID,
			&i.ExecutorUserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSprintTasksWithoutColumn = `-- name: ListSprintTasksWithoutColumn :many
SELECT t.id, t.board_id
FROM tasks t
JOIN sprint_tasks st ON st.task_id = t.id
WHERE st.sprint_id = $1 AND t.column_id IS NULL
`

type ListSprintTasksWithoutColumnRow struct {
	ID      uuid.UUID `json:"id"`
	BoardID uuid.UUID `json:"board_id"`
}

func (q *Queries) ListSprintTasksWithoutColumn(ctx context.Context, sprintID uuid.UUID) ([]ListSprintTasksWithoutColumnRow, error) {
	rows, err := q.db.QueryContext(ctx, listSprintTasksWithoutColumn, sprintID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSprintTasksWithoutColumnRow{}
	for rows.Next() {
		var i ListSprintTasksWithoutColumnRow
		if err := rows.Scan(&i.ID, &i.BoardID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskDependants = `-- name: ListTaskDependants :many
SELECT id, task_id, depends_on_task_id, dependency_type
FROM task_dependencies
WHERE depends_on_task_id = $1
`

func (q *Queries) ListTaskDependants(ctx context.Context, dependsOnTaskID uuid.UUID) ([]TaskDependency, error) {
	rows, err := q.db.QueryContext(ctx, listTaskDependants, dependsOnTaskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskDependency{}
	for rows.Next() {
		var i TaskDependency
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.DependsOnTaskID,
			&i.DependencyType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskDependencies = `-- name: ListTaskDependencies :many
SELECT id, task_id, depends_on_task_id, dependency_type
FROM task_dependencies
WHERE task_id = $1
`

func (q *Queries) ListTaskDependencies(ctx context.Context, taskID uuid.UUID) ([]TaskDependency, error) {
	rows, err := q.db.QueryContext(ctx, listTaskDependencies, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskDependency{}
	for rows.Next() {
		var i TaskDependency
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.DependsOnTaskID,
			&i.DependencyType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeInverseDependency = `-- name: RemoveInverseDependency :exec
DELETE FROM task_dependencies
WHERE task_id = $1 AND depends_on_task_id = $2
`

type RemoveInverseDependencyParams struct {
	TaskID          uuid.UUID `json:"task_id"`
	DependsOnTaskID uuid.UUID `json:"depends_on_task_id"`
}

func (q *Queries) RemoveInverseDependency(ctx context.Context, arg RemoveInverseDependencyParams) error {
	_, err := q.db.ExecContext(ctx, removeInverseDependency, arg.TaskID, arg.DependsOnTaskID)
	return err
}

const removeTaskDependency = `-- name: RemoveTaskDependency :exec
DELETE FROM task_dependencies
WHERE id = $1
`

func (q *Queries) RemoveTaskDependency(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, removeTaskDependency, id)
	return err
}

const searchTasks = `-- name: SearchTasks :many
SELECT DISTINCT t.id, t.key, t.project_id, t.owner_id, t.executor_id, t.name, t.description,
       t.deadline, t.column_id, t.swimlane_id, t.deleted_at, t.created_at,
       t.priority, t.estimation, t.board_id,
       c.name AS column_name, c.system_type AS column_system_type,
       m_owner.user_id AS owner_user_id,
       m_exec.user_id AS executor_user_id
FROM tasks t
LEFT JOIN columns c ON t.column_id = c.id
JOIN members m_owner ON m_owner.id = t.owner_id
LEFT JOIN members m_exec ON m_exec.id = t.executor_id
LEFT JOIN task_watchers tw ON tw.task_id = t.id
LEFT JOIN members m_watch ON m_watch.id = tw.member_id
WHERE (m_owner.user_id = $1 OR m_exec.user_id = $1 OR m_watch.user_id = $1)
  AND ($2::uuid IS NULL OR t.project_id = $2)
  AND ($3::uuid IS NULL OR t.column_id = $3)
  AND t.deleted_at IS NULL
ORDER BY t.created_at DESC
`

type SearchTasksParams struct {
	UserID    uuid.UUID     `json:"user_id"`
	ProjectID uuid.NullUUID `json:"project_id"`
	ColumnID  uuid.NullUUID `json:"column_id"`
}

type SearchTasksRow struct {
	ID               uuid.UUID      `json:"id"`
	Key              string         `json:"key"`
	ProjectID        uuid.UUID      `json:"project_id"`
	OwnerID          uuid.UUID      `json:"owner_id"`
	ExecutorID       uuid.NullUUID  `json:"executor_id"`
	Name             string         `json:"name"`
	Description      sql.NullString `json:"description"`
	Deadline         sql.NullTime   `json:"deadline"`
	ColumnID         uuid.NullUUID  `json:"column_id"`
	SwimlaneID       uuid.NullUUID  `json:"swimlane_id"`
	DeletedAt        sql.NullTime   `json:"deleted_at"`
	CreatedAt        time.Time      `json:"created_at"`
	Priority         sql.NullString `json:"priority"`
	Estimation       sql.NullString `json:"estimation"`
	BoardID          uuid.UUID      `json:"board_id"`
	ColumnName       sql.NullString `json:"column_name"`
	ColumnSystemType sql.NullString `json:"column_system_type"`
	OwnerUserID      uuid.UUID      `json:"owner_user_id"`
	ExecutorUserID   uuid.NullUUID  `json:"executor_user_id"`
}

func (q *Queries) SearchTasks(ctx context.Context, arg SearchTasksParams) ([]SearchTasksRow, error) {
	rows, err := q.db.QueryContext(ctx, searchTasks, arg.UserID, arg.ProjectID, arg.ColumnID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchTasksRow{}
	for rows.Next() {
		var i SearchTasksRow
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.ProjectID,
			&i.OwnerID,
			&i.ExecutorID,
			&i.Name,
			&i.Description,
			&i.Deadline,
			&i.ColumnID,
			&i.SwimlaneID,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.Priority,
			&i.Estimation,
			&i.BoardID,
			&i.ColumnName,
			&i.ColumnSystemType,
			&i.OwnerUserID,
			&i.ExecutorUserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteTask = `-- name: SoftDeleteTask :exec
UPDATE tasks
SET deleted_at = NOW()
WHERE id = $1
`

func (q *Queries) SoftDeleteTask(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, softDeleteTask, id)
	return err
}

const updateTask = `-- name: UpdateTask :one
UPDATE tasks
SET name        = COALESCE($1, name),
    description = $2,
    deadline    = $3,
    executor_id = $4,
    column_id   = COALESCE($5, column_id),
    swimlane_id = $6,
    priority    = $7,
    estimation  = $8
WHERE id = $9
RETURNING id, key, project_id, owner_id, executor_id, name, description, deadline, column_id, swimlane_id, deleted_at, created_at, priority, estimation, board_id
`

type UpdateTaskParams struct {
	Name        sql.NullString `json:"name"`
	Description sql.NullString `json:"description"`
	Deadline    sql.NullTime   `json:"deadline"`
	ExecutorID  uuid.NullUUID  `json:"executor_id"`
	ColumnID    uuid.NullUUID  `json:"column_id"`
	SwimlaneID  uuid.NullUUID  `json:"swimlane_id"`
	Priority    sql.NullString `json:"priority"`
	Estimation  sql.NullString `json:"estimation"`
	ID          uuid.UUID      `json:"id"`
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, updateTask,
		arg.Name,
		arg.Description,
		arg.Deadline,
		arg.ExecutorID,
		arg.ColumnID,
		arg.SwimlaneID,
		arg.Priority,
		arg.Estimation,
		arg.ID,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.ProjectID,
		&i.OwnerID,
		&i.ExecutorID,
		&i.Name,
		&i.Description,
		&i.Deadline,
		&i.ColumnID,
		&i.SwimlaneID,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.Priority,
		&i.Estimation,
		&i.BoardID,
	)
	return i, err
}

const upsertTaskFieldValue = `-- name: UpsertTaskFieldValue :exec

INSERT INTO task_field_values (task_id, field_id, value_text, value_number, value_datetime, value_json)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (task_id, field_id) DO UPDATE
SET value_text = EXCLUDED.value_text,
    value_number = EXCLUDED.value_number,
    value_datetime = EXCLUDED.value_datetime,
    value_json = EXCLUDED.value_json
`

type UpsertTaskFieldValueParams struct {
	TaskID        uuid.UUID             `json:"task_id"`
	FieldID       uuid.UUID             `json:"field_id"`
	ValueText     sql.NullString        `json:"value_text"`
	ValueNumber   sql.NullString        `json:"value_number"`
	ValueDatetime sql.NullTime          `json:"value_datetime"`
	ValueJson     pqtype.NullRawMessage `json:"value_json"`
}

// Task field values
func (q *Queries) UpsertTaskFieldValue(ctx context.Context, arg UpsertTaskFieldValueParams) error {
	_, err := q.db.ExecContext(ctx, upsertTaskFieldValue,
		arg.TaskID,
		arg.FieldID,
		arg.ValueText,
		arg.ValueNumber,
		arg.ValueDatetime,
		arg.ValueJson,
	)
	return err
}
