// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tasks.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const addTaskDependency = `-- name: AddTaskDependency :one

INSERT INTO task_dependencies (task_id, depends_on_task_id, dependency_type)
VALUES ($1, $2, $3)
RETURNING id, task_id, depends_on_task_id, dependency_type
`

type AddTaskDependencyParams struct {
	TaskID          uuid.UUID `json:"task_id"`
	DependsOnTaskID uuid.UUID `json:"depends_on_task_id"`
	DependencyType  string    `json:"dependency_type"`
}

// Dependencies
func (q *Queries) AddTaskDependency(ctx context.Context, arg AddTaskDependencyParams) (TaskDependency, error) {
	row := q.db.QueryRowContext(ctx, addTaskDependency, arg.TaskID, arg.DependsOnTaskID, arg.DependencyType)
	var i TaskDependency
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.DependsOnTaskID,
		&i.DependencyType,
	)
	return i, err
}

const createTask = `-- name: CreateTask :one

INSERT INTO tasks (key, project_id, owner_id, executor_id, name, description, deadline, column_id, swimlane_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, key, project_id, owner_id, executor_id, name, description, deadline, column_id, swimlane_id, status_type, deleted_at, delete_reason, created_at
`

type CreateTaskParams struct {
	Key         string         `json:"key"`
	ProjectID   uuid.UUID      `json:"project_id"`
	OwnerID     uuid.UUID      `json:"owner_id"`
	ExecutorID  uuid.NullUUID  `json:"executor_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Deadline    sql.NullTime   `json:"deadline"`
	ColumnID    uuid.UUID      `json:"column_id"`
	SwimlaneID  uuid.NullUUID  `json:"swimlane_id"`
}

// Tasks basic CRUD
func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, createTask,
		arg.Key,
		arg.ProjectID,
		arg.OwnerID,
		arg.ExecutorID,
		arg.Name,
		arg.Description,
		arg.Deadline,
		arg.ColumnID,
		arg.SwimlaneID,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.ProjectID,
		&i.OwnerID,
		&i.ExecutorID,
		&i.Name,
		&i.Description,
		&i.Deadline,
		&i.ColumnID,
		&i.SwimlaneID,
		&i.StatusType,
		&i.DeletedAt,
		&i.DeleteReason,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTaskFieldValue = `-- name: DeleteTaskFieldValue :exec
DELETE FROM task_field_values
WHERE task_id = $1 AND field_id = $2
`

type DeleteTaskFieldValueParams struct {
	TaskID  uuid.UUID `json:"task_id"`
	FieldID uuid.UUID `json:"field_id"`
}

func (q *Queries) DeleteTaskFieldValue(ctx context.Context, arg DeleteTaskFieldValueParams) error {
	_, err := q.db.ExecContext(ctx, deleteTaskFieldValue, arg.TaskID, arg.FieldID)
	return err
}

const getTaskByID = `-- name: GetTaskByID :one
SELECT id, key, project_id, owner_id, executor_id, name, description, deadline, column_id, swimlane_id, status_type, deleted_at, delete_reason, created_at
FROM tasks
WHERE id = $1
`

func (q *Queries) GetTaskByID(ctx context.Context, id uuid.UUID) (Task, error) {
	row := q.db.QueryRowContext(ctx, getTaskByID, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.ProjectID,
		&i.OwnerID,
		&i.ExecutorID,
		&i.Name,
		&i.Description,
		&i.Deadline,
		&i.ColumnID,
		&i.SwimlaneID,
		&i.StatusType,
		&i.DeletedAt,
		&i.DeleteReason,
		&i.CreatedAt,
	)
	return i, err
}

const getTaskFieldValues = `-- name: GetTaskFieldValues :many
SELECT task_id, field_id, value_text, value_number, value_datetime, value_json
FROM task_field_values
WHERE task_id = $1
`

func (q *Queries) GetTaskFieldValues(ctx context.Context, taskID uuid.UUID) ([]TaskFieldValue, error) {
	rows, err := q.db.QueryContext(ctx, getTaskFieldValues, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskFieldValue{}
	for rows.Next() {
		var i TaskFieldValue
		if err := rows.Scan(
			&i.TaskID,
			&i.FieldID,
			&i.ValueText,
			&i.ValueNumber,
			&i.ValueDatetime,
			&i.ValueJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectTaskKeys = `-- name: ListProjectTaskKeys :many
SELECT key
FROM tasks
WHERE project_id = $1
`

func (q *Queries) ListProjectTaskKeys(ctx context.Context, projectID uuid.UUID) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listProjectTaskKeys, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var key string
		if err := rows.Scan(&key); err != nil {
			return nil, err
		}
		items = append(items, key)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectTasks = `-- name: ListProjectTasks :many
SELECT id, key, project_id, owner_id, executor_id, name, description, deadline, column_id, swimlane_id, status_type, deleted_at, delete_reason, created_at
FROM tasks
WHERE project_id = $1
  AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListProjectTasks(ctx context.Context, projectID uuid.UUID) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listProjectTasks, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.ProjectID,
			&i.OwnerID,
			&i.ExecutorID,
			&i.Name,
			&i.Description,
			&i.Deadline,
			&i.ColumnID,
			&i.SwimlaneID,
			&i.StatusType,
			&i.DeletedAt,
			&i.DeleteReason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskDependants = `-- name: ListTaskDependants :many
SELECT id, task_id, depends_on_task_id, dependency_type
FROM task_dependencies
WHERE depends_on_task_id = $1
`

func (q *Queries) ListTaskDependants(ctx context.Context, dependsOnTaskID uuid.UUID) ([]TaskDependency, error) {
	rows, err := q.db.QueryContext(ctx, listTaskDependants, dependsOnTaskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskDependency{}
	for rows.Next() {
		var i TaskDependency
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.DependsOnTaskID,
			&i.DependencyType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskDependencies = `-- name: ListTaskDependencies :many
SELECT id, task_id, depends_on_task_id, dependency_type
FROM task_dependencies
WHERE task_id = $1
`

func (q *Queries) ListTaskDependencies(ctx context.Context, taskID uuid.UUID) ([]TaskDependency, error) {
	rows, err := q.db.QueryContext(ctx, listTaskDependencies, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskDependency{}
	for rows.Next() {
		var i TaskDependency
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.DependsOnTaskID,
			&i.DependencyType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeTaskDependency = `-- name: RemoveTaskDependency :exec
DELETE FROM task_dependencies
WHERE id = $1
`

func (q *Queries) RemoveTaskDependency(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, removeTaskDependency, id)
	return err
}

const searchTasks = `-- name: SearchTasks :many
SELECT id, key, project_id, owner_id, executor_id, name, description, deadline, column_id, swimlane_id, status_type, deleted_at, delete_reason, created_at
FROM tasks
WHERE ($1::uuid IS NULL OR project_id = $1)
  AND ($2::uuid IS NULL OR owner_id = $2)
  AND ($3::uuid IS NULL OR executor_id = $3)
  AND ($4::uuid IS NULL OR column_id = $4)
  AND deleted_at IS NULL
ORDER BY created_at DESC
`

type SearchTasksParams struct {
	Column1 uuid.UUID `json:"column_1"`
	Column2 uuid.UUID `json:"column_2"`
	Column3 uuid.UUID `json:"column_3"`
	Column4 uuid.UUID `json:"column_4"`
}

func (q *Queries) SearchTasks(ctx context.Context, arg SearchTasksParams) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, searchTasks,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.ProjectID,
			&i.OwnerID,
			&i.ExecutorID,
			&i.Name,
			&i.Description,
			&i.Deadline,
			&i.ColumnID,
			&i.SwimlaneID,
			&i.StatusType,
			&i.DeletedAt,
			&i.DeleteReason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteTask = `-- name: SoftDeleteTask :exec
UPDATE tasks
SET deleted_at   = NOW(),
    delete_reason = $2
WHERE id = $1
`

type SoftDeleteTaskParams struct {
	ID           uuid.UUID      `json:"id"`
	DeleteReason sql.NullString `json:"delete_reason"`
}

func (q *Queries) SoftDeleteTask(ctx context.Context, arg SoftDeleteTaskParams) error {
	_, err := q.db.ExecContext(ctx, softDeleteTask, arg.ID, arg.DeleteReason)
	return err
}

const updateTask = `-- name: UpdateTask :one
UPDATE tasks
SET name        = COALESCE($1, name),
    description = COALESCE($2, description),
    deadline    = COALESCE($3, deadline),
    executor_id = COALESCE($4, executor_id),
    column_id   = COALESCE($5, column_id),
    swimlane_id = COALESCE($6, swimlane_id)
WHERE id = $7
RETURNING id, key, project_id, owner_id, executor_id, name, description, deadline, column_id, swimlane_id, status_type, deleted_at, delete_reason, created_at
`

type UpdateTaskParams struct {
	Name        sql.NullString `json:"name"`
	Description sql.NullString `json:"description"`
	Deadline    sql.NullTime   `json:"deadline"`
	ExecutorID  uuid.NullUUID  `json:"executor_id"`
	ColumnID    uuid.NullUUID  `json:"column_id"`
	SwimlaneID  uuid.NullUUID  `json:"swimlane_id"`
	ID          uuid.UUID      `json:"id"`
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, updateTask,
		arg.Name,
		arg.Description,
		arg.Deadline,
		arg.ExecutorID,
		arg.ColumnID,
		arg.SwimlaneID,
		arg.ID,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.ProjectID,
		&i.OwnerID,
		&i.ExecutorID,
		&i.Name,
		&i.Description,
		&i.Deadline,
		&i.ColumnID,
		&i.SwimlaneID,
		&i.StatusType,
		&i.DeletedAt,
		&i.DeleteReason,
		&i.CreatedAt,
	)
	return i, err
}

const upsertTaskFieldValue = `-- name: UpsertTaskFieldValue :exec

INSERT INTO task_field_values (task_id, field_id, value_text, value_number, value_datetime, value_json)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (task_id, field_id) DO UPDATE
SET value_text = EXCLUDED.value_text,
    value_number = EXCLUDED.value_number,
    value_datetime = EXCLUDED.value_datetime,
    value_json = EXCLUDED.value_json
`

type UpsertTaskFieldValueParams struct {
	TaskID        uuid.UUID             `json:"task_id"`
	FieldID       uuid.UUID             `json:"field_id"`
	ValueText     sql.NullString        `json:"value_text"`
	ValueNumber   sql.NullString        `json:"value_number"`
	ValueDatetime sql.NullTime          `json:"value_datetime"`
	ValueJson     pqtype.NullRawMessage `json:"value_json"`
}

// Task field values
func (q *Queries) UpsertTaskFieldValue(ctx context.Context, arg UpsertTaskFieldValueParams) error {
	_, err := q.db.ExecContext(ctx, upsertTaskFieldValue,
		arg.TaskID,
		arg.FieldID,
		arg.ValueText,
		arg.ValueNumber,
		arg.ValueDatetime,
		arg.ValueJson,
	)
	return err
}
