// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: task_history.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const getCompletedTasksCycleTime = `-- name: GetCompletedTasksCycleTime :many
SELECT
    h.task_id,
    EXTRACT(EPOCH FROM (MAX(h.left_at) - MIN(h.entered_at))) AS cycle_time_seconds,
    MAX(h.left_at) AS completed_at
FROM task_status_history h
JOIN tasks t ON t.id = h.task_id
WHERE t.project_id = $1
  AND h.left_at IS NOT NULL
GROUP BY h.task_id
`

type GetCompletedTasksCycleTimeRow struct {
	TaskID           uuid.UUID   `json:"task_id"`
	CycleTimeSeconds string      `json:"cycle_time_seconds"`
	CompletedAt      interface{} `json:"completed_at"`
}

func (q *Queries) GetCompletedTasksCycleTime(ctx context.Context, projectID uuid.UUID) ([]GetCompletedTasksCycleTimeRow, error) {
	rows, err := q.db.QueryContext(ctx, getCompletedTasksCycleTime, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCompletedTasksCycleTimeRow{}
	for rows.Next() {
		var i GetCompletedTasksCycleTimeRow
		if err := rows.Scan(&i.TaskID, &i.CycleTimeSeconds, &i.CompletedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTaskCycleTimes = `-- name: GetTaskCycleTimes :many
SELECT
    h.task_id,
    EXTRACT(EPOCH FROM (MAX(h.left_at) - MIN(h.entered_at))) AS cycle_time_seconds
FROM task_status_history h
JOIN tasks t ON t.id = h.task_id
WHERE t.project_id = $1
  AND h.left_at IS NOT NULL
GROUP BY h.task_id
`

type GetTaskCycleTimesRow struct {
	TaskID           uuid.UUID `json:"task_id"`
	CycleTimeSeconds string    `json:"cycle_time_seconds"`
}

func (q *Queries) GetTaskCycleTimes(ctx context.Context, projectID uuid.UUID) ([]GetTaskCycleTimesRow, error) {
	rows, err := q.db.QueryContext(ctx, getTaskCycleTimes, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTaskCycleTimesRow{}
	for rows.Next() {
		var i GetTaskCycleTimesRow
		if err := rows.Scan(&i.TaskID, &i.CycleTimeSeconds); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTaskStatusHistory = `-- name: GetTaskStatusHistory :many
SELECT id, task_id, column_id, entered_at, left_at
FROM task_status_history
WHERE task_id = $1
ORDER BY entered_at
`

func (q *Queries) GetTaskStatusHistory(ctx context.Context, taskID uuid.UUID) ([]TaskStatusHistory, error) {
	rows, err := q.db.QueryContext(ctx, getTaskStatusHistory, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskStatusHistory{}
	for rows.Next() {
		var i TaskStatusHistory
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.ColumnID,
			&i.EnteredAt,
			&i.LeftAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordTaskStatusChange = `-- name: RecordTaskStatusChange :one

INSERT INTO task_status_history (task_id, column_id, entered_at, left_at)
VALUES ($1, $2, $3, $4)
RETURNING id, task_id, column_id, entered_at, left_at
`

type RecordTaskStatusChangeParams struct {
	TaskID    uuid.UUID    `json:"task_id"`
	ColumnID  uuid.UUID    `json:"column_id"`
	EnteredAt time.Time    `json:"entered_at"`
	LeftAt    sql.NullTime `json:"left_at"`
}

// Task status history for cycle time analytics
func (q *Queries) RecordTaskStatusChange(ctx context.Context, arg RecordTaskStatusChangeParams) (TaskStatusHistory, error) {
	row := q.db.QueryRowContext(ctx, recordTaskStatusChange,
		arg.TaskID,
		arg.ColumnID,
		arg.EnteredAt,
		arg.LeftAt,
	)
	var i TaskStatusHistory
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.ColumnID,
		&i.EnteredAt,
		&i.LeftAt,
	)
	return i, err
}
