// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: task_watchers.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const addTaskWatcher = `-- name: AddTaskWatcher :exec
INSERT INTO task_watchers (task_id, member_id)
VALUES ($1, $2)
ON CONFLICT (task_id, member_id) DO NOTHING
`

type AddTaskWatcherParams struct {
	TaskID   uuid.UUID `json:"task_id"`
	MemberID uuid.UUID `json:"member_id"`
}

func (q *Queries) AddTaskWatcher(ctx context.Context, arg AddTaskWatcherParams) error {
	_, err := q.db.ExecContext(ctx, addTaskWatcher, arg.TaskID, arg.MemberID)
	return err
}

const listTaskWatchers = `-- name: ListTaskWatchers :many
SELECT task_id, member_id
FROM task_watchers
WHERE task_id = $1
`

func (q *Queries) ListTaskWatchers(ctx context.Context, taskID uuid.UUID) ([]TaskWatcher, error) {
	rows, err := q.db.QueryContext(ctx, listTaskWatchers, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskWatcher{}
	for rows.Next() {
		var i TaskWatcher
		if err := rows.Scan(&i.TaskID, &i.MemberID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeTaskWatcher = `-- name: RemoveTaskWatcher :exec
DELETE FROM task_watchers
WHERE task_id = $1 AND member_id = $2
`

type RemoveTaskWatcherParams struct {
	TaskID   uuid.UUID `json:"task_id"`
	MemberID uuid.UUID `json:"member_id"`
}

func (q *Queries) RemoveTaskWatcher(ctx context.Context, arg RemoveTaskWatcherParams) error {
	_, err := q.db.ExecContext(ctx, removeTaskWatcher, arg.TaskID, arg.MemberID)
	return err
}
