// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: template_params_and_roles.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const countTemplateRolesByTemplateID = `-- name: CountTemplateRolesByTemplateID :one
SELECT COUNT(*)::int AS count FROM template_roles WHERE template_id = $1
`

func (q *Queries) CountTemplateRolesByTemplateID(ctx context.Context, templateID uuid.UUID) (int32, error) {
	row := q.db.QueryRowContext(ctx, countTemplateRolesByTemplateID, templateID)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const createTemplateProjectParam = `-- name: CreateTemplateProjectParam :one
INSERT INTO template_project_params (template_id, name, field_type, is_required, "order", options)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, template_id, name, field_type, is_required, "order", options
`

type CreateTemplateProjectParamParams struct {
	TemplateID uuid.UUID             `json:"template_id"`
	Name       string                `json:"name"`
	FieldType  string                `json:"field_type"`
	IsRequired bool                  `json:"is_required"`
	Order      int32                 `json:"order"`
	Options    pqtype.NullRawMessage `json:"options"`
}

func (q *Queries) CreateTemplateProjectParam(ctx context.Context, arg CreateTemplateProjectParamParams) (TemplateProjectParam, error) {
	row := q.db.QueryRowContext(ctx, createTemplateProjectParam,
		arg.TemplateID,
		arg.Name,
		arg.FieldType,
		arg.IsRequired,
		arg.Order,
		arg.Options,
	)
	var i TemplateProjectParam
	err := row.Scan(
		&i.ID,
		&i.TemplateID,
		&i.Name,
		&i.FieldType,
		&i.IsRequired,
		&i.Order,
		&i.Options,
	)
	return i, err
}

const createTemplateRole = `-- name: CreateTemplateRole :one
INSERT INTO template_roles (template_id, name, description, is_default, "order")
VALUES ($1, $2, $3, $4, $5)
RETURNING id, template_id, name, description, is_default, "order"
`

type CreateTemplateRoleParams struct {
	TemplateID  uuid.UUID `json:"template_id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	IsDefault   bool      `json:"is_default"`
	Order       int32     `json:"order"`
}

func (q *Queries) CreateTemplateRole(ctx context.Context, arg CreateTemplateRoleParams) (TemplateRole, error) {
	row := q.db.QueryRowContext(ctx, createTemplateRole,
		arg.TemplateID,
		arg.Name,
		arg.Description,
		arg.IsDefault,
		arg.Order,
	)
	var i TemplateRole
	err := row.Scan(
		&i.ID,
		&i.TemplateID,
		&i.Name,
		&i.Description,
		&i.IsDefault,
		&i.Order,
	)
	return i, err
}

const deleteTemplateProjectParamByID = `-- name: DeleteTemplateProjectParamByID :exec
DELETE FROM template_project_params WHERE id = $1
`

func (q *Queries) DeleteTemplateProjectParamByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteTemplateProjectParamByID, id)
	return err
}

const deleteTemplateRoleByID = `-- name: DeleteTemplateRoleByID :exec
DELETE FROM template_roles WHERE id = $1
`

func (q *Queries) DeleteTemplateRoleByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteTemplateRoleByID, id)
	return err
}

const deleteTemplateRolePermissionsByRoleID = `-- name: DeleteTemplateRolePermissionsByRoleID :exec
DELETE FROM template_role_permissions WHERE role_id = $1
`

func (q *Queries) DeleteTemplateRolePermissionsByRoleID(ctx context.Context, roleID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteTemplateRolePermissionsByRoleID, roleID)
	return err
}

const getTemplateProjectParamByID = `-- name: GetTemplateProjectParamByID :one
SELECT id, template_id, name, field_type, is_required, "order", options
FROM template_project_params
WHERE id = $1
`

func (q *Queries) GetTemplateProjectParamByID(ctx context.Context, id uuid.UUID) (TemplateProjectParam, error) {
	row := q.db.QueryRowContext(ctx, getTemplateProjectParamByID, id)
	var i TemplateProjectParam
	err := row.Scan(
		&i.ID,
		&i.TemplateID,
		&i.Name,
		&i.FieldType,
		&i.IsRequired,
		&i.Order,
		&i.Options,
	)
	return i, err
}

const getTemplateRoleByID = `-- name: GetTemplateRoleByID :one
SELECT id, template_id, name, description, is_default, "order"
FROM template_roles
WHERE id = $1
`

func (q *Queries) GetTemplateRoleByID(ctx context.Context, id uuid.UUID) (TemplateRole, error) {
	row := q.db.QueryRowContext(ctx, getTemplateRoleByID, id)
	var i TemplateRole
	err := row.Scan(
		&i.ID,
		&i.TemplateID,
		&i.Name,
		&i.Description,
		&i.IsDefault,
		&i.Order,
	)
	return i, err
}

const listRefAccessLevels = `-- name: ListRefAccessLevels :many
SELECT key, name, sort_order
FROM ref_access_levels
ORDER BY sort_order ASC
`

func (q *Queries) ListRefAccessLevels(ctx context.Context) ([]RefAccessLevel, error) {
	rows, err := q.db.QueryContext(ctx, listRefAccessLevels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RefAccessLevel{}
	for rows.Next() {
		var i RefAccessLevel
		if err := rows.Scan(&i.Key, &i.Name, &i.SortOrder); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRefPermissionAreas = `-- name: ListRefPermissionAreas :many
SELECT area, project_type, name, description, sort_order
FROM ref_permission_areas
ORDER BY project_type, sort_order ASC
`

func (q *Queries) ListRefPermissionAreas(ctx context.Context) ([]RefPermissionArea, error) {
	rows, err := q.db.QueryContext(ctx, listRefPermissionAreas)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RefPermissionArea{}
	for rows.Next() {
		var i RefPermissionArea
		if err := rows.Scan(
			&i.Area,
			&i.ProjectType,
			&i.Name,
			&i.Description,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRefSystemProjectParams = `-- name: ListRefSystemProjectParams :many

SELECT key, name, field_type, is_required, options, sort_order
FROM ref_system_project_params
ORDER BY sort_order ASC
`

// Reference queries for new tables
func (q *Queries) ListRefSystemProjectParams(ctx context.Context) ([]RefSystemProjectParam, error) {
	rows, err := q.db.QueryContext(ctx, listRefSystemProjectParams)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RefSystemProjectParam{}
	for rows.Next() {
		var i RefSystemProjectParam
		if err := rows.Scan(
			&i.Key,
			&i.Name,
			&i.FieldType,
			&i.IsRequired,
			&i.Options,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTemplateProjectParams = `-- name: ListTemplateProjectParams :many

SELECT id, template_id, name, field_type, is_required, "order", options
FROM template_project_params
WHERE template_id = $1
ORDER BY "order" ASC
`

// Template project params
func (q *Queries) ListTemplateProjectParams(ctx context.Context, templateID uuid.UUID) ([]TemplateProjectParam, error) {
	rows, err := q.db.QueryContext(ctx, listTemplateProjectParams, templateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TemplateProjectParam{}
	for rows.Next() {
		var i TemplateProjectParam
		if err := rows.Scan(
			&i.ID,
			&i.TemplateID,
			&i.Name,
			&i.FieldType,
			&i.IsRequired,
			&i.Order,
			&i.Options,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTemplateRolePermissions = `-- name: ListTemplateRolePermissions :many

SELECT id, role_id, area, access
FROM template_role_permissions
WHERE role_id = $1
`

// Template role permissions
func (q *Queries) ListTemplateRolePermissions(ctx context.Context, roleID uuid.UUID) ([]TemplateRolePermission, error) {
	rows, err := q.db.QueryContext(ctx, listTemplateRolePermissions, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TemplateRolePermission{}
	for rows.Next() {
		var i TemplateRolePermission
		if err := rows.Scan(
			&i.ID,
			&i.RoleID,
			&i.Area,
			&i.Access,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTemplateRoles = `-- name: ListTemplateRoles :many

SELECT id, template_id, name, description, is_default, "order"
FROM template_roles
WHERE template_id = $1
ORDER BY "order" ASC
`

// Template roles
func (q *Queries) ListTemplateRoles(ctx context.Context, templateID uuid.UUID) ([]TemplateRole, error) {
	rows, err := q.db.QueryContext(ctx, listTemplateRoles, templateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TemplateRole{}
	for rows.Next() {
		var i TemplateRole
		if err := rows.Scan(
			&i.ID,
			&i.TemplateID,
			&i.Name,
			&i.Description,
			&i.IsDefault,
			&i.Order,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTemplateProjectParam = `-- name: UpdateTemplateProjectParam :one
UPDATE template_project_params
SET name = $2, is_required = $3, options = $4
WHERE id = $1
RETURNING id, template_id, name, field_type, is_required, "order", options
`

type UpdateTemplateProjectParamParams struct {
	ID         uuid.UUID             `json:"id"`
	Name       string                `json:"name"`
	IsRequired bool                  `json:"is_required"`
	Options    pqtype.NullRawMessage `json:"options"`
}

func (q *Queries) UpdateTemplateProjectParam(ctx context.Context, arg UpdateTemplateProjectParamParams) (TemplateProjectParam, error) {
	row := q.db.QueryRowContext(ctx, updateTemplateProjectParam,
		arg.ID,
		arg.Name,
		arg.IsRequired,
		arg.Options,
	)
	var i TemplateProjectParam
	err := row.Scan(
		&i.ID,
		&i.TemplateID,
		&i.Name,
		&i.FieldType,
		&i.IsRequired,
		&i.Order,
		&i.Options,
	)
	return i, err
}

const updateTemplateProjectParamOrder = `-- name: UpdateTemplateProjectParamOrder :exec
UPDATE template_project_params SET "order" = $2 WHERE id = $1
`

type UpdateTemplateProjectParamOrderParams struct {
	ID    uuid.UUID `json:"id"`
	Order int32     `json:"order"`
}

func (q *Queries) UpdateTemplateProjectParamOrder(ctx context.Context, arg UpdateTemplateProjectParamOrderParams) error {
	_, err := q.db.ExecContext(ctx, updateTemplateProjectParamOrder, arg.ID, arg.Order)
	return err
}

const updateTemplateRole = `-- name: UpdateTemplateRole :one
UPDATE template_roles
SET name = $2, description = $3
WHERE id = $1
RETURNING id, template_id, name, description, is_default, "order"
`

type UpdateTemplateRoleParams struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
}

func (q *Queries) UpdateTemplateRole(ctx context.Context, arg UpdateTemplateRoleParams) (TemplateRole, error) {
	row := q.db.QueryRowContext(ctx, updateTemplateRole, arg.ID, arg.Name, arg.Description)
	var i TemplateRole
	err := row.Scan(
		&i.ID,
		&i.TemplateID,
		&i.Name,
		&i.Description,
		&i.IsDefault,
		&i.Order,
	)
	return i, err
}

const updateTemplateRoleOrder = `-- name: UpdateTemplateRoleOrder :exec
UPDATE template_roles SET "order" = $2 WHERE id = $1
`

type UpdateTemplateRoleOrderParams struct {
	ID    uuid.UUID `json:"id"`
	Order int32     `json:"order"`
}

func (q *Queries) UpdateTemplateRoleOrder(ctx context.Context, arg UpdateTemplateRoleOrderParams) error {
	_, err := q.db.ExecContext(ctx, updateTemplateRoleOrder, arg.ID, arg.Order)
	return err
}

const upsertTemplateRolePermission = `-- name: UpsertTemplateRolePermission :exec
INSERT INTO template_role_permissions (role_id, area, access)
VALUES ($1, $2, $3)
ON CONFLICT (role_id, area) DO UPDATE SET access = EXCLUDED.access
`

type UpsertTemplateRolePermissionParams struct {
	RoleID uuid.UUID `json:"role_id"`
	Area   string    `json:"area"`
	Access string    `json:"access"`
}

func (q *Queries) UpsertTemplateRolePermission(ctx context.Context, arg UpsertTemplateRolePermissionParams) error {
	_, err := q.db.ExecContext(ctx, upsertTemplateRolePermission, arg.RoleID, arg.Area, arg.Access)
	return err
}
