// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: template_params_and_roles.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const countTemplateRolesByTemplateID = `-- name: CountTemplateRolesByTemplateID :one
SELECT COUNT(*)::int AS count FROM roles WHERE template_id = $1
`

func (q *Queries) CountTemplateRolesByTemplateID(ctx context.Context, templateID uuid.NullUUID) (int32, error) {
	row := q.db.QueryRowContext(ctx, countTemplateRolesByTemplateID, templateID)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const createTemplateProjectParam = `-- name: CreateTemplateProjectParam :one
INSERT INTO fields (kind, template_id, name, description, field_type, is_required, options)
VALUES ('project_param', $1, $2, $3, $4, $5, $6)
RETURNING id, template_id, name, description, field_type, is_system, is_required, options
`

type CreateTemplateProjectParamParams struct {
	TemplateID  uuid.NullUUID         `json:"template_id"`
	Name        string                `json:"name"`
	Description string                `json:"description"`
	FieldType   string                `json:"field_type"`
	IsRequired  bool                  `json:"is_required"`
	Options     pqtype.NullRawMessage `json:"options"`
}

type CreateTemplateProjectParamRow struct {
	ID          uuid.UUID             `json:"id"`
	TemplateID  uuid.NullUUID         `json:"template_id"`
	Name        string                `json:"name"`
	Description string                `json:"description"`
	FieldType   string                `json:"field_type"`
	IsSystem    bool                  `json:"is_system"`
	IsRequired  bool                  `json:"is_required"`
	Options     pqtype.NullRawMessage `json:"options"`
}

func (q *Queries) CreateTemplateProjectParam(ctx context.Context, arg CreateTemplateProjectParamParams) (CreateTemplateProjectParamRow, error) {
	row := q.db.QueryRowContext(ctx, createTemplateProjectParam,
		arg.TemplateID,
		arg.Name,
		arg.Description,
		arg.FieldType,
		arg.IsRequired,
		arg.Options,
	)
	var i CreateTemplateProjectParamRow
	err := row.Scan(
		&i.ID,
		&i.TemplateID,
		&i.Name,
		&i.Description,
		&i.FieldType,
		&i.IsSystem,
		&i.IsRequired,
		&i.Options,
	)
	return i, err
}

const createTemplateRole = `-- name: CreateTemplateRole :one
INSERT INTO roles (template_id, scope, name, description)
VALUES ($1, 'template', $2, $3)
RETURNING id, template_id, name, description, is_admin
`

type CreateTemplateRoleParams struct {
	TemplateID  uuid.NullUUID `json:"template_id"`
	Name        string        `json:"name"`
	Description string        `json:"description"`
}

type CreateTemplateRoleRow struct {
	ID          uuid.UUID     `json:"id"`
	TemplateID  uuid.NullUUID `json:"template_id"`
	Name        string        `json:"name"`
	Description string        `json:"description"`
	IsAdmin     bool          `json:"is_admin"`
}

func (q *Queries) CreateTemplateRole(ctx context.Context, arg CreateTemplateRoleParams) (CreateTemplateRoleRow, error) {
	row := q.db.QueryRowContext(ctx, createTemplateRole, arg.TemplateID, arg.Name, arg.Description)
	var i CreateTemplateRoleRow
	err := row.Scan(
		&i.ID,
		&i.TemplateID,
		&i.Name,
		&i.Description,
		&i.IsAdmin,
	)
	return i, err
}

const deleteTemplateProjectParamByID = `-- name: DeleteTemplateProjectParamByID :exec
DELETE FROM fields WHERE id = $1 AND kind = 'project_param'
`

func (q *Queries) DeleteTemplateProjectParamByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteTemplateProjectParamByID, id)
	return err
}

const deleteTemplateRoleByID = `-- name: DeleteTemplateRoleByID :exec
DELETE FROM roles WHERE id = $1
`

func (q *Queries) DeleteTemplateRoleByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteTemplateRoleByID, id)
	return err
}

const deleteTemplateRolePermissionsByRoleID = `-- name: DeleteTemplateRolePermissionsByRoleID :exec
DELETE FROM role_permissions WHERE role_id = $1
`

func (q *Queries) DeleteTemplateRolePermissionsByRoleID(ctx context.Context, roleID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteTemplateRolePermissionsByRoleID, roleID)
	return err
}

const getTemplateProjectParamByID = `-- name: GetTemplateProjectParamByID :one
SELECT id, template_id, name, description, field_type, is_system, is_required, options
FROM fields
WHERE id = $1 AND kind = 'project_param'
`

type GetTemplateProjectParamByIDRow struct {
	ID          uuid.UUID             `json:"id"`
	TemplateID  uuid.NullUUID         `json:"template_id"`
	Name        string                `json:"name"`
	Description string                `json:"description"`
	FieldType   string                `json:"field_type"`
	IsSystem    bool                  `json:"is_system"`
	IsRequired  bool                  `json:"is_required"`
	Options     pqtype.NullRawMessage `json:"options"`
}

func (q *Queries) GetTemplateProjectParamByID(ctx context.Context, id uuid.UUID) (GetTemplateProjectParamByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getTemplateProjectParamByID, id)
	var i GetTemplateProjectParamByIDRow
	err := row.Scan(
		&i.ID,
		&i.TemplateID,
		&i.Name,
		&i.Description,
		&i.FieldType,
		&i.IsSystem,
		&i.IsRequired,
		&i.Options,
	)
	return i, err
}

const getTemplateRoleByID = `-- name: GetTemplateRoleByID :one
SELECT id, template_id, name, description, is_admin
FROM roles
WHERE id = $1
`

type GetTemplateRoleByIDRow struct {
	ID          uuid.UUID     `json:"id"`
	TemplateID  uuid.NullUUID `json:"template_id"`
	Name        string        `json:"name"`
	Description string        `json:"description"`
	IsAdmin     bool          `json:"is_admin"`
}

func (q *Queries) GetTemplateRoleByID(ctx context.Context, id uuid.UUID) (GetTemplateRoleByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getTemplateRoleByID, id)
	var i GetTemplateRoleByIDRow
	err := row.Scan(
		&i.ID,
		&i.TemplateID,
		&i.Name,
		&i.Description,
		&i.IsAdmin,
	)
	return i, err
}

const listTemplateProjectParams = `-- name: ListTemplateProjectParams :many

SELECT id, template_id, name, description, field_type, is_system, is_required, options
FROM fields
WHERE template_id = $1 AND kind = 'project_param'
`

type ListTemplateProjectParamsRow struct {
	ID          uuid.UUID             `json:"id"`
	TemplateID  uuid.NullUUID         `json:"template_id"`
	Name        string                `json:"name"`
	Description string                `json:"description"`
	FieldType   string                `json:"field_type"`
	IsSystem    bool                  `json:"is_system"`
	IsRequired  bool                  `json:"is_required"`
	Options     pqtype.NullRawMessage `json:"options"`
}

// Template project params (in unified `fields` table, kind='project_param')
func (q *Queries) ListTemplateProjectParams(ctx context.Context, templateID uuid.NullUUID) ([]ListTemplateProjectParamsRow, error) {
	rows, err := q.db.QueryContext(ctx, listTemplateProjectParams, templateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTemplateProjectParamsRow{}
	for rows.Next() {
		var i ListTemplateProjectParamsRow
		if err := rows.Scan(
			&i.ID,
			&i.TemplateID,
			&i.Name,
			&i.Description,
			&i.FieldType,
			&i.IsSystem,
			&i.IsRequired,
			&i.Options,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTemplateRolePermissions = `-- name: ListTemplateRolePermissions :many

SELECT rp.role_id, rp.permission_code, rp.access
FROM role_permissions rp
WHERE rp.role_id = $1
`

// Template role permissions (uses permission_code directly)
func (q *Queries) ListTemplateRolePermissions(ctx context.Context, roleID uuid.UUID) ([]RolePermission, error) {
	rows, err := q.db.QueryContext(ctx, listTemplateRolePermissions, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RolePermission{}
	for rows.Next() {
		var i RolePermission
		if err := rows.Scan(&i.RoleID, &i.PermissionCode, &i.Access); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTemplateRoles = `-- name: ListTemplateRoles :many

SELECT id, template_id, name, description, is_admin
FROM roles
WHERE template_id = $1
`

type ListTemplateRolesRow struct {
	ID          uuid.UUID     `json:"id"`
	TemplateID  uuid.NullUUID `json:"template_id"`
	Name        string        `json:"name"`
	Description string        `json:"description"`
	IsAdmin     bool          `json:"is_admin"`
}

// Template roles (in unified roles table, scope='template')
func (q *Queries) ListTemplateRoles(ctx context.Context, templateID uuid.NullUUID) ([]ListTemplateRolesRow, error) {
	rows, err := q.db.QueryContext(ctx, listTemplateRoles, templateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTemplateRolesRow{}
	for rows.Next() {
		var i ListTemplateRolesRow
		if err := rows.Scan(
			&i.ID,
			&i.TemplateID,
			&i.Name,
			&i.Description,
			&i.IsAdmin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTemplateProjectParam = `-- name: UpdateTemplateProjectParam :one
UPDATE fields
SET name = $2, is_required = $3, options = $4
WHERE id = $1 AND kind = 'project_param'
RETURNING id, template_id, name, description, field_type, is_system, is_required, options
`

type UpdateTemplateProjectParamParams struct {
	ID         uuid.UUID             `json:"id"`
	Name       string                `json:"name"`
	IsRequired bool                  `json:"is_required"`
	Options    pqtype.NullRawMessage `json:"options"`
}

type UpdateTemplateProjectParamRow struct {
	ID          uuid.UUID             `json:"id"`
	TemplateID  uuid.NullUUID         `json:"template_id"`
	Name        string                `json:"name"`
	Description string                `json:"description"`
	FieldType   string                `json:"field_type"`
	IsSystem    bool                  `json:"is_system"`
	IsRequired  bool                  `json:"is_required"`
	Options     pqtype.NullRawMessage `json:"options"`
}

func (q *Queries) UpdateTemplateProjectParam(ctx context.Context, arg UpdateTemplateProjectParamParams) (UpdateTemplateProjectParamRow, error) {
	row := q.db.QueryRowContext(ctx, updateTemplateProjectParam,
		arg.ID,
		arg.Name,
		arg.IsRequired,
		arg.Options,
	)
	var i UpdateTemplateProjectParamRow
	err := row.Scan(
		&i.ID,
		&i.TemplateID,
		&i.Name,
		&i.Description,
		&i.FieldType,
		&i.IsSystem,
		&i.IsRequired,
		&i.Options,
	)
	return i, err
}

const updateTemplateRole = `-- name: UpdateTemplateRole :one
UPDATE roles
SET name = $2, description = $3
WHERE id = $1
RETURNING id, template_id, name, description, is_admin
`

type UpdateTemplateRoleParams struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
}

type UpdateTemplateRoleRow struct {
	ID          uuid.UUID     `json:"id"`
	TemplateID  uuid.NullUUID `json:"template_id"`
	Name        string        `json:"name"`
	Description string        `json:"description"`
	IsAdmin     bool          `json:"is_admin"`
}

func (q *Queries) UpdateTemplateRole(ctx context.Context, arg UpdateTemplateRoleParams) (UpdateTemplateRoleRow, error) {
	row := q.db.QueryRowContext(ctx, updateTemplateRole, arg.ID, arg.Name, arg.Description)
	var i UpdateTemplateRoleRow
	err := row.Scan(
		&i.ID,
		&i.TemplateID,
		&i.Name,
		&i.Description,
		&i.IsAdmin,
	)
	return i, err
}

const upsertTemplateRolePermission = `-- name: UpsertTemplateRolePermission :exec
INSERT INTO role_permissions (role_id, permission_code, access)
VALUES ($1, $2, $3)
ON CONFLICT (role_id, permission_code) DO UPDATE SET access = EXCLUDED.access
`

type UpsertTemplateRolePermissionParams struct {
	RoleID         uuid.UUID      `json:"role_id"`
	PermissionCode string         `json:"permission_code"`
	Access         sql.NullString `json:"access"`
}

func (q *Queries) UpsertTemplateRolePermission(ctx context.Context, arg UpsertTemplateRolePermissionParams) error {
	_, err := q.db.ExecContext(ctx, upsertTemplateRolePermission, arg.RoleID, arg.PermissionCode, arg.Access)
	return err
}
