// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const countSearchUsers = `-- name: CountSearchUsers :one
SELECT COUNT(*)::bigint
FROM users
WHERE deleted_at IS NULL
  AND ($1::text IS NULL OR $1::text = '' OR (
   username ILIKE '%' || $1 || '%'
   OR email ILIKE '%' || $1 || '%'
   OR full_name ILIKE '%' || $1 || '%'
   OR position ILIKE '%' || $1 || '%'
   OR alt_contact_info ILIKE '%' || $1 || '%'))
`

// Полное количество пользователей, подходящих под фильтр q — без учёта limit/offset.
// Используется эндпоинтом GET /users для возврата поля `total` рядом с массивом
// пользователей.
func (q *Queries) CountSearchUsers(ctx context.Context, dollar_1 string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSearchUsers, dollar_1)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, email, password_hash, full_name, avatar_url)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, username, email, password_hash, full_name, avatar_url, position,
          is_active, on_vacation, is_sick, alt_contact_channel, alt_contact_info, deleted_at, blocked_until
`

type CreateUserParams struct {
	Username     string         `json:"username"`
	Email        string         `json:"email"`
	PasswordHash string         `json:"password_hash"`
	FullName     string         `json:"full_name"`
	AvatarUrl    sql.NullString `json:"avatar_url"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
		arg.FullName,
		arg.AvatarUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.AvatarUrl,
		&i.Position,
		&i.IsActive,
		&i.OnVacation,
		&i.IsSick,
		&i.AltContactChannel,
		&i.AltContactInfo,
		&i.DeletedAt,
		&i.BlockedUntil,
	)
	return i, err
}

const getLastNPasswordHashes = `-- name: GetLastNPasswordHashes :many
SELECT password_hash
FROM password_history
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type GetLastNPasswordHashesParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
}

func (q *Queries) GetLastNPasswordHashes(ctx context.Context, arg GetLastNPasswordHashesParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getLastNPasswordHashes, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var password_hash string
		if err := rows.Scan(&password_hash); err != nil {
			return nil, err
		}
		items = append(items, password_hash)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, email, password_hash, full_name, avatar_url, position,
       is_active, on_vacation, is_sick, alt_contact_channel, alt_contact_info, deleted_at, blocked_until
FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.AvatarUrl,
		&i.Position,
		&i.IsActive,
		&i.OnVacation,
		&i.IsSick,
		&i.AltContactChannel,
		&i.AltContactInfo,
		&i.DeletedAt,
		&i.BlockedUntil,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, email, password_hash, full_name, avatar_url, position,
       is_active, on_vacation, is_sick, alt_contact_channel, alt_contact_info, deleted_at, blocked_until
FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.AvatarUrl,
		&i.Position,
		&i.IsActive,
		&i.OnVacation,
		&i.IsSick,
		&i.AltContactChannel,
		&i.AltContactInfo,
		&i.DeletedAt,
		&i.BlockedUntil,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, email, password_hash, full_name, avatar_url, position,
       is_active, on_vacation, is_sick, alt_contact_channel, alt_contact_info, deleted_at, blocked_until
FROM users
WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.AvatarUrl,
		&i.Position,
		&i.IsActive,
		&i.OnVacation,
		&i.IsSick,
		&i.AltContactChannel,
		&i.AltContactInfo,
		&i.DeletedAt,
		&i.BlockedUntil,
	)
	return i, err
}

const insertPasswordHistory = `-- name: InsertPasswordHistory :exec
INSERT INTO password_history (user_id, password_hash)
VALUES ($1, $2)
`

type InsertPasswordHistoryParams struct {
	UserID       uuid.UUID `json:"user_id"`
	PasswordHash string    `json:"password_hash"`
}

func (q *Queries) InsertPasswordHistory(ctx context.Context, arg InsertPasswordHistoryParams) error {
	_, err := q.db.ExecContext(ctx, insertPasswordHistory, arg.UserID, arg.PasswordHash)
	return err
}

const listAllUserIDs = `-- name: ListAllUserIDs :many
SELECT id
FROM users
`

func (q *Queries) ListAllUserIDs(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.QueryContext(ctx, listAllUserIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchUsers = `-- name: SearchUsers :many
SELECT id, username, email, password_hash, full_name, avatar_url, position,
       is_active, on_vacation, is_sick, alt_contact_channel, alt_contact_info, deleted_at, blocked_until
FROM users
WHERE deleted_at IS NULL
  AND ($1::text IS NULL OR $1::text = '' OR (
   username ILIKE '%' || $1 || '%'
   OR email ILIKE '%' || $1 || '%'
   OR full_name ILIKE '%' || $1 || '%'
   OR position ILIKE '%' || $1 || '%'
   OR alt_contact_info ILIKE '%' || $1 || '%'))
ORDER BY LOWER(full_name) ASC, id ASC
LIMIT $2 OFFSET $3
`

type SearchUsersParams struct {
	Column1 string `json:"column_1"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

// Порядок: ORDER BY LOWER(full_name) ASC (регистро-независимо, кириллица
// сортируется корректно), id ASC как вторичный ключ — стабильный
// tiebreaker для равных ФИО, чтобы пагинация не «скакала».
func (q *Queries) SearchUsers(ctx context.Context, arg SearchUsersParams) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, searchUsers, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.PasswordHash,
			&i.FullName,
			&i.AvatarUrl,
			&i.Position,
			&i.IsActive,
			&i.OnVacation,
			&i.IsSick,
			&i.AltContactChannel,
			&i.AltContactInfo,
			&i.DeletedAt,
			&i.BlockedUntil,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserAvatar = `-- name: UpdateUserAvatar :exec
UPDATE users
SET avatar_url = $2
WHERE id = $1
`

type UpdateUserAvatarParams struct {
	ID        uuid.UUID      `json:"id"`
	AvatarUrl sql.NullString `json:"avatar_url"`
}

func (q *Queries) UpdateUserAvatar(ctx context.Context, arg UpdateUserAvatarParams) error {
	_, err := q.db.ExecContext(ctx, updateUserAvatar, arg.ID, arg.AvatarUrl)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users
SET password_hash = $2
WHERE id = $1
`

type UpdateUserPasswordParams struct {
	ID           uuid.UUID `json:"id"`
	PasswordHash string    `json:"password_hash"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.ExecContext(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	return err
}

const updateUserProfile = `-- name: UpdateUserProfile :exec
UPDATE users
SET full_name = $2,
    email     = $3,
    position  = $4,
    on_vacation = $5,
    is_sick     = $6,
    alt_contact_channel = $7,
    alt_contact_info    = $8
WHERE id = $1
`

type UpdateUserProfileParams struct {
	ID                uuid.UUID      `json:"id"`
	FullName          string         `json:"full_name"`
	Email             string         `json:"email"`
	Position          sql.NullString `json:"position"`
	OnVacation        bool           `json:"on_vacation"`
	IsSick            bool           `json:"is_sick"`
	AltContactChannel sql.NullString `json:"alt_contact_channel"`
	AltContactInfo    sql.NullString `json:"alt_contact_info"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) error {
	_, err := q.db.ExecContext(ctx, updateUserProfile,
		arg.ID,
		arg.FullName,
		arg.Email,
		arg.Position,
		arg.OnVacation,
		arg.IsSick,
		arg.AltContactChannel,
		arg.AltContactInfo,
	)
	return err
}
